# Generated By: Claude Code (Claude Opus 4.6)
.PHONY: default help install install-dev install-hooks uninstall clean format format-check lint typecheck test test-verbose coverage check run run-debug

PYTHON := python3

default: check

check: format-check lint typecheck test coverage

help:
	@echo "Targets:"
	@echo "  install        Install package"
	@echo "  install-dev    Install package and dev dependencies (run once)"
	@echo "  uninstall      Uninstall package"
	@echo "  clean          Remove build artifacts and caches"
	@echo "  format         Run black formatter (modifies files)"
	@echo "  format-check   Check formatting without modifying files"
	@echo "  lint           Run flake8"
	@echo "  typecheck      Run mypy"
	@echo "  test           Run tests"
	@echo "  test-verbose   Run tests with verbose output"
	@echo "  coverage       Run tests with coverage report"
	@echo "  check          Run format-check, lint, typecheck, test, coverage (default)"
	@echo "  run            Start the app"
	@echo "  run-debug      Start the app with debug logging"

install:
	$(PYTHON) -m pip install .

install-dev:
	$(PYTHON) -m pip install -e ".[dev]"

install-hooks:
	$(PYTHON) scripts/install_hooks.py

uninstall:
	$(PYTHON) -m pip uninstall -y claude-dashboard

clean:
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true
	rm -rf .pytest_cache .mypy_cache .coverage htmlcov

format: install-dev
	$(PYTHON) -m black claude_dashboard/ tests/

format-check: install-dev
	$(PYTHON) -m black --check claude_dashboard/ tests/

lint: install-dev
	$(PYTHON) -m flake8 claude_dashboard/ tests/

typecheck: install-dev
	$(PYTHON) -m mypy claude_dashboard/

test: install-dev
	$(PYTHON) -m pytest

test-verbose: install-dev
	$(PYTHON) -m pytest -v

coverage: install-dev
	$(PYTHON) -m pytest --cov=claude_dashboard --cov-report=term-missing

run:
	$(PYTHON) -m claude_dashboard

run-debug:
	$(PYTHON) -m claude_dashboard --debug
