# Generated By: Claude Code (Claude Opus 4.6)
PACKAGE_NAME ?= claude_dashboard

.PHONY: help install install-no-deps install-dev install-hooks uninstall clean format format-check lint typecheck test test-verbose coverage check markdown-lint links mutation mutation-report run

ifeq ($(OS),Windows_NT)
    VENV_DIR ?= .venv
    PYTHON := $(VENV_DIR)/Scripts/python.exe
else
    VENV_DIR ?= .venv
    PYTHON := $(VENV_DIR)/bin/python
endif
LOG_FILE := ~/.claude/claude-dashboard/dashboard.log

.DEFAULT_GOAL := check

$(PYTHON):
	python3 -m venv $(VENV_DIR)

check: format lint typecheck markdown-lint links test coverage ## Run all checks (default)

help: ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

install: ## Install package
	$(PYTHON) -m pip install .

install-no-deps: $(PYTHON) ## Install editable without dependencies
	$(PYTHON) -m pip install --no-deps -e .

install-dev: $(PYTHON) ## Install package and dev dependencies (editable)
	$(PYTHON) -m pip install -e ".[dev]"

install-hooks: ## Merge hook config into ~/.claude/settings.json
	$(PYTHON) scripts/install_hooks.py

uninstall: ## Uninstall package
	$(PYTHON) -m pip uninstall -y claude-dashboard

clean: ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true
	rm -rf .pytest_cache .mypy_cache .coverage htmlcov

format: install-dev ## Run black formatter (modifies files)
	$(PYTHON) -m black $(PACKAGE_NAME)/ tests/

format-check: install-dev ## Check formatting without modifying files
	$(PYTHON) -m black --check $(PACKAGE_NAME)/ tests/

lint: install-dev ## Run flake8
	$(PYTHON) -m flake8 $(PACKAGE_NAME)/ tests/

typecheck: install-dev ## Run mypy
	$(PYTHON) -m mypy $(PACKAGE_NAME)/

test: install-dev ## Run tests
	$(PYTHON) -m pytest

test-verbose: install-dev ## Run tests with verbose output
	$(PYTHON) -m pytest -v

coverage: install-dev ## Run tests with coverage report
	$(PYTHON) -m pytest --cov=$(PACKAGE_NAME) --cov-report=term-missing

markdown-lint: install-dev ## Lint markdown files
	$(PYTHON) -m pymarkdown --disable-rules MD013,MD024,MD031,MD036 scan README.md CLAUDE.md docs/ specs/

links: ## Validate local markdown links and anchors
	$(PYTHON) scripts/check-links.py

mutation: install-dev ## Run mutation testing (not part of check — run in CI or on-demand)
	$(PYTHON) -m mutmut run --CI --paths-to-mutate "$(PACKAGE_NAME)/"

mutation-report: ## Show results of last mutation run
	$(PYTHON) -m mutmut results

run: ## Start the app (always debug to file, rotated at 2 MB)
	@echo "Logging to $(LOG_FILE)"
	$(PYTHON) -m claude_dashboard --debug --log-file $(LOG_FILE)
