# Generated By: Claude Code (Claude Opus 4.6)

PACKAGE_NAME ?= claude_dashboard

ifeq ($(OS),Windows_NT)
    VENV_DIR ?= .venv
    PYTHON := $(VENV_DIR)/Scripts/python.exe
    PYTHON_BOOTSTRAP := py -3
else
    VENV_DIR ?= .venv
    PYTHON := $(VENV_DIR)/bin/python
    PYTHON_BOOTSTRAP := python3
endif

$(info venv: $(VENV_DIR))

check: format lint typecheck markdown-lint links test coverage  ## Run all checks (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	$(PYTHON_BOOTSTRAP) -m venv $(VENV_DIR)

install: $(PYTHON)  ## Install package
	$(PYTHON) -m pip install .

install-dev: $(PYTHON)  ## Install in editable mode with dev deps
	$(PYTHON) -m pip install -e ".[dev]"

install-no-deps: $(PYTHON)  ## Install in editable mode without dependencies
	$(PYTHON) -m pip install -e . --no-deps

install-hooks: $(PYTHON)  ## Merge hook config into ~/.claude/settings.json
	$(PYTHON) scripts/install_hooks.py

uninstall: $(PYTHON)  ## Uninstall package
	$(PYTHON) -m pip uninstall -y claude-dashboard

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true
	rm -rf .pytest_cache .mypy_cache .coverage htmlcov

format: install-dev  ## Format code with black
	$(PYTHON) -m black $(PACKAGE_NAME) tests

format-check: install-dev  ## Check formatting without modifying files
	$(PYTHON) -m black --check $(PACKAGE_NAME) tests

lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 $(PACKAGE_NAME) tests

typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(PACKAGE_NAME)

test: install-dev  ## Run pytest
	$(PYTHON) -m pytest

test-verbose: install-dev  ## Run pytest with verbose output
	$(PYTHON) -m pytest -v

coverage: install-dev  ## Run pytest with coverage
	$(PYTHON) -m pytest --cov=$(PACKAGE_NAME) --cov-report=term

markdown-lint: install-dev  ## Lint markdown files
	$(PYTHON) -m pymarkdown --disable-rules MD013,MD024,MD031,MD036 scan README.md CLAUDE.md docs/ specs/

links: $(PYTHON)  ## Validate local markdown links and anchors
	$(PYTHON) scripts/check-links.py

mutation: install-dev  ## Run mutation testing (not part of check — run in CI or on-demand)
	$(PYTHON) -m mutmut run --CI --paths-to-mutate "$(PACKAGE_NAME)"

mutation-report: $(PYTHON)  ## Show results of last mutation run
	$(PYTHON) -m mutmut results

-include make/run.mk

.PHONY: check help install install-dev install-no-deps install-hooks uninstall clean format format-check lint typecheck test test-verbose coverage markdown-lint links mutation mutation-report
