# Generated By: Claude Code (Claude Opus 4.6)
"""Linux-specific platform operations — process tree, window foregrounding.

Stub implementation. To be tested and refined on Linux.
Uses xdotool for X11 window management.
"""

import logging
import subprocess

import psutil

from claude_dashboard.platform.base import ContainerInfo, ContainerType

logger = logging.getLogger(__name__)

# Known Linux terminal emulators
_TERMINAL_NAMES = {
    "gnome-terminal-server",
    "konsole",
    "xfce4-terminal",
    "alacritty",
    "kitty",
    "wezterm-gui",
    "terminator",
    "tilix",
    "xterm",
    "urxvt",
    "st",
}


def detect_container_linux(pid: int) -> ContainerInfo:
    """Walk the parent process chain to identify the containing application."""
    container = ContainerInfo()

    try:
        claude_proc = psutil.Process(pid)
        current = claude_proc.parent()

        while current:
            name = current.name().lower()

            if "code" in name:
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.VSCODE
                break

            if name in _TERMINAL_NAMES:
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.TERMINAL
                break

            if name == "screen":
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.SCREEN
                # Keep walking to find the terminal hosting screen
                try:
                    current = current.parent()
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    break
                continue

            try:
                current = current.parent()
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                break

    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass

    return container


def foreground_window_linux(window_id: int) -> bool:
    """Bring a window to the foreground using xdotool."""
    try:
        subprocess.run(
            ["xdotool", "windowactivate", str(window_id)],
            check=True,
            capture_output=True,
            timeout=3,
        )
        return True
    except FileNotFoundError:
        logger.warning("xdotool not installed — cannot foreground windows")
        return False
    except subprocess.CalledProcessError as exc:
        logger.debug("xdotool failed error=%s", exc)
        return False
    except subprocess.TimeoutExpired:
        logger.debug("xdotool timed out")
        return False
