# Generated By: Claude Code (Claude Opus 4.6)
"""Linux-specific platform operations — process tree, window matching, foregrounding.

Uses the `window-calls` GNOME Shell extension for Wayland-native window
enumeration and activation via D-Bus. Falls back to the `code` CLI
for VS Code windows if the extension is not available.

Tested on Fedora 42 / GNOME Shell 48.7 / Wayland (2026-03-23).
See scripts/detect_sessions_linux.py for the diagnostic script that
validated this approach.
"""

import json
import logging
import subprocess

import psutil

from claude_dashboard.platform.base import ContainerInfo, ContainerType

logger = logging.getLogger(__name__)

# Known Linux terminal emulators
_TERMINAL_NAMES = {
    "gnome-terminal-server",
    "konsole",
    "xfce4-terminal",
    "alacritty",
    "kitty",
    "wezterm-gui",
    "terminator",
    "tilix",
    "xterm",
    "urxvt",
    "st",
    "foot",
    "ghostty",
}

# D-Bus constants for the window-calls GNOME Shell extension
_DBUS_DEST = "org.gnome.Shell"
_DBUS_PATH = "/org/gnome/Shell/Extensions/Windows"
_DBUS_IFACE = "org.gnome.Shell.Extensions.Windows"


def detect_container_linux(pid: int) -> ContainerInfo:
    """Walk the parent process chain to identify the containing application."""
    container = ContainerInfo()

    try:
        claude_proc = psutil.Process(pid)
        current = claude_proc.parent()

        while current:
            name = current.name().lower()

            if name == "code" or name.startswith("code-"):
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.VSCODE
                break

            if name in _TERMINAL_NAMES:
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.TERMINAL
                break

            if name == "screen":
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.SCREEN
                # Keep walking to find the terminal hosting screen
                try:
                    current = current.parent()
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    break
                continue

            if name == "tmux: server" or name.startswith("tmux"):
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = ContainerType.TERMINAL
                break

            try:
                current = current.parent()
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                break

        # Fallback: check TERM_PROGRAM env var
        if container.container_type == ContainerType.UNKNOWN:
            try:
                env = claude_proc.parent().environ()
                term_prog = env.get("TERM_PROGRAM", "").lower()
                del env
                if term_prog == "vscode":
                    container.container_type = ContainerType.VSCODE
                elif term_prog:
                    container.container_type = ContainerType.TERMINAL
                    container.process_name = term_prog
            except (psutil.AccessDenied, psutil.NoSuchProcess, AttributeError):
                pass

    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass

    return container


def _list_windows_dbus() -> list[dict]:
    """List all windows via the window-calls GNOME Shell extension D-Bus interface.

    Returns a list of dicts with keys: id, pid, title, wm_class, workspace, etc.
    Returns empty list if the extension is not installed or the call fails.
    """
    try:
        result = subprocess.run(
            [
                "gdbus",
                "call",
                "--session",
                "--dest",
                _DBUS_DEST,
                "--object-path",
                _DBUS_PATH,
                "--method",
                f"{_DBUS_IFACE}.List",
            ],
            capture_output=True,
            text=True,
            timeout=3,
        )
        if result.returncode != 0:
            logger.debug("window-calls List failed: %s", result.stderr.strip()[:200])
            return []

        raw = result.stdout.strip()
        # gdbus wraps output as ('json_string',)
        if raw.startswith("('") and raw.endswith("',)"):
            json_str = raw[2:-3]
        elif raw.startswith("('") and raw.endswith("')"):
            json_str = raw[2:-2]
        else:
            logger.debug("unexpected gdbus output format: %s", raw[:100])
            return []

        return json.loads(json_str)
    except FileNotFoundError:
        logger.debug("gdbus not found")
        return []
    except subprocess.TimeoutExpired:
        logger.debug("gdbus List timed out")
        return []
    except (json.JSONDecodeError, ValueError) as exc:
        logger.debug("failed to parse window list: %s", exc)
        return []


def _activate_window_dbus(window_id: int) -> bool:
    """Activate (foreground) a window by ID via window-calls D-Bus."""
    try:
        result = subprocess.run(
            [
                "gdbus",
                "call",
                "--session",
                "--dest",
                _DBUS_DEST,
                "--object-path",
                _DBUS_PATH,
                "--method",
                f"{_DBUS_IFACE}.Activate",
                str(window_id),
            ],
            capture_output=True,
            text=True,
            timeout=3,
        )
        if result.returncode == 0:
            return True
        logger.debug("window-calls Activate failed: %s", result.stderr.strip()[:200])
        return False
    except FileNotFoundError:
        logger.debug("gdbus not found")
        return False
    except subprocess.TimeoutExpired:
        logger.debug("gdbus Activate timed out")
        return False


def _find_window_id_for_session(
    container: ContainerInfo,
    *,
    cwd: str = "",
) -> int:
    """Find the window ID for a session's container using window-calls.

    Matches by PID (container process or its parent tree) and optionally
    by CWD folder name in the window title for VS Code disambiguation.
    """
    windows = _list_windows_dbus()
    if not windows:
        return 0

    # Collect PIDs in the container's process tree
    target_pids = set()
    if container.process_pid:
        target_pids.add(container.process_pid)
        try:
            proc = psutil.Process(container.process_pid)
            # Walk up to find the top-level process
            parent = proc.parent()
            while parent and parent.pid > 1:
                if parent.name().lower() in ("systemd", "init"):
                    break
                target_pids.add(parent.pid)
                parent = parent.parent()
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass

    # Find windows owned by any PID in the tree
    candidates = [w for w in windows if w.get("pid") in target_pids]

    if not candidates:
        return 0

    # For VS Code with multiple windows, match by CWD folder name in title
    if cwd and len(candidates) > 1:
        from pathlib import Path

        folder_name = Path(cwd).name.lower()
        for w in candidates:
            title = w.get("title", "").lower()
            if folder_name in title:
                return w.get("id", 0)

    # Single candidate or no CWD match — use first
    return candidates[0].get("id", 0)


def _foreground_code_cli(cwd: str) -> bool:
    """Foreground a VS Code window using the `code` CLI.

    Fallback when window-calls extension is not available.
    `code /path` activates the window that has the folder open.
    """
    try:
        result = subprocess.run(
            ["code", cwd],
            capture_output=True,
            timeout=5,
        )
        return result.returncode == 0
    except FileNotFoundError:
        logger.debug("code CLI not found")
        return False
    except subprocess.TimeoutExpired:
        logger.debug("code CLI timed out")
        return False


def foreground_window_linux(container: ContainerInfo, *, cwd: str = "") -> bool:
    """Bring a container's window to the foreground on Linux.

    Strategy (in order):
    1. window-calls GNOME extension via D-Bus (Wayland-native, preferred)
    2. `code /path` CLI (VS Code-specific fallback)
    """
    # Strategy 1: window-calls D-Bus extension
    window_id = _find_window_id_for_session(container, cwd=cwd)
    if window_id:
        if _activate_window_dbus(window_id):
            return True
        logger.debug("window-calls Activate failed for id=%d", window_id)

    # Strategy 2: VS Code CLI fallback
    if container.container_type == ContainerType.VSCODE and cwd:
        return _foreground_code_cli(cwd)

    logger.debug(
        "no foreground method succeeded for %s pid=%d",
        container.container_type.value,
        container.process_pid,
    )
    return False
