# Generated By: Claude Code (Claude Opus 4.6)
"""Entry point for claude-dashboard."""

import argparse
import logging
import logging.handlers
import os
import sys
from pathlib import Path

from claude_dashboard import config

EXIT_SUCCESS = 0
EXIT_ERROR = 1


def _is_already_running() -> bool:
    """Check if another dashboard instance is running via PID file lock."""
    pid_path = config.PID_FILE
    pid_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        fd = os.open(str(pid_path), os.O_CREAT | os.O_RDWR, 0o644)
        if config.IS_WINDOWS:
            import msvcrt

            msvcrt.locking(fd, msvcrt.LK_NBLCK, 1)  # type: ignore[attr-defined]
        else:
            import fcntl

            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)  # type: ignore[attr-defined]
        os.write(fd, str(os.getpid()).encode())
        os.truncate(fd, len(str(os.getpid())))
        _is_already_running._lock_fd = fd  # type: ignore[attr-defined]
        return False
    except OSError:
        return True


def _send_toggle() -> int:
    """Tell the running dashboard to toggle visibility, then exit.

    This is the keyboard-shortcut entry point: bind `claude-dashboard --toggle`.
    """
    if config.IS_WINDOWS:
        print("ERROR: --toggle is not supported on Windows", file=sys.stderr)
        return EXIT_ERROR
    import signal

    try:
        pid = int(config.PID_FILE.read_text(encoding="utf-8").strip())
        os.kill(pid, signal.SIGUSR1)
    except (OSError, ValueError) as exc:
        print(f"ERROR: no running dashboard to toggle: {exc}", file=sys.stderr)
        return EXIT_ERROR
    return EXIT_SUCCESS


def _install_excepthook(*, logger: logging.Logger) -> None:
    """Route uncaught exceptions through the logger so they reach --log-file."""

    def _hook(exc_type, exc_value, exc_tb):
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_tb)
            return
        logger.critical("uncaught exception", exc_info=(exc_type, exc_value, exc_tb))

    sys.excepthook = _hook


def main():
    parser = argparse.ArgumentParser(description="Dashboard for monitoring Claude Code sessions")
    parser.add_argument("--debug", action="store_true", help="enable debug logging")
    parser.add_argument("--quiet", "-q", action="store_true", help="suppress non-essential output")
    parser.add_argument(
        "--ttl", type=int, default=0, help="auto-quit after N seconds (0 = run forever)"
    )
    parser.add_argument("--log-file", type=str, default=None, help="write log output to file")
    parser.add_argument(
        "--scale",
        type=float,
        default=None,
        help="DPI scale factor (default: auto-detect, or set CLAUDE_DASHBOARD_SCALE env var)",
    )
    parser.add_argument(
        "--reset-position",
        action="store_true",
        help="ignore the saved window position and start centered on screen",
    )
    parser.add_argument(
        "--toggle",
        action="store_true",
        help="toggle visibility of the running dashboard and exit (for keyboard shortcuts)",
    )
    args = parser.parse_args()

    if args.toggle:
        sys.exit(_send_toggle())

    log_fmt = "%(asctime)s %(levelname)s %(name)s: %(message)s"
    if args.log_file:
        level = logging.DEBUG if args.debug else logging.INFO
        if args.quiet:
            level = logging.WARNING
        log_path = str(Path(args.log_file).expanduser().resolve())
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            log_path,
            maxBytes=2 * 1024 * 1024,
            backupCount=1,
            encoding="utf-8",
        )
        handler.setFormatter(logging.Formatter(log_fmt))
        logging.basicConfig(level=level, handlers=[handler])
    else:
        level = logging.DEBUG if args.debug else (logging.WARNING if args.quiet else logging.INFO)
        logging.basicConfig(level=level, format=log_fmt, stream=sys.stderr)
    logging.getLogger("PIL").setLevel(logging.WARNING)

    _install_excepthook(logger=logging.getLogger(__name__))

    if _is_already_running():
        logging.getLogger(__name__).error("Claude Dashboard is already running (PID file locked)")
        sys.exit(EXIT_ERROR)

    if config.IS_LINUX:
        from claude_dashboard.platform.linux import (
            WINDOW_CALLS_NAME,
            WINDOW_CALLS_URL,
            window_calls_available,
        )

        if not window_calls_available():
            msg = (
                f"ERROR: required GNOME Shell extension '{WINDOW_CALLS_NAME}' is not "
                "responding on D-Bus.\n\n"
                "Without it the dashboard cannot see VS Code windows: sandbox rows render "
                "as disconnected (grey text, no tooltips) and window foregrounding fails.\n\n"
                f"Install and enable it: {WINDOW_CALLS_URL}\n"
                "Verify with: gnome-extensions list --enabled | grep -i window"
            )
            # stderr as well as the log — --log-file would otherwise swallow it.
            print(msg, file=sys.stderr)
            logging.getLogger(__name__).error(msg.replace("\n", " "))
            sys.exit(EXIT_ERROR)

    if config.IS_WINDOWS:
        import ctypes

        try:
            ctypes.windll.shcore.SetProcessDpiAwareness(1)
        except Exception:
            pass

    from claude_dashboard.controller import AppController

    app = AppController(
        debug=args.debug,
        quiet=args.quiet,
        ttl_seconds=args.ttl,
        dpi_scale=args.scale,
        reset_position_on_start=args.reset_position,
    )
    app.run()


if __name__ == "__main__":
    main()
