# Generated By: Claude Code (Claude Opus 4.6)
"""Main application controller — poll loop, state management, UI coordination."""

import logging
import threading
import tkinter as tk

from claude_dashboard.platform.base import (
    ContainerInfo,
    detect_container,
    find_window_for_session,
    foreground_window,
)
from claude_dashboard.session import (
    SessionInfo,
    discover_sessions,
    resolve_transcript_path,
    validate_pid,
)
from claude_dashboard.settings import Settings, load_settings, save_settings
from claude_dashboard.transcript import StatusState, detect_state
from claude_dashboard.tray import create_tray_icon, update_tray_icon
from claude_dashboard.ui.main_window import MainWindow
from claude_dashboard.ui.settings_window import SettingsWindow

logger = logging.getLogger(__name__)


class AppController:
    """Central controller that owns the Tk root and coordinates all subsystems."""

    def __init__(self, *, debug: bool = False, quiet: bool = False):
        self._debug = debug
        self._quiet = quiet
        self._settings = load_settings()

        self._root = tk.Tk()
        self._root.withdraw()  # Hidden root window

        self._main_window = MainWindow(
            self._root,
            self._settings,
            on_row_click=self._on_row_click,
            on_position_save=self._on_position_save,
        )

        # Cache: PID -> ContainerInfo (only re-detect for new sessions)
        self._container_cache: dict[int, ContainerInfo] = {}

        # System tray
        self._tray_icon = create_tray_icon(
            on_show=lambda icon, item: self._root.after(0, self._show_window),
            on_settings=lambda icon, item: self._root.after(0, self._open_settings),
            on_quit=lambda icon, item: self._root.after(0, self._quit),
        )
        self._needs_attention = False

    def run(self):
        """Start the application main loop."""
        logger.info("Claude Dashboard starting")

        # Start tray icon on a daemon thread
        tray_thread = threading.Thread(target=self._tray_icon.run, daemon=True)
        tray_thread.start()

        # Run initial tick immediately (it self-schedules the next tick)
        self._tick()

        self._root.mainloop()
        logger.info("Claude Dashboard stopped")

    def _tick(self):
        """Poll for session changes and update the UI."""
        try:
            sessions = discover_sessions()
            alive_pids = set()

            session_states = []
            any_needs_attention = False

            for session in sessions:
                if not validate_pid(session.pid):
                    continue
                session.pid_alive = True
                alive_pids.add(session.pid)

                transcript_path = resolve_transcript_path(session.cwd, session.session_id)
                state = detect_state(transcript_path)

                if state == StatusState.PERMISSION_REQUIRED:
                    any_needs_attention = True

                # Detect container for new sessions (cached)
                if session.pid not in self._container_cache:
                    container = detect_container(session.pid)
                    container = find_window_for_session(session.cwd, container)
                    self._container_cache[session.pid] = container

                cached_container = self._container_cache.get(session.pid)
                session_states.append((session, state, cached_container))

            # Evict dead sessions from cache
            stale = set(self._container_cache.keys()) - alive_pids
            for pid in stale:
                del self._container_cache[pid]

            self._main_window.update_sessions(session_states)

            # Update tray icon attention state
            if any_needs_attention != self._needs_attention:
                self._needs_attention = any_needs_attention
                update_tray_icon(self._tray_icon, attention=any_needs_attention)

        except Exception as exc:
            logger.error("tick failed error=%s", exc)

        # Schedule next tick
        tick_ms = self._settings.poll_interval_seconds * 1000
        self._root.after(tick_ms, self._tick)

    def _on_row_click(self, session: SessionInfo):
        """Handle click on a session row — foreground the containing window."""
        logger.info("row clicked pid=%d cwd=%s", session.pid, session.cwd)

        container = self._container_cache.get(session.pid)
        if not container:
            container = detect_container(session.pid)
            container = find_window_for_session(session.cwd, container)
            self._container_cache[session.pid] = container

        if container.window_handle:
            success = foreground_window(container)
            if not success:
                logger.warning(
                    "failed to foreground window pid=%d hwnd=%d",
                    session.pid,
                    container.window_handle,
                )
        else:
            logger.debug("no window handle for session pid=%d", session.pid)

    def _show_window(self):
        """Show the dashboard window (from tray menu)."""
        self._main_window.show()

    def _open_settings(self):
        """Open the settings editor dialog."""
        SettingsWindow(
            self._main_window.toplevel,
            self._settings,
            on_save=self._on_settings_save,
        )

    def _on_settings_save(self, new_settings: Settings):
        """Apply new settings from the settings editor."""
        self._settings = new_settings
        save_settings(self._settings)
        logger.info("settings saved")

    def _quit(self):
        """Quit the application."""
        self._save_window_position()
        save_settings(self._settings)
        if self._tray_icon:
            self._tray_icon.stop()
        self._root.quit()

    def _on_position_save(self, x: int, y: int):
        """Callback when window position changes (close/hide)."""
        self._settings.window_x = x
        self._settings.window_y = y

    def _save_window_position(self):
        """Save the dashboard window position to settings."""
        x, y = self._main_window.get_position()
        if x is not None and y is not None:
            self._settings.window_x = x
            self._settings.window_y = y
