# Generated By: Claude Code (Claude Opus 4.6)
"""Main application controller — session discovery + hook-based state detection."""

import json
import logging
import os
import sys
from pathlib import Path
import threading
import tempfile
import tkinter as tk
from typing import Callable

from claude_dashboard import config
from claude_dashboard.hook_server import HookServer
from claude_dashboard.platform.base import (
    ContainerInfo,
    detect_container,
    find_window_for_session,
    foreground_window,
)
from claude_dashboard.session import (
    SessionInfo,
    cwd_basename,
    cwd_relative_to_home,
    detect_branch,
    discover_sessions,
    validate_pid,
)
from claude_dashboard.settings import Settings, load_settings, save_settings
from claude_dashboard.startup import set_run_on_startup
from claude_dashboard.config import StatusState
from claude_dashboard.models import SessionRow
from claude_dashboard.tray import create_tray_icon, update_tray_icon
from claude_dashboard.ui.main_window import MainWindow
from claude_dashboard.ui.settings_window import SettingsWindow

logger = logging.getLogger(__name__)

_STATE_PRIORITY = {
    StatusState.PERMISSION_REQUIRED: 0,
    StatusState.AWAITING_INPUT: 1,
    StatusState.WORKING: 2,
    StatusState.READY: 3,
    StatusState.IDLE: 4,
}

# States where the user can take an action (approve, answer, navigate, etc.)
_ACTIONABLE_STATES = frozenset(
    {
        StatusState.PERMISSION_REQUIRED,
        StatusState.AWAITING_INPUT,
        StatusState.READY,
        StatusState.IDLE,
    }
)

_DEBOUNCE_MS = 300  # Debounce window for state display updates (FR-043)


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert '#rrggbb' hex string to (r, g, b) tuple."""
    h = hex_color.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


class _AgentEntry:
    """Tracks an agent within a session."""

    __slots__ = ("agent_id", "state", "agent_type")

    def __init__(self, *, agent_id: str, state: StatusState, agent_type: str = ""):
        self.agent_id = agent_id
        self.state = state
        self.agent_type = agent_type


def build_restart_args() -> list[str]:
    """Build execv args for restarting the dashboard.

    Always uses ``-m claude_dashboard`` to avoid adding the package directory
    to sys.path (which would shadow stdlib ``platform`` with
    ``claude_dashboard/platform``).
    """
    return [sys.executable, "-m", "claude_dashboard"] + sys.argv[1:]


class _SessionEntry:
    """Tracks a live session: its info, container, and current state."""

    __slots__ = (
        "session",
        "container",
        "state",
        "hidden",
        "branch",
        "flagged",
        "agents",
        "unattached",
    )

    def __init__(self, session: SessionInfo):
        self.session = session
        self.container: ContainerInfo | None = None
        self.state: StatusState = StatusState.IDLE
        self.hidden: bool = False
        self.branch: str = ""
        self.flagged: bool = False
        self.agents: dict[str, _AgentEntry] = {}
        self.unattached: bool = False

    @property
    def effective_state(self) -> StatusState:
        """Highest-priority state across main process + all agents."""
        best = self.state
        best_p = _STATE_PRIORITY.get(best, 999)
        for agent in self.agents.values():
            p = _STATE_PRIORITY.get(agent.state, 999)
            if p < best_p:
                best = agent.state
                best_p = p
        return best


class AppController:
    """Central controller — discovers sessions, receives hook events, updates UI."""

    def __init__(self, *, debug: bool = False, quiet: bool = False, ttl_seconds: int = 0):
        self._debug = debug
        self._quiet = quiet
        self._ttl_seconds = ttl_seconds
        self._settings = load_settings()

        self._root = tk.Tk()
        self._root.withdraw()

        self._main_window = MainWindow(
            self._root,
            self._settings,
            on_row_click=self._on_row_click,
            on_row_double_click=self._on_row_double_click,
            on_row_middle_click=self._on_row_middle_click,
            on_position_save=self._on_position_save,
            on_right_click=self._on_right_click,
        )

        # PID -> _SessionEntry
        self._sessions: dict[int, _SessionEntry] = {}
        # session_id -> PID (reverse lookup for hook events)
        self._session_id_to_pid: dict[str, int] = {}
        # Buffer for hook events arriving before session discovery
        self._pending_hook_states: dict[str, StatusState] = {}
        self._first_tick_done = False

        # Debounce state (FR-043)
        self._debounce_id: str | None = None

        # Hook server
        self._hook_server = HookServer(
            on_hook_event=self._on_hook_event,
            on_session_end=self._on_hook_session_end,
            on_agent_stop=self._on_hook_agent_stop,
            port=config.HOOK_PORT,
        )

        # Sync OS auto-start with settings
        set_run_on_startup(self._settings.run_on_startup)

        # Tray
        self._tray_icon = create_tray_icon(
            on_toggle=lambda icon, item: self._root.after(0, self._toggle_window),
            on_settings=lambda icon, item: self._root.after(0, self._open_settings),
            on_restart=lambda icon, item: self._root.after(0, self._restart),
            on_quit=lambda icon, item: self._root.after(0, self._quit),
            get_hidden_sessions=self._get_hidden_sessions,
        )
        self._tray_state: StatusState | None = None

        # Session visibility menu (rebuilt dynamically in _on_right_click)
        self._context_menu = tk.Menu(self._root, tearoff=0)
        self._context_menu_open = False
        self._context_menu.bind("<Unmap>", lambda e: setattr(self, "_context_menu_open", False))
        self._session_vars: list[tk.BooleanVar] = []

        # Load saved session state for restart continuity
        self._saved_state = self._load_session_state()

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------

    def run(self):
        logger.info("Claude Dashboard starting")

        # Start hook server
        self._hook_server.start()

        # Start tray
        def _run_tray():
            try:
                logger.debug("tray thread starting")
                self._tray_icon.run()
                logger.warning("tray thread exited (run() returned)")
            except Exception:
                logger.exception("tray icon crashed")

        tray_thread = threading.Thread(target=_run_tray, daemon=True)
        tray_thread.start()

        if self._ttl_seconds > 0:
            self._root.after(self._ttl_seconds * 1000, self._quit)

        # Session discovery tick
        self._discovery_tick()

        try:
            self._root.mainloop()
        except KeyboardInterrupt:
            logger.info("KeyboardInterrupt received")
        finally:
            self._hook_server.stop()
            if self._tray_icon:
                try:
                    self._tray_icon.stop()
                except Exception:
                    pass
        logger.info("Claude Dashboard stopped")

    def _discovery_tick(self):
        """Discover new sessions and remove dead ones."""
        try:
            discovered = discover_sessions()
            alive_pids = set()

            for session in discovered:
                if not validate_pid(session.pid):
                    continue
                session.pid_alive = True
                alive_pids.add(session.pid)

                if session.pid not in self._sessions:
                    self._add_session(session)
                else:
                    self._sessions[session.pid].branch = detect_branch(session.cwd)

            # Remove dead sessions (but not unattached placeholders)
            dead_pids = set(self._sessions.keys()) - alive_pids
            for pid in dead_pids:
                entry = self._sessions.get(pid)
                if entry and not entry.unattached:
                    self._remove_session(pid)

            # On first tick, create unattached placeholders from state file
            if not self._first_tick_done:
                self._create_unattached_from_state(alive_pids)

            # Refresh UI (state may not have changed, but rows may have been added/removed)
            self._refresh_ui()
            self._first_tick_done = True

        except Exception as exc:
            logger.error("discovery tick failed error=%s", exc)

        tick_ms = self._settings.poll_interval_seconds * 1000
        self._root.after(tick_ms, self._discovery_tick)

    # ------------------------------------------------------------------
    # Session lifecycle
    # ------------------------------------------------------------------

    def _add_session(self, session: SessionInfo):
        entry = _SessionEntry(session)
        # All new sessions start as IDLE until a hook event updates them.
        entry.container = detect_container(session.pid)
        entry.container = find_window_for_session(session.cwd, entry.container)
        entry.branch = detect_branch(session.cwd)

        # Replace unattached placeholder if one exists for this CWD
        unattached_pid = self._find_unattached_pid(session.cwd)
        if unattached_pid is not None:
            old = self._sessions.pop(unattached_pid, None)
            if old:
                entry.flagged = old.flagged
                logger.debug(
                    "pid=%d replaced unattached placeholder for %s", session.pid, session.cwd
                )
        else:
            self._apply_saved_state(entry)

        self._sessions[session.pid] = entry
        self._session_id_to_pid[session.session_id] = session.pid

        # Replay any buffered hook state (overrides saved state)
        buffered = self._pending_hook_states.pop(session.session_id, None)
        if buffered is not None:
            entry.state = buffered

        cwd_short = cwd_basename(session.cwd)
        logger.debug(
            "pid=%d project=%s new_state=%s prior_state=None",
            session.pid,
            cwd_short,
            entry.state.value,
        )

    def _find_unattached_pid(self, cwd: str) -> int | None:
        """Find an unattached placeholder PID for the given CWD."""
        for pid, entry in self._sessions.items():
            if entry.unattached and entry.session.cwd == cwd:
                return pid
        return None

    def _create_unattached_from_state(self, alive_pids: set[int]):
        """Create ghost entries from state file for CWDs without live sessions."""
        live_cwds = {e.session.cwd for e in self._sessions.values()}
        for cwd, saved in self._saved_state.items():
            if cwd in live_cwds:
                continue
            # Synthetic negative PID from CWD hash
            synthetic_pid = -(abs(hash(cwd)) % 1_000_000_000)
            session = SessionInfo(
                pid=synthetic_pid,
                session_id=f"unattached-{synthetic_pid}",
                cwd=cwd,
                started_at=0,
                pid_alive=False,
            )
            entry = _SessionEntry(session)
            entry.unattached = True
            if saved.get("flagged"):
                entry.flagged = True
            self._sessions[synthetic_pid] = entry
            logger.debug("created unattached placeholder for %s pid=%d", cwd, synthetic_pid)

    def _remove_session(self, pid: int):
        entry = self._sessions.pop(pid, None)
        if entry:
            self._session_id_to_pid.pop(entry.session.session_id, None)
            logger.debug("session gone pid=%d", pid)

    # ------------------------------------------------------------------
    # Hook event callback (fired from HTTP server thread)
    # ------------------------------------------------------------------

    def _on_hook_event(
        self,
        session_id: str,
        event: str,
        new_state: StatusState,
        cwd: str = "",
        agent_id: str = "",
        agent_type: str = "",
    ) -> None:
        """Called from hook server thread. Marshal to main thread."""
        self._root.after(
            0,
            self._apply_hook_state,
            session_id,
            event,
            new_state,
            cwd,
            agent_id,
            agent_type,
        )

    def _on_hook_session_end(self, session_id: str):
        """Called from hook server thread on SessionEnd."""
        self._root.after(0, self._handle_session_end, session_id)

    def _on_hook_agent_stop(self, session_id: str, agent_id: str):
        """Called from hook server thread on SubagentStop."""
        self._root.after(0, self._handle_agent_stop, session_id, agent_id)

    def _apply_hook_state(
        self,
        session_id: str,
        event: str,
        new_state: StatusState,
        cwd: str = "",
        agent_id: str = "",
        agent_type: str = "",
    ):
        """Apply a hook-driven state change on the main thread."""
        pid = self._session_id_to_pid.get(session_id)

        # Fallback: match by CWD if session_id not found (resumed sessions
        # may have a different session_id than what's in sessions/*.json)
        if pid is None and cwd:
            for candidate in self._sessions.values():
                if candidate.session.cwd == cwd:
                    pid = candidate.session.pid
                    # Register this session_id for future lookups
                    self._session_id_to_pid[session_id] = pid
                    break

        if pid is None:
            # Buffer — session not yet discovered
            self._pending_hook_states[session_id] = new_state
            return

        entry = self._sessions.get(pid)
        if not entry:
            return

        if agent_id:
            # Agent event — register or update agent
            agent = entry.agents.get(agent_id)
            if agent is None:
                agent = _AgentEntry(
                    agent_id=agent_id,
                    state=new_state,
                    agent_type=agent_type,
                )
                entry.agents[agent_id] = agent
                logger.debug(
                    "pid=%d agent=%s registered state=%s",
                    pid,
                    agent_id[:12],
                    new_state.value,
                )
            else:
                agent.state = new_state
            self._refresh_ui()
            return

        # Main process event
        # Note: we do NOT clear agents on UserPromptSubmit because auto-wake
        # events (fired after each SubagentStop) are indistinguishable from
        # real user prompts and would prematurely clear active agents.
        # Agents are removed individually via SubagentStop or on PID death.

        prior = entry.state

        # Intercept idle: transition to ready instead (cleared by row click)
        if new_state == StatusState.IDLE:
            new_state = StatusState.READY

        if prior == new_state:
            return

        entry.state = new_state
        entry.branch = detect_branch(entry.session.cwd)
        cwd_short = cwd_basename(entry.session.cwd)
        logger.debug(
            "pid=%d project=%s new_state=%s prior_state=%s event=%s",
            pid,
            cwd_short,
            new_state.value,
            prior.value,
            event,
        )
        self._refresh_ui()

    def _handle_agent_stop(self, session_id: str, agent_id: str):
        """Remove an agent from a session."""
        pid = self._session_id_to_pid.get(session_id)
        if pid is None:
            return
        entry = self._sessions.get(pid)
        if not entry:
            return
        removed = entry.agents.pop(agent_id, None)
        if removed:
            logger.debug(
                "pid=%d agent=%s removed, %d agents remain",
                pid,
                agent_id[:12],
                len(entry.agents),
            )
            self._refresh_ui()

    def _handle_session_end(self, session_id: str):
        """Handle SessionEnd hook — remove the session."""
        pid = self._session_id_to_pid.get(session_id)
        if pid is not None:
            self._remove_session(pid)
            self._refresh_ui()

    # ------------------------------------------------------------------
    # UI refresh
    # ------------------------------------------------------------------

    def _sorted_entries(self) -> list["_SessionEntry"]:
        """Return all session entries sorted by display name."""
        return sorted(
            self._sessions.values(),
            key=lambda e: cwd_relative_to_home(e.session.cwd).lower(),
        )

    def _refresh_ui(self):
        """Debounced UI refresh. High-priority states bypass debounce (FR-043)."""
        all_entries = self._sorted_entries()
        bypass = any(
            entry.effective_state in (StatusState.PERMISSION_REQUIRED, StatusState.AWAITING_INPUT)
            for entry in all_entries
            if not entry.hidden
        )

        if bypass:
            if self._debounce_id is not None:
                self._root.after_cancel(self._debounce_id)
                self._debounce_id = None
            self._do_refresh_ui(all_entries)
        else:
            if self._debounce_id is not None:
                self._root.after_cancel(self._debounce_id)
            # Capture entries now — don't re-read at execution time (race condition)
            self._debounce_id = self._root.after(
                _DEBOUNCE_MS,
                self._do_refresh_ui_deferred,
                all_entries,
            )

    def _do_refresh_ui_deferred(self, all_entries: list["_SessionEntry"]):
        """Called by debounce timer with pre-captured entries."""
        self._debounce_id = None
        self._do_refresh_ui(all_entries)

    def _do_refresh_ui(self, all_entries: list["_SessionEntry"]):
        """Actual UI refresh logic."""
        visible_states = [
            SessionRow(
                session=entry.session,
                state=entry.effective_state,
                container=entry.container,
                branch=entry.branch,
                flagged=entry.flagged,
                agent_count=len(entry.agents),
                unattached=entry.unattached,
            )
            for entry in all_entries
            if not entry.hidden
        ]
        self._main_window.update_sessions(visible_states)

        highest = self._highest_priority_state(visible_states)
        if highest != self._tray_state:
            self._tray_state = highest
            update_tray_icon(self._tray_icon, color=self._tray_color_for_state(highest))

        self._save_session_state()

    # ------------------------------------------------------------------
    # Row click
    # ------------------------------------------------------------------

    def _on_row_click(self, session: SessionInfo):
        logger.info("row clicked pid=%d cwd=%s", session.pid, session.cwd)
        entry = self._sessions.get(session.pid)

        # Click unattached session to dismiss it
        if entry and entry.unattached:
            self._sessions.pop(session.pid, None)
            logger.info("pid=%d unattached placeholder cleared", session.pid)
            self._refresh_ui()
            return

        container = entry.container if entry else None

        # Clicking a Ready session clears to Idle
        if entry and entry.state == StatusState.READY:
            entry.state = StatusState.IDLE
            logger.debug("pid=%d clicked, cleared ready to idle", session.pid)
            self._refresh_ui()

        if not container:
            container = detect_container(session.pid)
            container = find_window_for_session(session.cwd, container)
            if entry:
                entry.container = container

        if container and (container.window_handle or container.process_pid):
            success = foreground_window(container, cwd=session.cwd)
            if not success:
                logger.warning("failed to foreground pid=%d", session.pid)

    def _on_row_double_click(self, session: SessionInfo):
        """Double-click toggles between Idle and Ready."""
        entry = self._sessions.get(session.pid)
        if entry and entry.state == StatusState.READY:
            entry.state = StatusState.IDLE
            logger.debug("pid=%d double-clicked while ready, now idle", session.pid)
            self._refresh_ui()
        elif entry and entry.state == StatusState.IDLE:
            entry.state = StatusState.READY
            logger.debug("pid=%d double-clicked while idle, now ready", session.pid)
            self._refresh_ui()

    def _on_row_middle_click(self, session: SessionInfo):
        """Middle-click toggles flagged state."""
        entry = self._sessions.get(session.pid)
        if entry:
            entry.flagged = not entry.flagged
            logger.debug("pid=%d flagged=%s", session.pid, entry.flagged)
            self._refresh_ui()

    def _clear_agents(self, session: SessionInfo):
        """Clear all agents from a session (manual reset for stale agent state)."""
        entry = self._sessions.get(session.pid)
        if entry and entry.agents:
            entry.agents.clear()
            logger.info("pid=%d agents cleared", session.pid)
            self._refresh_ui()

    # ------------------------------------------------------------------
    # Session visibility menu
    # ------------------------------------------------------------------

    def _on_right_click(self, x: int, y: int):
        # Toggle: if menu is visible, just close it
        if self._context_menu_open:
            self._context_menu.unpost()
            self._context_menu_open = False
            return
        self._context_menu.unpost()
        self._context_menu.delete(0, tk.END)
        self._session_vars.clear()

        # Header (clicking dismisses menu)
        self._context_menu.add_command(
            label="Show / Hide Sessions", command=self._context_menu.unpost
        )
        self._context_menu.add_separator()

        all_entries = self._sorted_entries()
        for entry in all_entries:
            var = tk.BooleanVar(value=not entry.hidden)
            self._session_vars.append(var)
            display_name = cwd_relative_to_home(entry.session.cwd)

            def make_toggle(e=entry, v=var):
                def toggle():
                    e.hidden = not v.get()
                    self._refresh_ui()

                return toggle

            self._context_menu.add_checkbutton(
                label=display_name,
                variable=var,
                command=make_toggle(),
            )

        self._context_menu_open = True
        self._context_menu.tk_popup(x, y)

    # ------------------------------------------------------------------
    # Tray hidden sessions
    # ------------------------------------------------------------------

    def _unhide_session(self, pid: int):
        entry = self._sessions.get(pid)
        if entry:
            entry.hidden = False
            logger.info("pid=%d unhidden via tray menu", pid)
            self._root.after(0, self._refresh_ui)

    def _get_hidden_sessions(self) -> list[tuple[str, Callable]]:
        """Return (display_name, unhide_callback) for each hidden session."""
        result = []
        for entry in list(self._sessions.values()):
            if entry.hidden:
                name = cwd_relative_to_home(entry.session.cwd)

                def unhide(icon, item, p=entry.session.pid):
                    self._unhide_session(p)

                result.append((name, unhide))
        return result

    # ------------------------------------------------------------------
    # Session state persistence (restart continuity)
    # ------------------------------------------------------------------

    def _load_session_state(self) -> dict[str, dict]:
        """Load saved session state keyed by CWD."""
        try:
            data = json.loads(config.STATE_FILE.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                return data
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            pass
        return {}

    def _save_session_state(self):
        """Snapshot mutable session state to disk."""
        state = {}
        for entry in self._sessions.values():
            agents = {
                aid: {"state": a.state.value, "agent_type": a.agent_type}
                for aid, a in entry.agents.items()
            }
            state[entry.session.cwd] = {
                "state": entry.state.value,
                "hidden": entry.hidden,
                "flagged": entry.flagged,
                "agents": agents,
            }
        try:
            config.STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
            data = json.dumps(state, indent=2)
            fd, tmp_path = tempfile.mkstemp(dir=str(config.STATE_FILE.parent), suffix=".tmp")
            try:
                with open(fd, "w", encoding="utf-8") as fh:
                    fh.write(data)
                    fh.write("\n")
                Path(tmp_path).replace(config.STATE_FILE)
            except BaseException:
                Path(tmp_path).unlink(missing_ok=True)
                raise
        except OSError as exc:
            logger.debug("failed to save session state error=%s", exc)

    def _apply_saved_state(self, entry: "_SessionEntry"):
        """Apply saved state from a previous run to a newly discovered session."""
        saved = self._saved_state.get(entry.session.cwd)
        if not saved:
            return
        if saved.get("flagged"):
            entry.flagged = True
        state_val = saved.get("state")
        if state_val:
            try:
                entry.state = StatusState(state_val)
            except ValueError:
                pass
        saved_agents = saved.get("agents")
        if isinstance(saved_agents, dict):
            for aid, adata in saved_agents.items():
                if not isinstance(adata, dict):
                    continue
                try:
                    agent_state = StatusState(adata["state"])
                except (KeyError, ValueError):
                    continue
                entry.agents[aid] = _AgentEntry(
                    agent_id=aid,
                    state=agent_state,
                    agent_type=adata.get("agent_type", ""),
                )

    # ------------------------------------------------------------------
    # Window management
    # ------------------------------------------------------------------

    def _toggle_window(self):
        if self._main_window.toplevel.winfo_viewable():
            self._main_window.hide()
        else:
            self._main_window.show()

    def _show_window(self):
        self._main_window.show()

    def _hide_window(self):
        self._main_window.hide()

    def _open_settings(self):
        SettingsWindow(self._root, self._settings, on_save=self._on_settings_save)

    def _on_settings_save(self, new_settings: Settings):
        self._settings = new_settings
        self._save_settings_safe()
        set_run_on_startup(new_settings.run_on_startup)
        self._main_window.apply_settings(new_settings)
        self._refresh_ui()
        logger.info("settings saved and applied")

    def _restart(self):
        """Save state, tear down, and re-exec the same process."""
        self._save_window_position()
        self._save_settings_safe()
        self._save_session_state()
        self._hook_server.stop()
        if self._tray_icon:
            self._tray_icon.stop()
        self._root.quit()
        logger.info("restarting dashboard")
        args = build_restart_args()
        try:
            os.execv(sys.executable, args)
        except OSError:
            logger.exception("failed to restart via execv")

    def _quit(self):
        self._save_window_position()
        self._save_settings_safe()
        self._hook_server.stop()
        if self._tray_icon:
            self._tray_icon.stop()
        self._root.quit()

    def _on_position_save(self, x: int, y: int):
        self._settings.window_x = x
        self._settings.window_y = y
        self._save_settings_safe()

    def _save_settings_safe(self):
        try:
            save_settings(self._settings)
        except OSError as exc:
            logger.error("failed to save settings: %s", exc)

    def _save_window_position(self):
        x, y = self._main_window.get_position()
        if x is not None and y is not None:
            self._settings.window_x = x
            self._settings.window_y = y

    # ------------------------------------------------------------------
    # Tray priority
    # ------------------------------------------------------------------

    def _highest_priority_state(
        self,
        session_states: list[SessionRow],
    ) -> StatusState | None:
        """Pick the highest-priority actionable state for the tray icon.

        Non-actionable states (e.g. Working) are skipped — the tray icon
        should only reflect states where the user can take action.
        """
        if not session_states:
            return None
        best = None
        best_priority = 999
        for row in session_states:
            if row.unattached:
                continue
            state = row.state
            if state not in _ACTIONABLE_STATES:
                continue
            p = _STATE_PRIORITY.get(state, 999)
            if p < best_priority:
                best = state
                best_priority = p
        return best

    def _tray_color_for_state(self, state: StatusState | None) -> tuple[int, int, int]:
        color_map = {
            StatusState.PERMISSION_REQUIRED: self._settings.color_permission_required,
            StatusState.AWAITING_INPUT: self._settings.color_awaiting_input,
            StatusState.READY: self._settings.color_ready,
            StatusState.WORKING: self._settings.color_working,
            StatusState.IDLE: self._settings.color_idle,
        }
        hex_color = (
            color_map.get(state, self._settings.color_idle) if state else self._settings.color_idle
        )
        return _hex_to_rgb(hex_color)
