# Generated By: Claude Code (Claude Opus 4.6)
"""HTTP server that receives Claude Code hook events for state detection."""

import json
import logging
from http.server import BaseHTTPRequestHandler, HTTPServer
from threading import Thread
from typing import Callable

from claude_dashboard.config import StatusState

logger = logging.getLogger(__name__)

# Event → state mapping
_EVENT_STATE_MAP: dict[str, StatusState] = {
    "UserPromptSubmit": StatusState.WORKING,
    "PostToolUse": StatusState.WORKING,
    "Stop": StatusState.IDLE,
}


def map_event_to_state(
    event: str,
    *,
    tool_name: str = "",
) -> StatusState | None:
    """Map a hook event name (+ optional tool name) to a StatusState."""
    if event == "PreToolUse":
        if tool_name == "AskUserQuestion":
            return StatusState.AWAITING_INPUT
        return StatusState.WORKING

    if event == "PermissionRequest":
        if tool_name == "AskUserQuestion":
            return StatusState.AWAITING_INPUT
        return StatusState.PERMISSION_REQUIRED

    return _EVENT_STATE_MAP.get(event)


class _HookHandler(BaseHTTPRequestHandler):
    """Handles POST /hook from Claude Code HTTP hooks."""

    def do_POST(self):
        logger.debug("POST received path=%s", self.path)

        if self.path != "/hook":
            self.send_response(404)
            self.end_headers()
            return

        try:
            length = int(self.headers.get("Content-Length", 0))
            raw = self.rfile.read(length) if length else b"{}"
            body = json.loads(raw)
        except (json.JSONDecodeError, ValueError) as exc:
            logger.debug("bad request error=%s", exc)
            self.send_response(400)
            self.end_headers()
            return

        session_id = body.get("session_id", "")
        event = body.get("hook_event_name", "")
        tool_name = body.get("tool_name", "")
        cwd = body.get("cwd", "")
        logger.debug(
            "hook event session_id=%s event=%s tool_name=%s",
            session_id,
            event,
            tool_name,
        )

        state = map_event_to_state(event, tool_name=tool_name)

        if state is not None and session_id:
            self.server.on_hook_event(session_id, event, state, cwd)  # type: ignore[attr-defined]

        # SessionEnd — signal removal
        if event == "SessionEnd" and session_id:
            self.server.on_session_end(session_id)  # type: ignore[attr-defined]

        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"{}")

    def log_message(self, format, *args):
        """Suppress default access logging."""
        pass


class HookServer:
    """Lightweight HTTP server for receiving Claude Code hook events."""

    def __init__(
        self,
        *,
        on_hook_event: Callable[[str, str, StatusState, str], None],
        on_session_end: Callable[[str], None],
        port: int = 17384,
    ):
        self._server = HTTPServer(("127.0.0.1", port), _HookHandler)
        self._server.on_hook_event = on_hook_event  # type: ignore[attr-defined]
        self._server.on_session_end = on_session_end  # type: ignore[attr-defined]
        self._port = self._server.server_address[1]
        self._thread: Thread | None = None

    @property
    def port(self) -> int:
        return self._port

    def start(self):
        """Start serving on a daemon thread."""
        self._thread = Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()
        logger.info("hook server listening on port=%d", self._port)

    def stop(self):
        """Shut down the server (safe to call multiple times)."""
        if self._thread and self._thread.is_alive():
            self._server.shutdown()
            logger.info("hook server stopped")
