# Generated By: Claude Code (Claude Opus 4.6)
"""Shared data types used across controller and UI layers."""

from typing import NamedTuple

from claude_dashboard.config import GitStatus, StatusState
from claude_dashboard.platform.base import ContainerInfo
from claude_dashboard.session import SessionInfo


class SessionRow(NamedTuple):
    """Data passed from controller to UI for each visible session row."""

    session: SessionInfo
    state: StatusState
    container: ContainerInfo | None
    branch: str
    flagged: bool
    git_status: GitStatus
    merged: bool
    agent_count: int
    unattached: bool
