# Generated By: Claude Code (Claude Opus 4.6)
"""Poll Prometheus for Claude Code session state derived from Loki recording rules."""

import json
import logging
import urllib.parse
import urllib.request
from typing import NamedTuple

from claude_dashboard import config
from claude_dashboard.config import StatusState

logger = logging.getLogger(__name__)

_STATE_PRIORITY = config.STATE_PRIORITY

_METRIC_TO_STATE = {
    "claude_session_permission": StatusState.PERMISSION_REQUIRED,
    "claude_session_working": StatusState.WORKING,
    "claude_session_ready": StatusState.READY,
}

_METRICS = list(_METRIC_TO_STATE.keys())

_TIMEOUT_SECONDS = 2


class SessionState(NamedTuple):
    state: StatusState
    host_name: str
    project: str
    sandbox_profile: str = ""


def poll_session_states(*, prometheus_url: str) -> dict[str, SessionState]:
    """Query Prometheus for claude_session_* recording rule metrics.

    Returns dict mapping session_id to SessionState (highest-priority state
    wins when multiple metrics are truthy for the same session).

    Metrics checked (highest priority first):
      1. claude_session_permission > 0 → PERMISSION_REQUIRED
      2. claude_session_working > 0 → WORKING
      3. claude_session_ready > 0 → READY
    """
    candidates: dict[str, SessionState] = {}

    for metric_name in _METRICS:
        state = _METRIC_TO_STATE[metric_name]
        results = _query_metric(prometheus_url=prometheus_url, metric=metric_name)
        for result in results:
            labels = result.get("metric", {})
            session_id = labels.get("session_id", "")
            if not session_id:
                continue
            value = _parse_value(result)
            if value is None or value <= 0:
                continue
            host_name = labels.get("host_name", "")
            project = labels.get("project", "")
            existing = candidates.get(session_id)
            if existing is None or _STATE_PRIORITY[state] < _STATE_PRIORITY[existing.state]:
                candidates[session_id] = SessionState(
                    state=state, host_name=host_name, project=project
                )

    profiles = _poll_sandbox_profiles(prometheus_url=prometheus_url)
    for session_id, profile in profiles.items():
        existing = candidates.get(session_id)
        if existing is not None and not existing.sandbox_profile:
            candidates[session_id] = existing._replace(sandbox_profile=profile)

    return candidates


def _poll_sandbox_profiles(*, prometheus_url: str) -> dict[str, str]:
    """Return session_id → sandbox_profile from raw OTEL metrics."""
    results = _query_metric(
        prometheus_url=prometheus_url,
        metric="max by (session_id, sandbox_profile) "
        '(claude_code_cost_usage_USD_total{sandbox_profile!=""})',
    )
    mapping: dict[str, str] = {}
    for result in results:
        labels = result.get("metric", {})
        sid = labels.get("session_id", "")
        profile = labels.get("sandbox_profile", "")
        if sid and profile:
            mapping[sid] = profile
    return mapping


def _query_metric(*, prometheus_url: str, metric: str) -> list[dict]:
    """Query a single instant metric from Prometheus."""
    url = f"{prometheus_url}/api/v1/query?query={urllib.parse.quote(metric)}"
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=_TIMEOUT_SECONDS) as resp:
            data = json.loads(resp.read())
            if data.get("status") != "success":
                logger.debug("prometheus query %s: status=%s", metric, data.get("status"))
                return []
            return data.get("data", {}).get("result", [])
    except Exception:
        logger.debug("prometheus query %s failed", metric, exc_info=True)
        return []


def _parse_value(result: dict) -> float | None:
    """Extract numeric value from a Prometheus instant query result."""
    try:
        v = float(result["value"][1])
        if v != v:  # NaN check
            return None
        return v
    except (KeyError, IndexError, TypeError, ValueError):
        return None
