# Generated By: Claude Code (Claude Opus 4.6)
"""Session discovery — read ~/.claude/sessions/*.json, validate PIDs, resolve paths."""

import json
import logging
from dataclasses import dataclass
from pathlib import Path

import psutil

from claude_dashboard import config

logger = logging.getLogger(__name__)


@dataclass
class SessionInfo:
    """A discovered Claude Code session."""

    pid: int
    session_id: str
    cwd: str
    started_at: int
    pid_alive: bool = False


def discover_sessions(*, sessions_dir: Path | None = None) -> list[SessionInfo]:
    """Read all session files from ~/.claude/sessions/ and return SessionInfo list."""
    directory = sessions_dir or config.SESSIONS_DIR

    if not directory.is_dir():
        logger.debug("sessions directory does not exist path=%s", directory)
        return []

    sessions = []
    for session_file in directory.glob("*.json"):
        try:
            data = json.loads(session_file.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                continue
            session = SessionInfo(
                pid=data.get("pid", 0),
                session_id=data.get("sessionId", ""),
                cwd=data.get("cwd", ""),
                started_at=data.get("startedAt", 0),
            )
            if session.pid and session.session_id:
                sessions.append(session)
        except (json.JSONDecodeError, OSError) as exc:
            logger.debug("failed to read session file=%s error=%s", session_file, exc)

    return sorted(sessions, key=lambda s: s.pid)


def validate_pid(pid: int) -> bool:
    """Check if a process with the given PID is alive and is a Claude process."""
    try:
        if not psutil.pid_exists(pid):
            return False
        proc = psutil.Process(pid)
        name = proc.name().lower()
        return "claude" in name
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return False


def encode_project_key(cwd: str) -> str:
    """Encode a CWD path as a Claude project key.

    Replaces path separators and colons with dashes.
    e.g., "C:\\Users\\user\\source\\my-project" -> "C--Users-user-source-my-project"
    """
    # Normalize to forward slashes first
    normalized = cwd.replace("\\", "/")
    # Replace colons (Windows drive letter)
    normalized = normalized.replace(":", "-")
    # Replace slashes with dashes
    normalized = normalized.replace("/", "-")
    # Collapse leading dash from root slash on Linux (e.g., /home -> -home)
    normalized = normalized.lstrip("-")
    return normalized


def cwd_relative_to_home(cwd: str) -> str:
    """Convert a CWD path to be relative to ~.

    e.g., "C:\\Users\\user\\source\\my-project" -> "~/source/my-project"
    """
    home = str(Path.home())
    # Normalize both to forward slashes for comparison
    cwd_normalized = cwd.replace("\\", "/")
    home_normalized = home.replace("\\", "/")

    if cwd_normalized.startswith(home_normalized):
        relative = cwd_normalized[len(home_normalized) :]
        return "~" + relative
    return cwd_normalized
