# Generated By: Claude Code (Claude Opus 4.6)
"""Session discovery — read ~/.claude/sessions/*.json, validate PIDs, resolve paths."""

import json
import logging
import os
import subprocess
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import psutil

from claude_dashboard import config
from claude_dashboard.config import GitStatus

logger = logging.getLogger(__name__)


@dataclass
class SessionInfo:
    """A discovered Claude Code session."""

    pid: int
    session_id: str
    cwd: str
    started_at: int
    pid_alive: bool = False
    entrypoint: str = "cli"
    sandbox_phase: str = ""
    sandbox_profile: str = ""


# Entrypoints written by non-interactive runs (`claude -p`, Agent SDK). They have
# no window to foreground and finish in seconds, so a row plus a ghost is noise.
# Verified against Claude Code 2.1.226: `claude -p` writes entrypoint "sdk-cli",
# the interactive TUI writes "cli". Unknown entrypoints stay visible on purpose.
HEADLESS_ENTRYPOINTS = frozenset({"sdk-cli"})


def discover_sessions(*, sessions_dir: Path | None = None) -> list[SessionInfo]:
    """Read all session files from ~/.claude/sessions/ and return SessionInfo list.

    Headless entrypoints are skipped — see HEADLESS_ENTRYPOINTS. Their OTEL
    telemetry is unaffected; Claude Code emits that independently.
    """
    directory = sessions_dir or config.SESSIONS_DIR

    if not directory.is_dir():
        logger.debug("sessions directory does not exist path=%s", directory)
        return []

    sessions = []
    for session_file in directory.glob("*.json"):
        try:
            data = json.loads(session_file.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                continue
            session = SessionInfo(
                pid=data.get("pid", 0),
                session_id=data.get("sessionId", ""),
                cwd=data.get("cwd", ""),
                started_at=data.get("startedAt", 0),
                entrypoint=data.get("entrypoint", "cli"),
            )
            if session.entrypoint in HEADLESS_ENTRYPOINTS:
                logger.debug(
                    "skipping headless session pid=%d entrypoint=%s cwd=%s",
                    session.pid,
                    session.entrypoint,
                    session.cwd,
                )
                continue
            if session.pid and session.session_id:
                sessions.append(session)
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("failed to read session file=%s error=%s", session_file, exc)

    return sorted(sessions, key=lambda s: cwd_relative_to_home(cwd=s.cwd).lower())


def validate_pid(*, pid: int) -> bool:
    """Check if a process with the given PID is alive and is a Claude process.

    On Linux, also checks dtach: if Claude is running under dtach and no client
    is attached, returns False so the session renders as a ghost.
    """
    try:
        if not psutil.pid_exists(pid):
            return False
        proc = psutil.Process(pid)
        name = proc.name().lower()
        if "claude" not in name:
            return False
        if config.IS_LINUX and not _is_dtach_attached(proc):
            return False
        return True
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return False


def _is_dtach_attached(proc: psutil.Process) -> bool:
    """Check if a Claude process under dtach has an attached client.

    Returns True if not under dtach (normal session) or if dtach has a client.
    Returns False only when Claude is under dtach and no client is connected.
    """
    try:
        parent = proc.parent()
        if not parent or parent.name() != "dtach":
            return True

        master = parent

        # Case 1: initial -c client still alive (master's parent is also dtach)
        try:
            grandparent = master.parent()
            if grandparent and grandparent.name() == "dtach":
                return True
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass

        # Case 2: reattached via -a — scan for dtach process with same socket
        try:
            master_cwd = master.cwd()
            master_cmdline = master.cmdline()
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            return False

        socket_name = _parse_dtach_socket(master_cmdline)
        if not socket_name:
            return False

        socket_abs = os.path.realpath(os.path.join(master_cwd, socket_name))

        for p in psutil.process_iter(["name", "pid"]):
            if p.info["name"] != "dtach" or p.info["pid"] == master.pid:
                continue
            try:
                cmdline = p.cmdline()
                if "-a" not in cmdline:
                    continue
                a_idx = cmdline.index("-a")
                if a_idx + 1 >= len(cmdline):
                    continue
                client_socket = cmdline[a_idx + 1]
                client_cwd = p.cwd()
                client_abs = os.path.realpath(os.path.join(client_cwd, client_socket))
                if client_abs == socket_abs:
                    return True
            except (psutil.NoSuchProcess, psutil.AccessDenied, OSError):
                continue

        return False
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return True


def _parse_dtach_socket(cmdline: list[str]) -> str:
    """Extract socket path from dtach cmdline like ['dtach', '-c', '.dtach-claude', 'claude']."""
    for i, arg in enumerate(cmdline):
        if arg == "-c" and i + 1 < len(cmdline):
            return cmdline[i + 1]
    return ""


def encode_project_key(*, cwd: str) -> str:
    """Encode a CWD path as a Claude project key.

    Replaces path separators and colons with dashes.
    e.g., "C:\\Users\\user\\source\\my-project" -> "C--Users-user-source-my-project"
    """
    # Normalize to forward slashes first
    normalized = cwd.replace("\\", "/")
    # Replace colons (Windows drive letter)
    normalized = normalized.replace(":", "-")
    # Replace slashes with dashes
    normalized = normalized.replace("/", "-")
    # Collapse leading dash from root slash on Linux (e.g., /home -> -home)
    normalized = normalized.lstrip("-")
    return normalized


def _resolve_git_dir(cwd: str) -> Path | None:
    """Resolve the git directory for a working tree.

    For regular repos, .git is a directory containing HEAD, config, refs, etc.
    For worktrees, .git is a file containing ``gitdir: /path/to/git/dir``.
    Returns None if *cwd* is not inside a git repo.
    """
    dot_git = Path(cwd) / ".git"
    try:
        if dot_git.is_dir():
            return dot_git
        if dot_git.is_file():
            content = dot_git.read_text(encoding="utf-8").strip()
            if content.startswith("gitdir: "):
                gitdir_path = content[len("gitdir: ") :]
                resolved = Path(gitdir_path)
                if not resolved.is_absolute():
                    resolved = (Path(cwd) / resolved).resolve()
                if resolved.is_dir():
                    return resolved
    except OSError:
        pass
    return None


def _resolve_common_dir(git_dir: Path) -> Path:
    """Resolve the common git directory (shared refs, config, packed-refs).

    For regular repos, common_dir == git_dir.
    For worktrees, ``git_dir/commondir`` contains a relative path to the
    main ``.git`` directory.
    """
    commondir_file = git_dir / "commondir"
    try:
        if commondir_file.is_file():
            rel = commondir_file.read_text(encoding="utf-8").strip()
            return (git_dir / rel).resolve()
    except OSError:
        pass
    return git_dir


def detect_branch(*, cwd: str, trunk_branch: str = "") -> str:
    """Return the active git branch for a directory, or empty string on failure.

    Reads HEAD from the resolved git directory — works for both regular repos
    and worktrees. No subprocess needed.
    Returns empty string if the branch matches trunk_branch, if HEAD is
    detached, or if the directory is not a git repo.
    """
    git_dir = _resolve_git_dir(cwd)
    if git_dir is None:
        return ""
    try:
        head_content = (git_dir / "HEAD").read_text(encoding="utf-8").strip()
        if not head_content.startswith("ref: refs/heads/"):
            return ""
        branch = head_content[len("ref: refs/heads/") :]
        if trunk_branch and branch == trunk_branch:
            return ""
        return branch
    except OSError:
        return ""


def _read_remotes(common_dir: Path) -> list[str]:
    """Parse remote names from git config via file read.

    Reads ``common_dir/config`` looking for ``[remote "name"]`` sections.
    """
    config_path = common_dir / "config"
    try:
        content = config_path.read_text(encoding="utf-8")
    except OSError:
        return []
    remotes: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith('[remote "') and stripped.endswith('"]'):
            name = stripped[len('[remote "') : -len('"]')]
            remotes.append(name)
    return remotes


def _read_symbolic_ref(common_dir: Path, ref_path: str) -> str | None:
    """Read a symbolic ref from the filesystem (loose ref then packed-refs).

    *ref_path* is e.g. ``refs/remotes/origin/HEAD``.
    Returns the target ref string if found, else None.
    """
    loose = common_dir / ref_path
    try:
        content = loose.read_text(encoding="utf-8").strip()
        if content.startswith("ref: "):
            return content[len("ref: ") :]
        return None
    except OSError:
        pass
    packed = common_dir / "packed-refs"
    try:
        for line in packed.read_text(encoding="utf-8").splitlines():
            if line.startswith("#") or line.startswith("^"):
                continue
            parts = line.split()
            if len(parts) >= 2 and parts[1] == ref_path:
                return None
    except OSError:
        pass
    return None


def _read_upstream(common_dir: Path) -> tuple[str, str]:
    """Detect upstream remote and trunk ref via file reads only.

    Returns ``(remote, trunk_ref)`` e.g. ``("origin", "origin/main")``.
    """
    for remote in _read_remotes(common_dir):
        ref_path = f"refs/remotes/{remote}/HEAD"
        target = _read_symbolic_ref(common_dir, ref_path)
        if target and target.startswith("refs/remotes/"):
            return (remote, target[len("refs/remotes/") :])
    return ("", "")


def read_trunk_info(*, cwd: str) -> tuple[str, str, str]:
    """Read trunk remote, ref, and branch name via file reads only.

    Returns ``(remote, trunk_ref, trunk_branch)``
    e.g. ``("origin", "origin/main", "main")``.
    """
    git_dir = _resolve_git_dir(cwd)
    if git_dir is None:
        return ("", "", "")
    common_dir = _resolve_common_dir(git_dir)
    remote, trunk_ref = _read_upstream(common_dir)
    trunk_branch = trunk_ref.split("/", 1)[-1] if trunk_ref else ""
    return (remote, trunk_ref, trunk_branch)


def _git_output(*, args: list[str], cwd: str) -> str | None:
    """Run a git command and return stdout, or None on failure/timeout."""
    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=2,
            creationflags=config.SUBPROCESS_FLAGS,
        )
        if result.returncode == 0:
            return result.stdout
    except (OSError, subprocess.TimeoutExpired):
        pass
    return None


def _parse_porcelain(porcelain: str) -> tuple[bool, bool]:
    """Parse git status --porcelain output into (has_unstaged, has_staged)."""
    has_unstaged = False
    has_staged = False
    for line in porcelain.splitlines():
        if len(line) < 2 or line.startswith("??"):
            continue
        if line[1] != " ":
            has_unstaged = True
        if line[0] != " ":
            has_staged = True
    return has_unstaged, has_staged


def git_check(*, cwd: str, trunk_ref: str = "", branch: str = "") -> tuple[GitStatus, bool]:
    """Git status and merge check via subprocess.

    Upstream/trunk resolution is done by the caller via file reads —
    this function only runs the git plumbing that *requires* a
    subprocess (status, log, merge-base, cherry, diff).

    Returns ``(git_status, is_merged)``.
    """
    if _resolve_git_dir(cwd) is None:
        return (GitStatus.CLEAN, False)

    deadline = time.monotonic() + 4.0

    def _run(args: list[str]) -> subprocess.CompletedProcess[str] | None:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return None
        try:
            return subprocess.run(
                args,
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=min(remaining, 2),
                creationflags=config.SUBPROCESS_FLAGS,
            )
        except (OSError, subprocess.TimeoutExpired):
            return None

    # 1. git status --porcelain
    result = _run(["git", "status", "--porcelain"])
    if result is None or result.returncode != 0:
        return (GitStatus.CLEAN, False)

    has_unstaged, has_staged = _parse_porcelain(result.stdout)
    if has_unstaged:
        return (GitStatus.UNSTAGED_CHANGES, False)
    if has_staged:
        return (GitStatus.STAGED_UNCOMMITTED, False)

    # 2. Check commits ahead of upstream tracking branch
    git_status = GitStatus.CLEAN
    result = _run(["git", "log", "--oneline", "@{u}..HEAD"])
    if result is not None and result.returncode == 0:
        if result.stdout.strip():
            git_status = GitStatus.COMMITTED_NOT_PUSHED
    elif branch and trunk_ref:
        result = _run(["git", "log", "--oneline", f"{trunk_ref}..HEAD"])
        if result is not None and result.returncode == 0 and result.stdout.strip():
            git_status = GitStatus.COMMITTED_NOT_PUSHED

    if git_status == GitStatus.CLEAN and branch:
        git_status = GitStatus.PUSHED_NOT_MERGED

    # 3. Merge detection (only when there is a branch to check)
    is_merged = False
    if branch and trunk_ref:
        # Strategy 1: regular merge (branch is ancestor of trunk)
        result = _run(["git", "merge-base", "--is-ancestor", branch, trunk_ref])
        if result is not None and result.returncode == 0:
            is_merged = True

        # Strategy 2: rebase merge (all commits have patch-equivalent)
        if not is_merged:
            result = _run(["git", "cherry", trunk_ref, branch])
            if result is not None and result.returncode == 0:
                unmerged = sum(1 for line in result.stdout.splitlines() if line.startswith("+"))
                if unmerged == 0:
                    is_merged = True

        # Strategy 3: squash merge (trees identical)
        if not is_merged:
            result = _run(["git", "diff", "--quiet", trunk_ref, branch, "--"])
            if result is not None and result.returncode == 0:
                is_merged = True

    return (git_status, is_merged)


def cwd_basename(*, cwd: str) -> str:
    """Extract the last path component from a CWD, handling both / and \\ separators."""
    return cwd.rsplit("\\", 1)[-1].rsplit("/", 1)[-1]


def cwd_relative_to_home(*, cwd: str) -> str:
    """Convert a CWD path to be relative to ~.

    e.g., "C:\\Users\\user\\source\\my-project" -> "~/source/my-project"
    """
    home = str(Path.home())
    # Normalize both to forward slashes for comparison
    cwd_normalized = cwd.replace("\\", "/")
    home_normalized = home.replace("\\", "/")

    if cwd_normalized.startswith(home_normalized):
        relative = cwd_normalized[len(home_normalized) :]
        return "~" + relative
    return cwd_normalized


_GIT_STATUS_PRIORITY = {
    GitStatus.UNSTAGED_CHANGES: 0,
    GitStatus.STAGED_UNCOMMITTED: 1,
    GitStatus.COMMITTED_NOT_PUSHED: 2,
    GitStatus.PUSHED_NOT_MERGED: 3,
    GitStatus.CLEAN: 4,
}

SANDBOXES_DIR = Path.home() / "sandboxes"


def read_sandbox_repos(*, sandbox_dir: str) -> list[str]:
    """Read manifest.json and return paths to repo subdirs that exist."""
    manifest = Path(sandbox_dir) / "manifest.json"
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return []
    repos = data.get("repos")
    if not isinstance(repos, dict):
        return []
    result = []
    for repo_name in repos:
        repo_dir = Path(sandbox_dir) / repo_name
        if repo_dir.is_dir():
            result.append(str(repo_dir))
    return result


def sandbox_git_check(*, sandbox_dir: str) -> tuple[GitStatus, bool, str]:
    """Aggregate git status across all repos in a sandbox.

    Returns ``(highest_priority_status, any_merged, first_non_trunk_branch)``.
    """
    repos = read_sandbox_repos(sandbox_dir=sandbox_dir)
    if not repos:
        return (GitStatus.CLEAN, False, "")

    best_status = GitStatus.CLEAN
    best_priority = _GIT_STATUS_PRIORITY[GitStatus.CLEAN]
    any_merged = False
    first_branch = ""

    for repo_path in repos:
        remote, trunk_ref, trunk_branch = read_trunk_info(cwd=repo_path)
        branch = detect_branch(cwd=repo_path, trunk_branch=trunk_branch)
        status, merged = git_check(cwd=repo_path, trunk_ref=trunk_ref, branch=branch)

        priority = _GIT_STATUS_PRIORITY.get(status, 4)
        if priority < best_priority:
            best_status = status
            best_priority = priority
        if merged:
            any_merged = True
        if branch and not first_branch:
            first_branch = branch

    return (best_status, any_merged, first_branch)


def _read_sandbox_profile(sandbox_dir: Path) -> str:
    """Read profile from manifest.json in a sandbox directory."""
    try:
        data = json.loads((sandbox_dir / "manifest.json").read_text(encoding="utf-8"))
        return data.get("profile", "")
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return ""


def _scan_sandbox_manifests() -> dict[str, Path]:
    """Scan manifest.json files to map openshell names to host directories."""
    mapping: dict[str, Path] = {}
    for manifest in SANDBOXES_DIR.glob("*/manifest.json"):
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
            os_name = data.get("openshell_name", "")
            if os_name:
                mapping[os_name] = manifest.parent
        except (json.JSONDecodeError, OSError):
            continue
    return mapping


def discover_sandbox_sessions() -> list[SessionInfo]:
    """Discover Claude sessions running in OpenShell sandboxes.

    Runs ``openshell sandbox list --output json``, filters to Ready phase,
    and returns a SessionInfo per sandbox whose host directory exists.
    Returns an empty list if ``openshell`` is not installed or fails.
    """
    try:
        result = subprocess.run(
            ["openshell", "sandbox", "list", "--output", "json"],
            capture_output=True,
            text=True,
            timeout=5,
            creationflags=config.SUBPROCESS_FLAGS,
        )
        if result.returncode != 0:
            logger.info(
                "openshell sandbox list failed rc=%d stderr=%s",
                result.returncode,
                result.stderr[:200],
            )
            return []
    except FileNotFoundError:
        logger.debug("openshell not installed, skipping sandbox discovery")
        return []
    except (OSError, subprocess.TimeoutExpired) as exc:
        logger.info("openshell sandbox list error: %s", exc)
        return []

    try:
        sandboxes = json.loads(result.stdout)
    except json.JSONDecodeError:
        logger.info("openshell sandbox list returned invalid JSON: %s", result.stdout[:200])
        return []

    if not isinstance(sandboxes, list):
        return []

    sessions: list[SessionInfo] = []
    manifest_map = _scan_sandbox_manifests()

    for sb in sandboxes:
        if not isinstance(sb, dict):
            continue
        phase = sb.get("phase", "Unknown")
        name = sb.get("name", "")
        if not name or phase == "Deleting":
            continue

        sandbox_dir: Path | None = None

        # Strategy 1: label from openshell (new sandboxes with --label)
        labels = sb.get("labels") or {}
        source_dir = labels.get("source.directory", "")
        if source_dir:
            candidate = SANDBOXES_DIR / source_dir
            if candidate.is_dir():
                sandbox_dir = candidate

        # Strategy 2: direct name match (old full-name sandboxes)
        if sandbox_dir is None:
            candidate = SANDBOXES_DIR / name
            if candidate.is_dir():
                sandbox_dir = candidate

        # Strategy 3: manifest lookup (hash-name sandboxes)
        if sandbox_dir is None and name in manifest_map:
            sandbox_dir = manifest_map[name]

        if sandbox_dir is None:
            logger.info("sandbox %s skipped: no matching directory found", name)
            continue

        started_at = 0
        created_at = sb.get("created_at", "")
        if created_at:
            try:
                dt = datetime.strptime(created_at, "%Y-%m-%d %H:%M:%S")
                dt = dt.replace(tzinfo=timezone.utc)
                started_at = int(dt.timestamp() * 1000)
            except ValueError:
                pass

        profile = _read_sandbox_profile(sandbox_dir)

        sessions.append(
            SessionInfo(
                pid=0,
                session_id=f"sandbox-{name}",
                cwd=str(sandbox_dir),
                started_at=started_at,
                entrypoint="sandbox",
                sandbox_phase=phase,
                sandbox_profile=profile,
            )
        )

    if sessions:
        logger.info(
            "sandbox discovery found %d: %s",
            len(sessions),
            [s.session_id for s in sessions],
        )
    return sorted(sessions, key=lambda s: cwd_relative_to_home(cwd=s.cwd).lower())


# Process names to exclude from terminal activity detection
_TERMINAL_ACTIVITY_EXCLUDE = frozenset(
    {"claude-wrapper.sh", "claude", "openshell", "node", "code", "pgrep", "ps", "grep"}
)


def detect_terminal_activity(*, session_cwds: list[str], vscode_pid: int) -> set[str]:
    """Return session CWDs that have non-Claude processes running in VS Code terminals.

    Scans /proc for bash shells parented by VS Code, checks their CWD against
    session CWDs, and reports which sessions have active non-Claude child processes.
    """
    if not config.IS_LINUX or vscode_pid <= 0:
        return set()

    active_cwds: set[str] = set()

    try:
        parent = psutil.Process(vscode_pid)
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        return set()

    for child in parent.children(recursive=True):
        try:
            if child.name() != "bash":
                continue
            cmdline_str = " ".join(child.cmdline())
            if "shellIntegration-bash" not in cmdline_str and "bash -li" not in cmdline_str:
                continue

            child_cwd = child.cwd()
            matched_cwd = _match_cwd(child_cwd, session_cwds)
            if not matched_cwd:
                continue

            for grandchild in child.children(recursive=False):
                try:
                    gc_name = grandchild.name()
                    gc_cmdline = " ".join(grandchild.cmdline())
                    if gc_name in _TERMINAL_ACTIVITY_EXCLUDE:
                        continue
                    if any(ex in gc_cmdline for ex in _TERMINAL_ACTIVITY_EXCLUDE):
                        continue
                    active_cwds.add(matched_cwd)
                    break
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    continue

        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue

    return active_cwds


def _match_cwd(terminal_cwd: str, session_cwds: list[str]) -> str | None:
    """Match a terminal CWD to a session CWD. Exact match first, prefix fallback."""
    for cwd in session_cwds:
        if terminal_cwd == cwd:
            return cwd
    for cwd in session_cwds:
        if terminal_cwd.startswith(cwd + "/"):
            return cwd
    return None
