# Generated By: Claude Code (Claude Opus 4.6)
"""Settings persistence — dataclass with atomic JSON I/O."""

import json
import logging
from dataclasses import asdict, dataclass, fields
from pathlib import Path

from claude_dashboard import config
from claude_dashboard.file_utils import atomic_write_json

logger = logging.getLogger(__name__)


@dataclass
class Settings:
    """User-configurable dashboard settings."""

    # Window position
    window_x: int | None = None
    window_y: int | None = None
    settings_x: int | None = None
    settings_y: int | None = None
    color_picker_x: int | None = None
    color_picker_y: int | None = None
    always_on_top: bool = config.DEFAULT_ALWAYS_ON_TOP
    grow_up: bool = config.DEFAULT_GROW_UP

    # Row dimensions
    row_height: int = config.DEFAULT_ROW_HEIGHT
    row_width: int = config.DEFAULT_ROW_WIDTH
    font_size: int = config.DEFAULT_FONT_SIZE

    # Poll
    poll_interval_seconds: int = config.DEFAULT_POLL_INTERVAL_SECONDS

    # OTEL state source (env var PROMETHEUS_URL overrides at runtime)
    prometheus_url: str = config.DEFAULT_PROMETHEUS_URL

    # Loki state source (env var LOKI_URL overrides at runtime)
    loki_url: str = config.DEFAULT_LOKI_URL

    # Tooltip
    tooltip_delay_ms: int = config.DEFAULT_TOOLTIP_DELAY_MS

    # Startup
    run_on_startup: bool = config.DEFAULT_RUN_ON_STARTUP

    # Status colors
    color_working: str = config.DEFAULT_COLOR_WORKING
    color_ready: str = config.DEFAULT_COLOR_READY
    color_idle: str = config.DEFAULT_COLOR_IDLE
    color_awaiting_input: str = config.DEFAULT_COLOR_AWAITING_INPUT
    color_permission_required: str = config.DEFAULT_COLOR_PERMISSION_REQUIRED
    color_flag_manual: str = config.DEFAULT_COLOR_FLAG_MANUAL
    color_flag_unstaged: str = config.DEFAULT_COLOR_FLAG_UNSTAGED
    color_flag_staged: str = config.DEFAULT_COLOR_FLAG_STAGED
    color_flag_unpushed: str = config.DEFAULT_COLOR_FLAG_UNPUSHED
    color_flag_unmerged: str = config.DEFAULT_COLOR_FLAG_UNMERGED
    color_unattached: str = config.DEFAULT_COLOR_UNATTACHED
    color_remote: str = config.DEFAULT_COLOR_REMOTE

    # Remote sessions (discovered from OTEL metrics, not local processes)
    show_remote: bool = config.DEFAULT_SHOW_REMOTE

    # General UI
    window_bg: str = config.DEFAULT_WINDOW_BG

    # Session filtering
    ignore_regex: str = config.DEFAULT_IGNORE_REGEX
    max_sessions: int = config.DEFAULT_MAX_SESSIONS


def _is_valid_value(*, value: object, default: object) -> bool:
    """Check if a JSON value is type-compatible with a Settings field default."""
    if value is None:
        return default is None
    if default is None:
        # Optional[int] — accept int but not bool
        return isinstance(value, int) and not isinstance(value, bool)
    if not isinstance(value, type(default)):
        return False
    # bool is subclass of int — reject bool for int fields
    if isinstance(default, int) and not isinstance(default, bool):
        return not isinstance(value, bool)
    return True


SETTINGS_FIELD_NAMES = {f.name for f in fields(Settings)}


def reset_position(
    settings: Settings, *, screen_width: int, screen_height: int, window_width: int
) -> None:
    """Move the window to the middle of the screen.

    Escape hatch for a window stranded off-screen. The origin is not usable
    as a recovery target: with ``grow_up`` disabled the title bar lands at
    y=0, underneath a top panel, so the window is visible but cannot be
    dragged. Mid-screen clears panels at every edge and works for both
    growth directions — ``window_y`` is a top edge when growing down and a
    bottom edge when growing up, and either way the window stays on screen.
    """
    settings.window_x = max(0, (screen_width - window_width) // 2)
    settings.window_y = screen_height // 2


def load_settings(*, path: Path | None = None) -> Settings:
    """Load settings from JSON file. Returns defaults if file missing or invalid."""
    settings_path = config.SETTINGS_FILE if path is None else path
    settings = Settings()

    if not settings_path.exists():
        logger.debug("settings file not found, using defaults path=%s", settings_path)
        return settings

    try:
        raw = json.loads(settings_path.read_text(encoding="utf-8"))

        # Filter to known fields only
        filtered = {k: v for k, v in raw.items() if k in SETTINGS_FIELD_NAMES}

        # Validate types by comparing against default value types
        for field_name in SETTINGS_FIELD_NAMES:
            if field_name not in filtered:
                continue
            value = filtered[field_name]
            default = getattr(settings, field_name)
            if not _is_valid_value(value=value, default=default):
                logger.debug("skipping invalid settings field=%s value=%r", field_name, value)
                continue
            setattr(settings, field_name, value)

    except Exception as exc:
        logger.warning("failed to read settings, using defaults error=%s", exc)

    return settings


def save_settings(settings: Settings, *, path: Path | None = None) -> None:
    """Save settings to JSON file using atomic write (temp + rename)."""
    settings_path = path or config.SETTINGS_FILE

    try:
        atomic_write_json(data=asdict(settings), path=settings_path)
    except OSError as exc:
        logger.error("failed to save settings error=%s", exc)
