# Generated By: Claude Code (Claude Opus 4.6)
"""Transcript JSONL streaming and state machine for session status detection."""

import json
import logging
import threading
from enum import Enum
from pathlib import Path
from typing import Callable

logger = logging.getLogger(__name__)


class StatusState(Enum):
    """Possible states of a Claude Code session."""

    WORKING = "working"
    IDLE = "idle"
    AWAITING_INPUT = "awaiting_input"
    PERMISSION_REQUIRED = "permission_required"
    UNKNOWN = "unknown"


def _classify_entry(entry: dict) -> StatusState | None:
    """Classify a single transcript entry into a state transition.

    Returns the new state, or None if the entry doesn't change state.
    """
    entry_type = entry.get("type")

    if entry_type == "user":
        message = entry.get("message", {})
        content = message.get("content", [])
        if not isinstance(content, list):
            return None

        # Interruption marker → IDLE
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                text = item.get("text", "")
                if "[Request interrupted by user" in text:
                    return StatusState.IDLE

        # Tool result → WORKING (Claude is processing the result)
        has_tool_result = any(
            isinstance(item, dict) and item.get("type") == "tool_result" for item in content
        )
        if has_tool_result:
            return StatusState.WORKING

        # Text prompt → WORKING (user sent input, Claude will process)
        has_text = any(isinstance(item, dict) and item.get("type") == "text" for item in content)
        if has_text:
            return StatusState.WORKING

        return None

    if entry_type == "assistant":
        message = entry.get("message", {})
        stop_reason = message.get("stop_reason", "")

        if stop_reason == "end_turn":
            return StatusState.IDLE

        if stop_reason == "tool_use":
            content = message.get("content", [])
            tool_names = set()
            if isinstance(content, list):
                for item in content:
                    if isinstance(item, dict) and item.get("type") == "tool_use":
                        name = item.get("name", "")
                        if name:
                            tool_names.add(name)

            if "AskUserQuestion" in tool_names:
                return StatusState.AWAITING_INPUT

            # tool_use → WORKING initially. The TranscriptWatcher will
            # escalate to PERMISSION_REQUIRED if no tool_result arrives
            # within the timeout (see TranscriptWatcher._update_state).
            return StatusState.WORKING

    return None


class TranscriptWatcher:
    """Streams a transcript file and maintains current session state.

    Runs on its own thread. Calls on_state_change when the state transitions.
    """

    # Seconds to wait after a tool_use before escalating to PERMISSION_REQUIRED.
    # Auto-approved tools produce a tool_result almost immediately (< 1s).
    # If no result arrives within this window, the tool is likely waiting for
    # user permission.
    _PERMISSION_ESCALATION_SECONDS = 3.0

    def __init__(
        self,
        path: Path,
        *,
        on_state_change: Callable[[StatusState], None],
        poll_interval: float = 0.5,
    ):
        self._path = path
        self._on_state_change = on_state_change
        self._poll_interval = poll_interval
        self._state = StatusState.UNKNOWN
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        self._last_tool_use_time: float | None = None  # monotonic time of last tool_use
        self._pending_tool_use = False  # True if waiting for tool_result

    @property
    def state(self) -> StatusState:
        return self._state

    def start(self):
        """Start watching the transcript file on a daemon thread."""
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        """Signal the watcher to stop and wait for the thread to finish."""
        self._stop_event.set()
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=self._poll_interval * 3)

    def _check_permission_escalation(self):
        """If a tool_use has been pending without a result for too long, escalate."""
        import time

        if (
            self._pending_tool_use
            and self._last_tool_use_time is not None
            and self._state == StatusState.WORKING
        ):
            elapsed = time.monotonic() - self._last_tool_use_time
            if elapsed >= self._PERMISSION_ESCALATION_SECONDS:
                self._update_state(StatusState.PERMISSION_REQUIRED)

    def _update_state(self, new_state: StatusState):
        if new_state != self._state:
            self._state = new_state
            self._on_state_change(new_state)

    def _process_line(self, line: str):
        import time

        line = line.strip()
        if not line:
            return
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            return

        entry_type = entry.get("type")

        # Track tool_use / tool_result for permission escalation
        if entry_type == "assistant":
            message = entry.get("message", {})
            if message.get("stop_reason") == "tool_use":
                self._pending_tool_use = True
                self._last_tool_use_time = time.monotonic()
        elif entry_type == "user":
            content = entry.get("message", {}).get("content", [])
            if isinstance(content, list):
                has_result = any(
                    isinstance(item, dict) and item.get("type") == "tool_result" for item in content
                )
                if has_result:
                    self._pending_tool_use = False
                    self._last_tool_use_time = None

        new_state = _classify_entry(entry)
        if new_state is not None:
            self._update_state(new_state)

    def _run(self):
        """Read the file from the beginning, then stream new content."""
        try:
            fh = open(self._path, "r", encoding="utf-8")
        except OSError:
            return

        try:
            # Process existing content to determine initial state (no callbacks)
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                new_state = _classify_entry(entry)
                if new_state is not None:
                    self._state = new_state
                if self._stop_event.is_set():
                    return

            # Fire one callback with the final initial state
            self._on_state_change(self._state)

            # Stream new content
            while not self._stop_event.is_set():
                line = fh.readline()
                if line.endswith("\n"):
                    self._process_line(line)
                elif not line:
                    # Check for permission escalation while idle
                    self._check_permission_escalation()
                    self._stop_event.wait(self._poll_interval)
                # else: partial line — wait for the rest on next iteration
        finally:
            fh.close()


# Keep the stateless function for tests and one-off checks
def detect_state(transcript_path: Path | None) -> StatusState:
    """Detect the current state of a session from its transcript (stateless).

    Reads the entire file and processes all entries. Use TranscriptWatcher
    for ongoing monitoring.
    """
    if transcript_path is None:
        return StatusState.UNKNOWN

    try:
        with open(transcript_path, "r", encoding="utf-8") as fh:
            state = StatusState.UNKNOWN
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                new_state = _classify_entry(entry)
                if new_state is not None:
                    state = new_state
            return state
    except OSError:
        return StatusState.UNKNOWN
