# Generated By: Claude Code (Claude Opus 4.6)
"""System tray icon using pystray with PIL-generated icon image."""

import logging
from typing import Any, Callable

from PIL import Image, ImageDraw

logger = logging.getLogger(__name__)

TRAY_ICON_SIZE = (64, 64)
TRAY_ICON_NAME = "Claude Dashboard"
_DEFAULT_COLOR = (128, 128, 128)  # Gray


def generate_icon_image(*, color: tuple[int, int, int] = _DEFAULT_COLOR) -> Image.Image:
    """Generate a PIL Image for the tray icon — off-center eye.

    An asymmetric eye shape looking slightly to the right. Solid state
    color fill, transparent background. The off-center pupil gives it
    personality — 'keeping an eye on your sessions'.
    """
    size = TRAY_ICON_SIZE[0]
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    cx, cy = size // 2, size // 2
    margin = 3

    # --- Outer eye (filled circle, nearly full icon) ---
    draw.ellipse(
        [margin, margin, size - margin, size - margin],
        fill=color,
    )

    # --- Iris/pupil (dark circle, offset right and slightly up) ---
    pupil_r = 10
    pupil_cx = cx + 6
    pupil_cy = cy - 2
    draw.ellipse(
        [pupil_cx - pupil_r, pupil_cy - pupil_r, pupil_cx + pupil_r, pupil_cy + pupil_r],
        fill=(20, 20, 20),
    )

    return image


def create_tray_icon(
    *,
    on_toggle: Callable,
    on_settings: Callable,
    on_restart: Callable,
    on_quit: Callable,
    get_hidden_sessions: Callable[[], list[tuple[str, Callable]]],
) -> Any:
    """Create and return a pystray Icon (not yet running).

    on_toggle is called on left-click to toggle dashboard visibility.
    get_hidden_sessions returns a list of (display_name, unhide_callback) tuples.
    """
    import pystray

    icon_image = generate_icon_image()

    def _build_menu():
        items: list = [
            pystray.MenuItem("Toggle", on_toggle, default=True),
        ]
        hidden = get_hidden_sessions()
        if hidden:
            items.append(pystray.Menu.SEPARATOR)
            for name, cb in hidden:
                items.append(pystray.MenuItem(f"Unhide: {name}", cb))
        items.append(pystray.Menu.SEPARATOR)
        items.append(pystray.MenuItem("Settings", on_settings))
        items.append(pystray.MenuItem("Restart", on_restart))
        items.append(pystray.MenuItem("Quit", on_quit))
        return items

    menu = pystray.Menu(lambda: _build_menu())

    icon = pystray.Icon(
        name=TRAY_ICON_NAME,
        icon=icon_image,
        title=TRAY_ICON_NAME,
        menu=menu,
    )
    return icon


def update_tray_icon(
    icon: Any,
    *,
    color: tuple[int, int, int] = _DEFAULT_COLOR,
) -> None:
    """Update the tray icon color."""
    try:
        icon.icon = generate_icon_image(color=color)
    except Exception as exc:
        logger.debug("failed to update tray icon error=%s", exc)
