# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for context menu state operations.

Tests the state mutations triggered by right-click menu actions:
live session Hide/Clear State, ghost Dismiss, and row right-click dispatch.
"""

from unittest.mock import MagicMock, patch

from claude_dashboard import config
from claude_dashboard.config import GitStatus, StatusState
from claude_dashboard.controller import _AgentEntry, _SessionEntry
from claude_dashboard.session import SessionInfo


def _make_session(
    *, pid: int = 1000, cwd: str = "/tmp/test", entrypoint: str = "cli"
) -> SessionInfo:
    return SessionInfo(pid=pid, session_id="test-sid", cwd=cwd, started_at=0, entrypoint=entrypoint)


class TestLiveContextMenuHide:
    """Test Hide action from live session context menu."""

    def test_hide_sets_hidden_true(self):
        entry = _SessionEntry(_make_session())
        assert entry.hidden is False
        entry.hidden = True
        assert entry.hidden is True

    def test_hide_preserves_state(self):
        entry = _SessionEntry(_make_session())
        entry.state = StatusState.PERMISSION_REQUIRED
        entry.hidden = True
        assert entry.state == StatusState.PERMISSION_REQUIRED

    def test_hide_preserves_agents(self):
        entry = _SessionEntry(_make_session())
        entry.agents["a1"] = _AgentEntry(agent_id="a1", state=StatusState.WORKING)
        entry.hidden = True
        assert len(entry.agents) == 1


class TestLiveContextMenuClearState:
    """Test Clear State action from live session context menu."""

    def test_clear_state_resets_to_idle(self):
        entry = _SessionEntry(_make_session())
        entry.state = StatusState.PERMISSION_REQUIRED
        entry.state = StatusState.IDLE
        entry.agents.clear()
        assert entry.state == StatusState.IDLE

    def test_clear_state_removes_all_agents(self):
        entry = _SessionEntry(_make_session())
        entry.agents["a1"] = _AgentEntry(agent_id="a1", state=StatusState.WORKING)
        entry.agents["a2"] = _AgentEntry(agent_id="a2", state=StatusState.PERMISSION_REQUIRED)
        entry.agents.clear()
        assert len(entry.agents) == 0

    def test_clear_state_effective_state_becomes_idle(self):
        entry = _SessionEntry(_make_session())
        entry.state = StatusState.WORKING
        entry.agents["a1"] = _AgentEntry(agent_id="a1", state=StatusState.PERMISSION_REQUIRED)
        assert entry.effective_state == StatusState.PERMISSION_REQUIRED
        entry.state = StatusState.IDLE
        entry.agents.clear()
        assert entry.effective_state == StatusState.IDLE

    def test_clear_state_preserves_flagged(self):
        entry = _SessionEntry(_make_session())
        entry.flagged = True
        entry.state = StatusState.PERMISSION_REQUIRED
        entry.state = StatusState.IDLE
        entry.agents.clear()
        assert entry.flagged is True

    def test_clear_state_preserves_hidden(self):
        entry = _SessionEntry(_make_session())
        entry.hidden = True
        entry.state = StatusState.PERMISSION_REQUIRED
        entry.state = StatusState.IDLE
        entry.agents.clear()
        assert entry.hidden is True


class TestGhostContextMenuDismiss:
    """Test Dismiss action from ghost context menu."""

    def test_dismiss_removes_from_sessions(self):
        sessions: dict[int, _SessionEntry] = {}
        entry = _SessionEntry(_make_session(pid=-1))
        entry.unattached = True
        sessions[-1] = entry
        sessions.pop(-1, None)
        assert -1 not in sessions

    def test_dismiss_preserves_other_sessions(self):
        sessions: dict[int, _SessionEntry] = {}
        sessions[-1] = _SessionEntry(_make_session(pid=-1))
        sessions[-1].unattached = True
        sessions[1000] = _SessionEntry(_make_session(pid=1000, cwd="/tmp/other"))
        sessions.pop(-1, None)
        assert 1000 in sessions
        assert -1 not in sessions


class TestRowRightClickDispatch:
    """Test that right-click dispatches correctly based on unattached status."""

    def test_unattached_entry_routes_to_ghost_menu(self):
        entry = _SessionEntry(_make_session())
        entry.unattached = True
        assert entry.unattached is True

    def test_attached_entry_routes_to_live_menu(self):
        entry = _SessionEntry(_make_session())
        entry.unattached = False
        assert entry.unattached is False

    def test_dispatch_checks_unattached_field(self):
        """The dispatch decision is solely based on entry.unattached."""
        ghost = _SessionEntry(_make_session(pid=-1))
        ghost.unattached = True
        live = _SessionEntry(_make_session(pid=1000))
        live.unattached = False
        # Ghost and live are distinguished only by unattached flag
        assert ghost.unattached != live.unattached


class TestAutoHideNonInteractive:
    """Test that non-CLI sessions are auto-hidden."""

    def test_cli_entrypoint_not_hidden(self):
        session = _make_session(entrypoint="cli")
        entry = _SessionEntry(session)
        assert entry.hidden is False

    def test_sdk_cli_entrypoint_auto_hidden(self):
        """Sessions with entrypoint != cli (e.g. claude -p) should be hidden."""
        session = _make_session(entrypoint="sdk-cli")
        entry = _SessionEntry(session)
        # Simulates what _add_session does
        if session.entrypoint != "cli":
            entry.hidden = True
        assert entry.hidden is True

    def test_entrypoint_defaults_to_cli(self):
        session = SessionInfo(pid=1, session_id="s", cwd="/tmp", started_at=0)
        assert session.entrypoint == "cli"

    def test_entrypoint_parsed_from_session_data(self):
        session = SessionInfo(pid=1, session_id="s", cwd="/tmp", started_at=0, entrypoint="sdk-cli")
        assert session.entrypoint == "sdk-cli"


class TestHiddenStatePersistence:
    """Test that hidden state survives restarts and ghost replacement."""

    def test_hidden_carried_from_ghost_to_live(self):
        """When a live session replaces a ghost, hidden state transfers."""
        ghost = _SessionEntry(_make_session(pid=-1))
        ghost.unattached = True
        ghost.hidden = True
        live = _SessionEntry(_make_session(pid=1000))
        live.hidden = ghost.hidden
        assert live.hidden is True

    def test_flagged_and_hidden_both_carry(self):
        ghost = _SessionEntry(_make_session(pid=-1))
        ghost.unattached = True
        ghost.flagged = True
        ghost.hidden = True
        live = _SessionEntry(_make_session(pid=1000))
        live.flagged = ghost.flagged
        live.hidden = ghost.hidden
        assert live.flagged is True
        assert live.hidden is True

    def test_hidden_restored_from_saved_state(self):
        """Simulates _apply_saved_state restoring hidden=True."""
        entry = _SessionEntry(_make_session())
        assert entry.hidden is False
        saved = {"hidden": True, "flagged": False}
        if saved.get("hidden"):
            entry.hidden = True
        assert entry.hidden is True

    def test_hidden_false_not_set(self):
        """hidden=False in saved state doesn't override."""
        entry = _SessionEntry(_make_session())
        saved = {"hidden": False}
        if saved.get("hidden"):
            entry.hidden = True
        assert entry.hidden is False


class TestOpenPrMenuVisibility:
    """Test that Open PR menu item appears only for PUSHED_NOT_MERGED status."""

    def test_open_pr_available_when_pushed_not_merged(self):
        entry = _SessionEntry(_make_session())
        entry.git_status = GitStatus.PUSHED_NOT_MERGED
        assert entry.git_status == GitStatus.PUSHED_NOT_MERGED

    def test_open_pr_not_available_when_clean(self):
        entry = _SessionEntry(_make_session())
        entry.git_status = GitStatus.CLEAN
        assert entry.git_status != GitStatus.PUSHED_NOT_MERGED

    def test_open_pr_not_available_when_unstaged(self):
        entry = _SessionEntry(_make_session())
        entry.git_status = GitStatus.UNSTAGED_CHANGES
        assert entry.git_status != GitStatus.PUSHED_NOT_MERGED

    def test_open_pr_not_available_when_committed_not_pushed(self):
        entry = _SessionEntry(_make_session())
        entry.git_status = GitStatus.COMMITTED_NOT_PUSHED
        assert entry.git_status != GitStatus.PUSHED_NOT_MERGED


class TestOpenPrAction:
    """Test the _open_pr subprocess invocation."""

    @patch("claude_dashboard.controller.subprocess.run")
    def test_open_pr_views_existing_pr(self, mock_run):
        """_open_pr opens existing PR when gh pr view succeeds."""
        from claude_dashboard.controller import AppController

        mock_run.return_value = MagicMock(returncode=0)
        session = _make_session(cwd="/tmp/my-repo")
        stub = object.__new__(AppController)
        AppController._open_pr(stub, session)
        mock_run.assert_called_once_with(
            ["gh", "pr", "view", "--web"],
            cwd="/tmp/my-repo",
            stdout=-3,
            stderr=-3,
            timeout=10,
            creationflags=config.SUBPROCESS_FLAGS,
        )

    @patch("claude_dashboard.controller.subprocess.Popen")
    @patch("claude_dashboard.controller.subprocess.run")
    def test_open_pr_falls_back_to_create(self, mock_run, mock_popen):
        """_open_pr opens create-PR page when no PR exists."""
        from claude_dashboard.controller import AppController

        mock_run.return_value = MagicMock(returncode=1)
        session = _make_session(cwd="/tmp/my-repo")
        stub = object.__new__(AppController)
        AppController._open_pr(stub, session)
        mock_popen.assert_called_once_with(
            ["gh", "pr", "create", "--web"],
            cwd="/tmp/my-repo",
            stdout=-3,
            stderr=-3,
            creationflags=config.SUBPROCESS_FLAGS,
        )

    @patch("claude_dashboard.controller.subprocess.run", side_effect=FileNotFoundError)
    def test_open_pr_handles_missing_gh(self, mock_run):
        """_open_pr does not raise when gh CLI is missing."""
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/my-repo")
        stub = object.__new__(AppController)
        AppController._open_pr(stub, session)  # should not raise

    @patch("claude_dashboard.controller.subprocess.run", side_effect=OSError("test"))
    def test_open_pr_handles_os_error(self, mock_run):
        """_open_pr does not raise on generic OSError."""
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/my-repo")
        stub = object.__new__(AppController)
        AppController._open_pr(stub, session)  # should not raise


class TestLaunchVscode:
    """Test the shared _launch_vscode subprocess wrapper."""

    @patch("claude_dashboard.controller.subprocess.Popen")
    def test_launch_vscode_calls_code_with_folder(self, mock_popen):
        from claude_dashboard.controller import AppController

        stub = object.__new__(AppController)
        AppController._launch_vscode(stub, folder="/tmp/my-project")
        mock_popen.assert_called_once_with(
            ["code", "/tmp/my-project"],
            stdout=-3,
            stderr=-3,
            creationflags=config.SUBPROCESS_FLAGS,
        )

    @patch("claude_dashboard.controller.subprocess.Popen", side_effect=FileNotFoundError)
    def test_launch_vscode_handles_missing_code(self, mock_popen):
        from claude_dashboard.controller import AppController

        stub = object.__new__(AppController)
        AppController._launch_vscode(stub, folder="/tmp/x")  # should not raise

    @patch("claude_dashboard.controller.subprocess.Popen", side_effect=OSError("fail"))
    def test_launch_vscode_handles_os_error(self, mock_popen):
        from claude_dashboard.controller import AppController

        stub = object.__new__(AppController)
        AppController._launch_vscode(stub, folder="/tmp/x")  # should not raise


class TestOpenFolderAction:
    """Test the _open_folder folder picker delegates to _open_in_vscode."""

    @patch("claude_dashboard.controller.filedialog.askdirectory", return_value="/tmp/chosen")
    def test_open_folder_delegates_to_open_in_vscode(self, mock_dialog):
        from claude_dashboard.controller import AppController

        stub = object.__new__(AppController)
        with patch.object(stub, "_open_in_vscode") as mock_open:
            stub._open_folder()
            mock_dialog.assert_called_once_with(title="Open folder in VS Code")
            mock_open.assert_called_once_with(cwd="/tmp/chosen")

    @patch("claude_dashboard.controller.filedialog.askdirectory", return_value="")
    def test_open_folder_cancelled_does_nothing(self, mock_dialog):
        from claude_dashboard.controller import AppController

        stub = object.__new__(AppController)
        with patch.object(stub, "_open_in_vscode") as mock_open:
            stub._open_folder()
            mock_open.assert_not_called()


class TestLeftClickGhost:
    """Test that left-click on ghost sessions opens in VS Code."""

    def test_ghost_left_click_opens_in_vscode(self):
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/ghost-project")
        entry = _SessionEntry(session)
        entry.unattached = True

        stub = object.__new__(AppController)
        stub._sessions = {session.pid: entry}
        with patch.object(stub, "_open_in_vscode") as mock_open:
            stub._on_row_left_click(session)
            mock_open.assert_called_once_with(cwd="/tmp/ghost-project")

    def test_live_left_click_does_not_open_vscode(self):
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/live-project")
        entry = _SessionEntry(session)
        entry.unattached = False

        stub = object.__new__(AppController)
        stub._sessions = {session.pid: entry}
        with patch.object(stub, "_open_in_vscode") as mock_open:
            stub._on_row_left_click(session)
            mock_open.assert_not_called()


class TestDoubleClickOpenPr:
    """Test that double-click opens PR when pushed-not-merged."""

    def test_double_click_pushed_not_merged_opens_pr(self):
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/pr-project")
        entry = _SessionEntry(session)
        entry.git_status = GitStatus.PUSHED_NOT_MERGED

        stub = object.__new__(AppController)
        stub._sessions = {session.pid: entry}
        with patch.object(stub, "_open_pr") as mock_pr:
            stub._on_row_double_click(session)
            mock_pr.assert_called_once_with(session)

    def test_double_click_clean_does_not_open_pr(self):
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/clean-project")
        entry = _SessionEntry(session)
        entry.git_status = GitStatus.CLEAN

        stub = object.__new__(AppController)
        stub._sessions = {session.pid: entry}
        with patch.object(stub, "_open_pr") as mock_pr:
            stub._on_row_double_click(session)
            mock_pr.assert_not_called()

    def test_double_click_unstaged_does_not_open_pr(self):
        from claude_dashboard.controller import AppController

        session = _make_session(cwd="/tmp/dirty-project")
        entry = _SessionEntry(session)
        entry.git_status = GitStatus.UNSTAGED_CHANGES

        stub = object.__new__(AppController)
        stub._sessions = {session.pid: entry}
        with patch.object(stub, "_open_pr") as mock_pr:
            stub._on_row_double_click(session)
            mock_pr.assert_not_called()


class TestGhostToggle:
    """Test middle-click ghost toggle: hide visible ghosts first, show only when all hidden."""

    def _make_controller_stub(self, sessions: dict[int, _SessionEntry]):
        from claude_dashboard.controller import AppController

        stub = object.__new__(AppController)
        stub._sessions = sessions
        stub._ghosts_hidden = False
        return stub

    def test_hides_visible_ghosts_when_any_visible(self):
        from claude_dashboard.controller import AppController

        ghost1 = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        ghost1.unattached = True
        ghost1.hidden = False
        ghost2 = _SessionEntry(_make_session(pid=-2, cwd="/tmp/g2"))
        ghost2.unattached = True
        ghost2.hidden = True

        stub = self._make_controller_stub({-1: ghost1, -2: ghost2})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle()

        assert ghost1.hidden is True
        assert ghost2.hidden is True
        assert stub._ghosts_hidden is True

    def test_flagged_ghosts_not_hidden_by_toggle(self):
        from claude_dashboard.controller import AppController

        flagged_ghost = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        flagged_ghost.unattached = True
        flagged_ghost.hidden = False
        flagged_ghost.flagged = True
        unflagged_ghost = _SessionEntry(_make_session(pid=-2, cwd="/tmp/g2"))
        unflagged_ghost.unattached = True
        unflagged_ghost.hidden = False

        stub = self._make_controller_stub({-1: flagged_ghost, -2: unflagged_ghost})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle()

        assert flagged_ghost.hidden is False
        assert unflagged_ghost.hidden is True
        assert stub._ghosts_hidden is True

    def test_show_ghosts_when_only_flagged_visible(self):
        """When only flagged ghosts are visible, toggle shows all ghosts."""
        from claude_dashboard.controller import AppController

        flagged_ghost = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        flagged_ghost.unattached = True
        flagged_ghost.hidden = False
        flagged_ghost.flagged = True
        hidden_ghost = _SessionEntry(_make_session(pid=-2, cwd="/tmp/g2"))
        hidden_ghost.unattached = True
        hidden_ghost.hidden = True

        stub = self._make_controller_stub({-1: flagged_ghost, -2: hidden_ghost})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle()

        assert flagged_ghost.hidden is False
        assert hidden_ghost.hidden is False
        assert stub._ghosts_hidden is False

    def test_shows_all_ghosts_when_none_visible(self):
        from claude_dashboard.controller import AppController

        ghost1 = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        ghost1.unattached = True
        ghost1.hidden = True
        ghost2 = _SessionEntry(_make_session(pid=-2, cwd="/tmp/g2"))
        ghost2.unattached = True
        ghost2.hidden = True

        stub = self._make_controller_stub({-1: ghost1, -2: ghost2})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle()

        assert ghost1.hidden is False
        assert ghost2.hidden is False
        assert stub._ghosts_hidden is False

    def test_force_show_unhides_all_ghosts(self):
        """force_show=True always shows ghosts regardless of current visibility."""
        from claude_dashboard.controller import AppController

        ghost1 = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        ghost1.unattached = True
        ghost1.hidden = True
        ghost2 = _SessionEntry(_make_session(pid=-2, cwd="/tmp/g2"))
        ghost2.unattached = True
        ghost2.hidden = False

        stub = self._make_controller_stub({-1: ghost1, -2: ghost2})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle(force_show=True)

        assert ghost1.hidden is False
        assert ghost2.hidden is False
        assert stub._ghosts_hidden is False

    def test_force_show_does_not_unhide_flagged(self):
        """force_show=True shows non-flagged ghosts; flagged stay as-is (already visible)."""
        from claude_dashboard.controller import AppController

        flagged_ghost = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        flagged_ghost.unattached = True
        flagged_ghost.hidden = False
        flagged_ghost.flagged = True
        hidden_ghost = _SessionEntry(_make_session(pid=-2, cwd="/tmp/g2"))
        hidden_ghost.unattached = True
        hidden_ghost.hidden = True

        stub = self._make_controller_stub({-1: flagged_ghost, -2: hidden_ghost})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle(force_show=True)

        assert flagged_ghost.hidden is False
        assert hidden_ghost.hidden is False
        assert stub._ghosts_hidden is False

    def test_does_not_affect_live_sessions(self):
        from claude_dashboard.controller import AppController

        live = _SessionEntry(_make_session(pid=1000, cwd="/tmp/live"))
        live.unattached = False
        live.hidden = False
        ghost = _SessionEntry(_make_session(pid=-1, cwd="/tmp/g1"))
        ghost.unattached = True
        ghost.hidden = False

        stub = self._make_controller_stub({1000: live, -1: ghost})
        with (
            patch.object(AppController, "_save_session_state"),
            patch.object(AppController, "_refresh_ui"),
        ):
            stub._on_ghost_toggle()

        assert live.hidden is False
        assert ghost.hidden is True
