# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for grow-up window positioning logic."""

from unittest.mock import MagicMock, patch

from claude_dashboard.settings import Settings


class TestGrowUpPositionSave:
    """Verify get_position returns bottom edge when grow_up=True."""

    def _make_window(self, *, grow_up, x=100, y=200, height=240):
        """Create a MainWindow with mocked Tk internals."""
        with patch("claude_dashboard.ui.main_window.tk"):
            from claude_dashboard.ui.main_window import MainWindow

            settings = Settings(grow_up=grow_up, window_x=x, window_y=y)
            toplevel = MagicMock()

            with patch.object(MainWindow, "__init__", lambda self, *a, **kw: None):
                win = MainWindow.__new__(MainWindow)
                win._window = toplevel
                win._settings = settings

            toplevel.winfo_x.return_value = x
            toplevel.winfo_y.return_value = y
            toplevel.winfo_height.return_value = height
            return win

    def test_grow_up_saves_bottom_edge(self):
        win = self._make_window(grow_up=True, x=100, y=200, height=240)
        x, y = win.get_position()
        assert x == 100
        assert y == 200 + 240  # bottom edge = top + height

    def test_grow_down_saves_top_left(self):
        win = self._make_window(grow_up=False, x=100, y=200, height=240)
        x, y = win.get_position()
        assert x == 100
        assert y == 200  # unchanged


class TestGrowUpRestore:
    """Verify bottom edge is anchored on first render after restore."""

    def test_restore_positions_bottom_edge(self):
        """Given saved bottom_y=1080, 7 sessions at 34px each = 238px,
        the top-left y should be 1080 - 238 = 842."""
        saved_bottom_y = 1080
        row_height = 32
        pad_y = 1
        session_count = 7
        new_height = session_count * (row_height + pad_y * 2)
        expected_y = saved_bottom_y - new_height
        assert expected_y == 1080 - 238
        assert expected_y == 842

    def test_grow_up_subsequent_render_keeps_bottom(self):
        """On subsequent renders, bottom = old_y + old_height.
        If old_y=842, old_height=238, new_height=272 (8 sessions),
        new_y = 842 + 238 - 272 = 808."""
        old_y = 842
        old_height = 238
        new_height = 272
        new_y = old_y + old_height - new_height
        assert new_y == 808

    def test_grow_down_ignores_height_change(self):
        """When grow_up=False, y stays the same regardless of height."""
        old_y = 200
        # grow_down: y is unchanged regardless of session count
        assert old_y == 200
