# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for settings persistence."""

import json

from claude_dashboard.settings import Settings, load_settings, save_settings


class TestLoadSettings:
    def test_returns_defaults_when_file_missing(self, tmp_path):
        path = tmp_path / "nonexistent.json"
        settings = load_settings(path=path)
        assert settings == Settings()

    def test_loads_valid_settings(self, tmp_settings_path, sample_settings_data):
        tmp_settings_path.write_text(json.dumps(sample_settings_data), encoding="utf-8")
        settings = load_settings(path=tmp_settings_path)
        assert settings.window_x == 100
        assert settings.window_y == 200
        assert settings.always_on_top is False
        assert settings.row_height == 40
        assert settings.row_width == 500
        assert settings.poll_interval_seconds == 3
        assert settings.color_working == "#223344"

    def test_ignores_unknown_fields(self, tmp_settings_path):
        data = {"window_x": 50, "bogus_field": "ignored"}
        tmp_settings_path.write_text(json.dumps(data), encoding="utf-8")
        settings = load_settings(path=tmp_settings_path)
        assert settings.window_x == 50
        assert not hasattr(settings, "bogus_field")

    def test_returns_defaults_on_invalid_json(self, tmp_settings_path):
        tmp_settings_path.write_text("not valid json{{{", encoding="utf-8")
        settings = load_settings(path=tmp_settings_path)
        assert settings == Settings()

    def test_returns_defaults_on_non_object_json(self, tmp_settings_path):
        tmp_settings_path.write_text("[1, 2, 3]", encoding="utf-8")
        settings = load_settings(path=tmp_settings_path)
        assert settings == Settings()

    def test_skips_wrong_type_values(self, tmp_settings_path):
        data = {"row_height": "not_an_int", "window_x": 42}
        tmp_settings_path.write_text(json.dumps(data), encoding="utf-8")
        settings = load_settings(path=tmp_settings_path)
        assert settings.row_height == Settings().row_height  # default
        assert settings.window_x == 42

    def test_accepts_none_for_optional_fields(self, tmp_settings_path):
        data = {"window_x": None, "window_y": None}
        tmp_settings_path.write_text(json.dumps(data), encoding="utf-8")
        settings = load_settings(path=tmp_settings_path)
        assert settings.window_x is None
        assert settings.window_y is None


class TestSaveSettings:
    def test_save_creates_file(self, tmp_settings_path):
        settings = Settings(window_x=150, window_y=250)
        save_settings(settings, path=tmp_settings_path)
        assert tmp_settings_path.exists()
        loaded = json.loads(tmp_settings_path.read_text(encoding="utf-8"))
        assert loaded["window_x"] == 150
        assert loaded["window_y"] == 250

    def test_save_creates_parent_dirs(self, tmp_path):
        deep_path = tmp_path / "a" / "b" / "c" / "settings.json"
        save_settings(Settings(), path=deep_path)
        assert deep_path.exists()

    def test_roundtrip_preserves_values(self, tmp_settings_path):
        original = Settings(
            window_x=10,
            window_y=20,
            always_on_top=False,
            row_height=50,
            poll_interval_seconds=10,
            color_working="#aabbcc",
        )
        save_settings(original, path=tmp_settings_path)
        loaded = load_settings(path=tmp_settings_path)
        assert loaded == original

    def test_save_overwrites_existing(self, tmp_settings_path):
        save_settings(Settings(window_x=1), path=tmp_settings_path)
        save_settings(Settings(window_x=2), path=tmp_settings_path)
        loaded = load_settings(path=tmp_settings_path)
        assert loaded.window_x == 2

    def test_ready_settings_roundtrip(self, tmp_settings_path):
        original = Settings(ready_seconds=120, color_ready="#00ff00")
        save_settings(original, path=tmp_settings_path)
        loaded = load_settings(path=tmp_settings_path)
        assert loaded.ready_seconds == 120
        assert loaded.color_ready == "#00ff00"
