# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for VS Code tasks.json write logic."""

import hashlib
import json
import os
from pathlib import Path

from claude_dashboard import config
from claude_dashboard.controller import write_vscode_tasks_json


class TestVscodeTasksTemplate:
    def test_template_is_valid_json(self):
        parsed = json.loads(config.VSCODE_TASKS_JSON_TEMPLATE)
        assert parsed["version"] == "2.0.0"
        assert len(parsed["tasks"]) == 2
        claude_task = parsed["tasks"][0]
        assert claude_task["command"] == "claude -c || claude"
        assert claude_task["label"] == "claude"
        assert claude_task["runOptions"]["runOn"] == "folderOpen"
        assert claude_task["presentation"]["group"] == "claude-dev"
        terminal_task = parsed["tasks"][1]
        assert terminal_task["label"] == "bash"
        assert terminal_task["presentation"]["group"] == "claude-dev"
        assert terminal_task["isBackground"] is True

    def test_hash_matches_template(self):
        expected = hashlib.sha256(config.VSCODE_TASKS_JSON_TEMPLATE.encode("utf-8")).hexdigest()
        assert config.VSCODE_TASKS_JSON_HASH == expected


class TestWriteVscodeTasksJson:
    def test_write_creates_file_and_dir(self, tmp_path):
        cwd = str(tmp_path / "project")
        os.makedirs(cwd)
        write_vscode_tasks_json(cwd=cwd)
        tasks_path = Path(cwd) / ".vscode" / "tasks.json"
        assert tasks_path.exists()

    def test_write_content_matches_template(self, tmp_path):
        cwd = str(tmp_path / "project")
        os.makedirs(cwd)
        write_vscode_tasks_json(cwd=cwd)
        tasks_path = Path(cwd) / ".vscode" / "tasks.json"
        assert tasks_path.read_text(encoding="utf-8") == config.VSCODE_TASKS_JSON_TEMPLATE

    def test_write_skips_when_file_exists(self, tmp_path):
        cwd = str(tmp_path / "project")
        vscode_dir = Path(cwd) / ".vscode"
        vscode_dir.mkdir(parents=True)
        user_content = '{"version": "2.0.0", "tasks": [{"label": "custom"}]}'
        (vscode_dir / "tasks.json").write_text(user_content, encoding="utf-8")
        write_vscode_tasks_json(cwd=cwd)
        content = (vscode_dir / "tasks.json").read_text(encoding="utf-8")
        assert content == user_content

    def test_write_when_cwd_does_not_exist(self, tmp_path):
        cwd = str(tmp_path / "nonexistent")
        write_vscode_tasks_json(cwd=cwd)  # should not raise
        assert not Path(cwd).exists()

    def test_write_when_vscode_dir_exists_but_no_tasks(self, tmp_path):
        """Write succeeds when .vscode/ exists with other files but no tasks.json."""
        cwd = str(tmp_path / "project")
        vscode_dir = Path(cwd) / ".vscode"
        vscode_dir.mkdir(parents=True)
        (vscode_dir / "settings.json").write_text("{}", encoding="utf-8")
        write_vscode_tasks_json(cwd=cwd)
        assert (vscode_dir / "tasks.json").exists()
        assert (vscode_dir / "settings.json").exists()
