"""Middle-click filter clear + pre-filter view restore.

Generated By: Claude Code (Claude Opus 5)
"""

from unittest.mock import MagicMock, patch

import claude_dashboard.ui.main_window  # noqa: F401  (patch target must be imported)
from claude_dashboard.settings import Settings


def _make_window():
    from claude_dashboard.ui.main_window import MainWindow

    with patch.object(MainWindow, "__init__", lambda self, *a, **kw: None):
        win = MainWindow.__new__(MainWindow)
    win._settings = Settings()
    win._window = MagicMock()
    win._title_text_label = MagicMock()
    win._title_fg = "#ffffff"
    win._shaded = False
    win._filter_text = ""
    win._filter_after_id = None
    win._last_sessions = []
    win._on_ghost_toggle = MagicMock()
    win._on_filter_exit = MagicMock()
    return win


def test_middle_click_clears_filter_and_restores_view():
    with patch("claude_dashboard.ui.main_window.tk"):
        win = _make_window()
        win._filter_text = "foo"

        win._on_ghost_toggle_click(MagicMock())

        assert win._filter_text == ""
        # controller re-supplies rows, dropping the hidden ones filter revealed
        win._on_filter_exit.assert_called_once_with()
        # ghosts untouched — middle-click consumed by the filter clear
        win._on_ghost_toggle.assert_not_called()


def test_middle_click_without_filter_toggles_ghosts():
    with patch("claude_dashboard.ui.main_window.tk"):
        win = _make_window()

        win._on_ghost_toggle_click(MagicMock())

        win._on_ghost_toggle.assert_called_once_with()
        win._on_filter_exit.assert_not_called()


def test_middle_click_while_shaded_only_unshades():
    """Shaded title bar treats middle-click as a left-click — no ghost toggle."""
    from claude_dashboard.ui.main_window import MainWindow

    with (
        patch("claude_dashboard.ui.main_window.tk"),
        patch.object(MainWindow, "_apply_shade_state") as apply_shade,
    ):
        win = _make_window()
        win._shaded = True
        win._dragged = False

        win._on_ghost_toggle_click(MagicMock())

        assert win._shaded is False
        apply_shade.assert_called_once_with()
        win._on_ghost_toggle.assert_not_called()


def test_exit_filter_falls_back_to_local_render_without_callback():
    with patch("claude_dashboard.ui.main_window.tk"):
        from claude_dashboard.ui.main_window import MainWindow

        win = _make_window()
        win._filter_text = "foo"
        win._on_filter_exit = None

        with patch.object(MainWindow, "_do_filter_render") as render:
            win._exit_filter_mode()

        render.assert_called_once_with()
