# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for Prometheus-based session state polling."""

import json
from unittest.mock import patch, MagicMock

from claude_dashboard.config import StatusState
from claude_dashboard.otel_state import SessionState, poll_session_states, _parse_value


def _prom_response(*, metric: str, results: list[dict]) -> bytes:
    """Build a Prometheus API JSON response."""
    return json.dumps(
        {"status": "success", "data": {"resultType": "vector", "result": results}}
    ).encode()


def _result(
    *, session_id: str, value: float, host_name: str = "", project: str = "", metric: str = ""
) -> dict:
    """Build a single Prometheus result entry."""
    return {
        "metric": {
            "__name__": metric,
            "session_id": session_id,
            "host_name": host_name,
            "project": project,
        },
        "value": [1234567890, str(value)],
    }


class TestPollSessionStates:
    def test_working_session(self):
        responses = {
            "claude_session_permission": _prom_response(
                metric="claude_session_permission", results=[]
            ),
            "claude_session_working": _prom_response(
                metric="claude_session_working",
                results=[
                    _result(
                        session_id="abc-123", value=5, host_name="myhost", project="/home/user/src"
                    )
                ],
            ),
            "claude_session_ready": _prom_response(metric="claude_session_ready", results=[]),
        }

        def fake_urlopen(req, timeout=None):
            for metric, data in responses.items():
                if metric in req.full_url:
                    mock = MagicMock()
                    mock.read.return_value = data
                    mock.__enter__ = lambda s: s
                    mock.__exit__ = MagicMock(return_value=False)
                    return mock
            raise ValueError(f"unexpected url: {req.full_url}")

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result == {
            "abc-123": SessionState(
                state=StatusState.WORKING, host_name="myhost", project="/home/user/src"
            ),
        }

    def test_permission_overrides_working(self):
        responses = {
            "claude_session_permission": _prom_response(
                metric="claude_session_permission",
                results=[_result(session_id="abc-123", value=1, host_name="myhost")],
            ),
            "claude_session_working": _prom_response(
                metric="claude_session_working",
                results=[_result(session_id="abc-123", value=10, host_name="myhost")],
            ),
            "claude_session_ready": _prom_response(metric="claude_session_ready", results=[]),
        }

        def fake_urlopen(req, timeout=None):
            for metric, data in responses.items():
                if metric in req.full_url:
                    mock = MagicMock()
                    mock.read.return_value = data
                    mock.__enter__ = lambda s: s
                    mock.__exit__ = MagicMock(return_value=False)
                    return mock
            raise ValueError(f"unexpected url: {req.full_url}")

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result["abc-123"].state == StatusState.PERMISSION_REQUIRED

    def test_ready_session(self):
        responses = {
            "claude_session_permission": _prom_response(
                metric="claude_session_permission", results=[]
            ),
            "claude_session_working": _prom_response(metric="claude_session_working", results=[]),
            "claude_session_ready": _prom_response(
                metric="claude_session_ready",
                results=[_result(session_id="abc-123", value=1, host_name="sandbox-mybox")],
            ),
        }

        def fake_urlopen(req, timeout=None):
            for metric, data in responses.items():
                if metric in req.full_url:
                    mock = MagicMock()
                    mock.read.return_value = data
                    mock.__enter__ = lambda s: s
                    mock.__exit__ = MagicMock(return_value=False)
                    return mock
            raise ValueError(f"unexpected url: {req.full_url}")

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result["abc-123"] == SessionState(
            state=StatusState.READY, host_name="sandbox-mybox", project=""
        )

    def test_multiple_sessions(self):
        responses = {
            "claude_session_permission": _prom_response(
                metric="claude_session_permission", results=[]
            ),
            "claude_session_working": _prom_response(
                metric="claude_session_working",
                results=[
                    _result(session_id="s1", value=3, host_name="host1"),
                    _result(session_id="s2", value=7, host_name="host2"),
                ],
            ),
            "claude_session_ready": _prom_response(
                metric="claude_session_ready",
                results=[_result(session_id="s3", value=1, host_name="host3")],
            ),
        }

        def fake_urlopen(req, timeout=None):
            for metric, data in responses.items():
                if metric in req.full_url:
                    mock = MagicMock()
                    mock.read.return_value = data
                    mock.__enter__ = lambda s: s
                    mock.__exit__ = MagicMock(return_value=False)
                    return mock
            raise ValueError(f"unexpected url: {req.full_url}")

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert len(result) == 3
        assert result["s1"].state == StatusState.WORKING
        assert result["s2"].state == StatusState.WORKING
        assert result["s3"].state == StatusState.READY

    def test_empty_results(self):
        def fake_urlopen(req, timeout=None):
            mock = MagicMock()
            mock.read.return_value = _prom_response(metric="", results=[])
            mock.__enter__ = lambda s: s
            mock.__exit__ = MagicMock(return_value=False)
            return mock

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result == {}

    def test_prometheus_unreachable(self):
        with patch(
            "claude_dashboard.otel_state.urllib.request.urlopen",
            side_effect=ConnectionRefusedError("connection refused"),
        ):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result == {}

    def test_zero_value_ignored(self):
        responses = {
            "claude_session_permission": _prom_response(
                metric="claude_session_permission", results=[]
            ),
            "claude_session_working": _prom_response(
                metric="claude_session_working",
                results=[_result(session_id="abc-123", value=0, host_name="myhost")],
            ),
            "claude_session_ready": _prom_response(metric="claude_session_ready", results=[]),
        }

        def fake_urlopen(req, timeout=None):
            for metric, data in responses.items():
                if metric in req.full_url:
                    mock = MagicMock()
                    mock.read.return_value = data
                    mock.__enter__ = lambda s: s
                    mock.__exit__ = MagicMock(return_value=False)
                    return mock
            raise ValueError(f"unexpected url: {req.full_url}")

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result == {}

    def test_missing_session_id_ignored(self):
        responses = {
            "claude_session_permission": _prom_response(
                metric="claude_session_permission", results=[]
            ),
            "claude_session_working": _prom_response(
                metric="claude_session_working",
                results=[{"metric": {"host_name": "myhost"}, "value": [123, "5"]}],
            ),
            "claude_session_ready": _prom_response(metric="claude_session_ready", results=[]),
        }

        def fake_urlopen(req, timeout=None):
            for metric, data in responses.items():
                if metric in req.full_url:
                    mock = MagicMock()
                    mock.read.return_value = data
                    mock.__enter__ = lambda s: s
                    mock.__exit__ = MagicMock(return_value=False)
                    return mock
            raise ValueError(f"unexpected url: {req.full_url}")

        with patch("claude_dashboard.otel_state.urllib.request.urlopen", side_effect=fake_urlopen):
            result = poll_session_states(prometheus_url="http://localhost:9090")

        assert result == {}


class TestParseValue:
    def test_valid_float(self):
        assert _parse_value({"value": [123, "42.5"]}) == 42.5

    def test_valid_int_string(self):
        assert _parse_value({"value": [123, "10"]}) == 10.0

    def test_missing_value_key(self):
        assert _parse_value({}) is None

    def test_empty_value_list(self):
        assert _parse_value({"value": []}) is None

    def test_non_numeric_string(self):
        assert _parse_value({"value": [123, "NaN"]}) is None
