# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Tests for flag icon rendering — terminal activity arrow tinting."""

from PIL import Image

from claude_dashboard import config
from claude_dashboard.ui.main_window import _tint_image


def _load_arrow() -> Image.Image:
    return Image.open(config.ICON_TERMINAL_ACTIVITY).convert("RGBA")


def _opaque_colors(image: Image.Image) -> set[tuple[int, int, int]]:
    return {px[:3] for _, px in image.getcolors(maxcolors=1 << 24) if px[3] > 0}


def _transparent_count(image: Image.Image) -> int:
    return sum(count for count, px in image.getcolors(maxcolors=1 << 24) if px[3] == 0)


class TestTintImage:
    def test_opaque_pixels_take_new_color(self):
        tinted = _tint_image(_load_arrow(), (220, 38, 38))
        assert _opaque_colors(tinted) == {(220, 38, 38)}

    def test_alpha_channel_preserved(self):
        arrow = _load_arrow()
        tinted = _tint_image(arrow, (21, 128, 61))
        assert tinted.getchannel("A").tobytes() == arrow.getchannel("A").tobytes()

    def test_transparent_pixel_count_unchanged(self):
        arrow = _load_arrow()
        tinted = _tint_image(arrow, (255, 255, 255))
        assert tinted.size == arrow.size
        assert _transparent_count(tinted) == _transparent_count(arrow)

    def test_source_image_untouched(self):
        arrow = _load_arrow()
        before = arrow.tobytes()
        _tint_image(arrow, (0, 0, 0))
        assert arrow.tobytes() == before


class TestArrowAssetIsFlat:
    """Tinting assumes one flat color; guard the assumption for future assets."""

    def test_single_opaque_color(self):
        assert len(_opaque_colors(_load_arrow())) == 1
