# Generated By: Claude Code (Claude Opus 4.6)
"""Integration tests — POST hook events to the server and verify state transitions."""

import json
import urllib.request

from claude_dashboard.config import StatusState
from claude_dashboard.hook_server import HookServer


def _post_hook(port: int, payload: dict) -> int:
    """POST a hook event and return the HTTP status code."""
    data = json.dumps(payload).encode()
    req = urllib.request.Request(
        f"http://127.0.0.1:{port}/hook",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=5) as resp:
        return resp.status


class TestStateTransitions:
    """End-to-end: POST a sequence of hook events and verify state transitions."""

    def _make_server(self):
        states: dict[str, StatusState] = {}
        ended: list[str] = []

        def on_hook(session_id, event, state, cwd=""):
            states[session_id] = state

        def on_end(session_id):
            ended.append(session_id)

        server = HookServer(on_hook_event=on_hook, on_session_end=on_end, port=0)
        return server, states, ended

    def test_full_tool_lifecycle(self):
        """user prompt → tool use → permission → approval → stop → idle."""
        server, states, _ = self._make_server()
        server.start()
        sid = "lifecycle-test"

        try:
            # User submits prompt → WORKING
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "UserPromptSubmit"})
            assert states[sid] == StatusState.WORKING

            # Claude wants to use a tool (auto-approved) → stays WORKING
            _post_hook(
                server.port,
                {"session_id": sid, "hook_event_name": "PreToolUse", "tool_name": "Read"},
            )
            assert states[sid] == StatusState.WORKING

            # Tool completes → WORKING
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "PostToolUse"})
            assert states[sid] == StatusState.WORKING

            # Claude wants to use Bash (needs permission) → PermissionRequest fires
            _post_hook(
                server.port,
                {"session_id": sid, "hook_event_name": "PermissionRequest", "tool_name": "Bash"},
            )
            assert states[sid] == StatusState.PERMISSION_REQUIRED

            # User approves → tool runs → PostToolUse
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "PostToolUse"})
            assert states[sid] == StatusState.WORKING

            # Claude finishes → IDLE
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "Stop"})
            assert states[sid] == StatusState.IDLE
        finally:
            server.stop()

    def test_ask_user_question(self):
        """AskUserQuestion → AWAITING_INPUT, then answer → WORKING → IDLE."""
        server, states, _ = self._make_server()
        server.start()
        sid = "question-test"

        try:
            _post_hook(
                server.port,
                {
                    "session_id": sid,
                    "hook_event_name": "PreToolUse",
                    "tool_name": "AskUserQuestion",
                },
            )
            assert states[sid] == StatusState.AWAITING_INPUT

            # User answers → PostToolUse
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "PostToolUse"})
            assert states[sid] == StatusState.WORKING

            # Claude finishes
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "Stop"})
            assert states[sid] == StatusState.IDLE
        finally:
            server.stop()

    def test_session_end(self):
        """SessionEnd fires the on_session_end callback."""
        server, states, ended = self._make_server()
        server.start()
        sid = "ending-test"

        try:
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "UserPromptSubmit"})
            assert states[sid] == StatusState.WORKING

            _post_hook(server.port, {"session_id": sid, "hook_event_name": "SessionEnd"})
            assert sid in ended
        finally:
            server.stop()

    def test_multiple_sessions_independent(self):
        """Two sessions maintain independent state."""
        server, states, _ = self._make_server()
        server.start()

        try:
            _post_hook(server.port, {"session_id": "s1", "hook_event_name": "UserPromptSubmit"})
            _post_hook(server.port, {"session_id": "s2", "hook_event_name": "Stop"})

            assert states["s1"] == StatusState.WORKING
            assert states["s2"] == StatusState.IDLE

            _post_hook(
                server.port,
                {"session_id": "s1", "hook_event_name": "PermissionRequest", "tool_name": "Bash"},
            )
            assert states["s1"] == StatusState.PERMISSION_REQUIRED
            assert states["s2"] == StatusState.IDLE
        finally:
            server.stop()

    def test_rapid_tool_calls_stay_working(self):
        """Multiple auto-approved tools in sequence → never flickers to permission."""
        server, states, _ = self._make_server()
        server.start()
        sid = "rapid-test"
        all_states: list[StatusState] = []

        # Override to capture every state
        original = server._server.on_hook_event  # type: ignore[attr-defined]

        def tracking_hook(session_id, event, state, cwd=""):
            all_states.append(state)
            original(session_id, event, state, cwd)

        server._server.on_hook_event = tracking_hook  # type: ignore[attr-defined]

        try:
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "UserPromptSubmit"})
            for _ in range(5):
                _post_hook(
                    server.port,
                    {"session_id": sid, "hook_event_name": "PreToolUse", "tool_name": "Read"},
                )
                _post_hook(server.port, {"session_id": sid, "hook_event_name": "PostToolUse"})
            _post_hook(server.port, {"session_id": sid, "hook_event_name": "Stop"})

            # Should never see PERMISSION_REQUIRED
            assert StatusState.PERMISSION_REQUIRED not in all_states
            assert all_states[-1] == StatusState.IDLE
        finally:
            server.stop()
