# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for transcript parsing and state machine."""

import json

from claude_dashboard.transcript import StatusState, detect_state, tail_jsonl


def _write_jsonl(path, entries):
    """Write a list of dicts as JSONL to a file."""
    with open(path, "w", encoding="utf-8") as fh:
        for entry in entries:
            fh.write(json.dumps(entry) + "\n")


class TestTailJsonl:
    def test_reads_last_n_lines(self, tmp_path):
        path = tmp_path / "transcript.jsonl"
        entries = [{"n": i} for i in range(20)]
        _write_jsonl(path, entries)

        result = tail_jsonl(path, max_lines=5)
        assert len(result) == 5
        assert result[-1]["n"] == 19

    def test_returns_empty_for_missing_file(self, tmp_path):
        result = tail_jsonl(tmp_path / "nonexistent.jsonl")
        assert result == []

    def test_returns_empty_for_empty_file(self, tmp_path):
        path = tmp_path / "empty.jsonl"
        path.write_text("", encoding="utf-8")
        result = tail_jsonl(path)
        assert result == []

    def test_handles_malformed_lines(self, tmp_path):
        path = tmp_path / "mixed.jsonl"
        path.write_text(
            '{"good": true}\nnot json\n{"also_good": true}\n',
            encoding="utf-8",
        )
        result = tail_jsonl(path)
        assert len(result) == 2

    def test_reads_all_when_fewer_than_max(self, tmp_path):
        path = tmp_path / "small.jsonl"
        entries = [{"n": i} for i in range(3)]
        _write_jsonl(path, entries)
        result = tail_jsonl(path, max_lines=10)
        assert len(result) == 3


class TestDetectState:
    def test_idle_after_end_turn(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "user",
                    "message": {"role": "user", "content": [{"type": "text", "text": "hi"}]},
                },
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "end_turn",
                        "content": [{"type": "text", "text": "hello"}],
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.IDLE

    def test_awaiting_input_ask_user_question(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "tool_use",
                        "content": [
                            {
                                "type": "tool_use",
                                "id": "q_123",
                                "name": "AskUserQuestion",
                                "input": {"question": "Which option?"},
                            }
                        ],
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.AWAITING_INPUT

    def test_permission_required(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "tool_use",
                        "content": [
                            {"type": "tool_use", "id": "tool_123", "name": "Read", "input": {}}
                        ],
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.PERMISSION_REQUIRED

    def test_permission_required_with_hook_progress(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "tool_use",
                        "content": [
                            {"type": "tool_use", "id": "tool_123", "name": "Read", "input": {}}
                        ],
                    },
                },
                {"type": "progress", "data": {"type": "hook_progress"}},
            ],
        )
        assert detect_state(path) == StatusState.PERMISSION_REQUIRED

    def test_working_after_tool_approved(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "tool_use",
                        "content": [
                            {"type": "tool_use", "id": "tool_123", "name": "Read", "input": {}}
                        ],
                    },
                },
                {
                    "type": "user",
                    "message": {
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": "tool_123",
                                "content": "file contents",
                            }
                        ]
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.WORKING

    def test_working_after_tool_denied_with_text(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "tool_use",
                        "content": [
                            {"type": "tool_use", "id": "tool_123", "name": "Read", "input": {}}
                        ],
                    },
                },
                {
                    "type": "user",
                    "message": {
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": "tool_123",
                                "content": "denied",
                                "is_error": True,
                            },
                        ]
                    },
                },
            ],
        )
        # Tool result exists (even if error) -> Working (Claude processes the denial)
        assert detect_state(path) == StatusState.WORKING

    def test_working_on_user_prompt(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {"type": "assistant", "message": {"stop_reason": "end_turn", "content": []}},
                {
                    "type": "user",
                    "message": {
                        "role": "user",
                        "content": [{"type": "text", "text": "do something"}],
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.WORKING

    def test_idle_after_interruption(self, tmp_path):
        """User interrupted Claude mid-response → IDLE."""
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "assistant",
                    "message": {
                        "stop_reason": "tool_use",
                        "content": [{"type": "tool_use", "id": "t1", "name": "Bash", "input": {}}],
                    },
                },
                {
                    "type": "user",
                    "message": {
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": "t1",
                                "content": "ok",
                            }
                        ]
                    },
                },
                {
                    "type": "user",
                    "message": {
                        "content": [{"type": "text", "text": "[Request interrupted by user]"}]
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.IDLE

    def test_unknown_for_none_path(self):
        assert detect_state(None) == StatusState.UNKNOWN

    def test_unknown_for_empty_file(self, tmp_path):
        path = tmp_path / "t.jsonl"
        path.write_text("", encoding="utf-8")
        assert detect_state(path) == StatusState.UNKNOWN

    def test_unknown_for_no_assistant_entries(self, tmp_path):
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {"type": "system", "message": {"content": "system prompt"}},
            ],
        )
        assert detect_state(path) == StatusState.UNKNOWN

    def test_unknown_for_orphaned_tool_result(self, tmp_path):
        """User entry with tool_result but no assistant entry returns UNKNOWN."""
        path = tmp_path / "t.jsonl"
        _write_jsonl(
            path,
            [
                {
                    "type": "user",
                    "message": {
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": "orphan",
                                "content": "result",
                            }
                        ]
                    },
                },
            ],
        )
        assert detect_state(path) == StatusState.UNKNOWN
