# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for ghost session git operations.

Verifies that ghost sessions get initial git status at creation and
periodic git updates at a lower frequency than live sessions.
"""

from unittest.mock import patch

from claude_dashboard.config import GitStatus
from claude_dashboard.controller import _SessionEntry
from claude_dashboard.session import SessionInfo


def _make_session(*, pid: int = -1, cwd: str = "/tmp/test") -> SessionInfo:
    return SessionInfo(pid=pid, session_id=f"unattached-{pid}", cwd=cwd, started_at=0)


class TestGhostGitTickCounter:
    """Ghost git tick counter increments and resets at interval."""

    def test_counter_initializes_to_zero(self):
        """Ghost git tick counter starts at zero."""
        # Mirrors the _fetch_tick_counter pattern
        counter = 0
        assert counter == 0

    def test_counter_increments(self):
        counter = 0
        counter += 1
        assert counter == 1

    def test_counter_resets_at_interval(self):
        interval = 100
        counter = interval  # simulates reaching the interval
        if counter >= interval:
            counter = 0
        assert counter == 0

    def test_interval_scales_with_poll_interval(self):
        """Interval is ~300s worth of ticks regardless of poll_interval."""
        # poll_interval=3 → 300/3 = 100 ticks
        assert max(300 // max(3, 1), 1) == 100
        # poll_interval=5 → 300/5 = 60 ticks
        assert max(300 // max(5, 1), 1) == 60
        # poll_interval=1 → 300/1 = 300 ticks
        assert max(300 // max(1, 1), 1) == 300


class TestGhostInitialGitCheck:
    """Ghost sessions get git_status and merged set at creation."""

    @patch("claude_dashboard.controller.git_check")
    @patch("claude_dashboard.controller.detect_branch")
    def test_create_ghost_sets_git_status(self, mock_branch, mock_git_check):
        """_create_ghost calls git_check and sets git_status on the entry."""
        mock_branch.return_value = "feature-branch"
        mock_git_check.return_value = (GitStatus.UNSTAGED_CHANGES, False)

        entry = _SessionEntry(_make_session())
        entry.unattached = True
        entry.branch = mock_branch(cwd="/tmp/test", trunk_branch="main")
        entry.git_status, entry.merged = mock_git_check(
            cwd="/tmp/test", trunk_ref="origin/main", branch=entry.branch
        )

        assert entry.git_status == GitStatus.UNSTAGED_CHANGES
        assert entry.merged is False

    @patch("claude_dashboard.controller.git_check")
    @patch("claude_dashboard.controller.detect_branch")
    def test_create_ghost_detects_merged(self, mock_branch, mock_git_check):
        mock_branch.return_value = "merged-branch"
        mock_git_check.return_value = (GitStatus.PUSHED_NOT_MERGED, True)

        entry = _SessionEntry(_make_session())
        entry.unattached = True
        entry.branch = mock_branch(cwd="/tmp/test", trunk_branch="main")
        entry.git_status, entry.merged = mock_git_check(
            cwd="/tmp/test", trunk_ref="origin/main", branch=entry.branch
        )

        assert entry.git_status == GitStatus.PUSHED_NOT_MERGED
        assert entry.merged is True

    def test_ghost_defaults_to_clean(self):
        """Without git_check, ghost defaults to CLEAN and not merged."""
        entry = _SessionEntry(_make_session())
        entry.unattached = True
        assert entry.git_status == GitStatus.CLEAN
        assert entry.merged is False


class TestGhostGitUpdateScope:
    """Ghost git updates only run for unattached sessions."""

    def test_live_sessions_skipped_by_unattached_filter(self):
        sessions = {
            1000: _SessionEntry(_make_session(pid=1000)),
            -1: _SessionEntry(_make_session(pid=-1)),
        }
        sessions[-1].unattached = True

        ghosts = [e for e in sessions.values() if e.unattached]
        assert len(ghosts) == 1
        assert ghosts[0].session.pid == -1

    def test_only_ghosts_get_periodic_update(self):
        sessions = {
            1000: _SessionEntry(_make_session(pid=1000, cwd="/tmp/live")),
            -1: _SessionEntry(_make_session(pid=-1, cwd="/tmp/ghost1")),
            -2: _SessionEntry(_make_session(pid=-2, cwd="/tmp/ghost2")),
        }
        sessions[-1].unattached = True
        sessions[-2].unattached = True

        updated_cwds = []
        for entry in sessions.values():
            if not entry.unattached:
                continue
            updated_cwds.append(entry.session.cwd)

        assert "/tmp/live" not in updated_cwds
        assert "/tmp/ghost1" in updated_cwds
        assert "/tmp/ghost2" in updated_cwds


class TestGhostGitFetchDedup:
    """Ghost git fetch deduplicates by CWD."""

    def test_same_cwd_fetched_once(self):
        fetched_cwds: set[str] = set()
        ghost_cwds = ["/tmp/project", "/tmp/project", "/tmp/other"]

        for cwd in ghost_cwds:
            if cwd not in fetched_cwds:
                fetched_cwds.add(cwd)

        assert len(fetched_cwds) == 2
        assert "/tmp/project" in fetched_cwds
        assert "/tmp/other" in fetched_cwds
