# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for session capacity management — last_active timestamps and ghost eviction."""

from claude_dashboard.controller import _SessionEntry, _now_epoch
from claude_dashboard.session import SessionInfo


def _make_session(*, pid: int = 1000, cwd: str = "/tmp/test") -> SessionInfo:
    return SessionInfo(pid=pid, session_id="test-sid", cwd=cwd, started_at=0)


class TestNowEpoch:
    """Test the _now_epoch helper."""

    def test_returns_float(self):
        result = _now_epoch()
        assert isinstance(result, float)

    def test_is_recent(self):
        result = _now_epoch()
        assert result > 1_700_000_000  # after 2023


class TestLastActiveOnCreation:
    """_add_session sets last_active to current time."""

    def test_new_entry_has_non_zero_last_active(self):
        entry = _SessionEntry(_make_session())
        entry.last_active = _now_epoch()
        assert entry.last_active > 0.0

    def test_default_is_zero(self):
        entry = _SessionEntry(_make_session())
        assert entry.last_active == 0.0


class TestLastActiveOnHookEvent:
    """Hook events update last_active."""

    def test_hook_event_updates_timestamp(self):
        entry = _SessionEntry(_make_session())
        assert entry.last_active == 0.0
        entry.last_active = _now_epoch()
        assert entry.last_active > 0.0


class TestLastActiveInheritance:
    """Ghost inherits last_active from the dying live session."""

    def test_ghost_inherits_last_active(self):
        live = _SessionEntry(_make_session())
        live.last_active = 1_700_000_000.0
        ghost = _SessionEntry(_make_session(pid=-1))
        ghost.unattached = True
        ghost.last_active = live.last_active
        assert ghost.last_active == 1_700_000_000.0


class TestLastActivePersistence:
    """last_active survives save/restore cycle."""

    def _serialize_entry(self, entry: _SessionEntry) -> dict:
        return {
            "state": entry.state.value,
            "flagged": entry.flagged,
            "last_active": entry.last_active,
        }

    def test_roundtrip_preserves_last_active(self):
        entry = _SessionEntry(_make_session())
        entry.last_active = 1_700_000_000.0
        saved = self._serialize_entry(entry)
        assert saved["last_active"] == 1_700_000_000.0

        restored = _SessionEntry(_make_session())
        restored.last_active = float(saved.get("last_active", 0.0))
        assert restored.last_active == 1_700_000_000.0

    def test_missing_last_active_defaults_to_zero(self):
        saved = {"state": "idle", "hidden": False, "flagged": False, "agents": {}}
        restored = _SessionEntry(_make_session())
        restored.last_active = float(saved.get("last_active", 0.0))
        assert restored.last_active == 0.0


class TestEvictOldestGhosts:
    """Test the ghost eviction algorithm.

    max_sessions caps TOTAL sessions. Only non-flagged ghosts are eviction
    candidates — live sessions and flagged ghosts are never removed.
    """

    def _make_ghost(
        self, *, pid: int, cwd: str, last_active: float, flagged: bool = False
    ) -> _SessionEntry:
        entry = _SessionEntry(_make_session(pid=pid, cwd=cwd))
        entry.unattached = True
        entry.last_active = last_active
        entry.flagged = flagged
        return entry

    def _make_live(self, *, pid: int, cwd: str) -> _SessionEntry:
        entry = _SessionEntry(_make_session(pid=pid, cwd=cwd))
        entry.last_active = _now_epoch()
        return entry

    def _evict(
        self, sessions: dict[int, _SessionEntry], max_sessions: int
    ) -> dict[int, _SessionEntry]:
        """Replicate _evict_oldest_ghosts logic — total count vs max."""
        total = len(sessions)
        if total <= max_sessions:
            return sessions
        candidates = [
            (pid, entry)
            for pid, entry in sessions.items()
            if entry.unattached and not entry.flagged
        ]
        if not candidates:
            return sessions
        candidates.sort(key=lambda pair: pair[1].last_active)
        evict_count = min(len(candidates), total - max_sessions)
        for pid, _ in candidates[:evict_count]:
            sessions.pop(pid)
        return sessions

    def test_no_eviction_when_under_limit(self):
        sessions = {
            -1: self._make_ghost(pid=-1, cwd="/tmp/a", last_active=100.0),
            -2: self._make_ghost(pid=-2, cwd="/tmp/b", last_active=200.0),
        }
        result = self._evict(sessions, max_sessions=5)
        assert len(result) == 2

    def test_evicts_oldest_ghost(self):
        sessions = {
            -1: self._make_ghost(pid=-1, cwd="/tmp/old", last_active=100.0),
            -2: self._make_ghost(pid=-2, cwd="/tmp/new", last_active=300.0),
            -3: self._make_ghost(pid=-3, cwd="/tmp/mid", last_active=200.0),
        }
        result = self._evict(sessions, max_sessions=2)
        assert len(result) == 2
        assert -1 not in result
        assert -2 in result
        assert -3 in result

    def test_flagged_ghosts_not_evicted(self):
        sessions = {
            -1: self._make_ghost(pid=-1, cwd="/tmp/old", last_active=100.0, flagged=True),
            -2: self._make_ghost(pid=-2, cwd="/tmp/new", last_active=300.0),
            -3: self._make_ghost(pid=-3, cwd="/tmp/mid", last_active=200.0),
        }
        # 3 total, max=2 → need to evict 1, but flagged is exempt
        result = self._evict(sessions, max_sessions=2)
        assert -1 in result  # flagged, never evicted
        assert -2 in result  # newest non-flagged, kept
        assert -3 not in result  # oldest non-flagged, evicted

    def test_live_sessions_count_toward_total(self):
        """30 live + 15 ghosts with max=40 → evict 5 oldest ghosts."""
        sessions: dict[int, _SessionEntry] = {}
        for i in range(30):
            sessions[1000 + i] = self._make_live(pid=1000 + i, cwd=f"/tmp/live-{i}")
        for i in range(15):
            sessions[-(i + 1)] = self._make_ghost(
                pid=-(i + 1), cwd=f"/tmp/ghost-{i}", last_active=100.0 + i
            )
        result = self._evict(sessions, max_sessions=40)
        assert len(result) == 40
        # All 30 live sessions kept
        for i in range(30):
            assert 1000 + i in result
        # 5 oldest ghosts evicted (ghost-0 through ghost-4)
        for i in range(5):
            assert -(i + 1) not in result
        # 10 newest ghosts kept (ghost-5 through ghost-14)
        for i in range(5, 15):
            assert -(i + 1) in result

    def test_live_sessions_not_evicted(self):
        sessions = {
            1000: self._make_live(pid=1000, cwd="/tmp/live"),
            -1: self._make_ghost(pid=-1, cwd="/tmp/ghost", last_active=300.0),
        }
        result = self._evict(sessions, max_sessions=2)
        assert 1000 in result
        assert -1 in result

    def test_all_live_no_eviction_possible(self):
        """When over limit but no evictable ghosts, nothing happens."""
        sessions = {
            1000: self._make_live(pid=1000, cwd="/tmp/a"),
            1001: self._make_live(pid=1001, cwd="/tmp/b"),
            1002: self._make_live(pid=1002, cwd="/tmp/c"),
        }
        result = self._evict(sessions, max_sessions=2)
        assert len(result) == 3  # can't evict live sessions

    def test_max_sessions_zero_evicts_all_non_flagged(self):
        sessions = {
            -1: self._make_ghost(pid=-1, cwd="/tmp/a", last_active=100.0),
            -2: self._make_ghost(pid=-2, cwd="/tmp/b", last_active=200.0),
            -3: self._make_ghost(pid=-3, cwd="/tmp/c", last_active=300.0, flagged=True),
        }
        result = self._evict(sessions, max_sessions=0)
        assert -1 not in result
        assert -2 not in result
        assert -3 in result  # flagged, kept

    def test_zero_entries_evicted_first(self):
        sessions = {
            -1: self._make_ghost(pid=-1, cwd="/tmp/legacy", last_active=0.0),
            -2: self._make_ghost(pid=-2, cwd="/tmp/recent", last_active=300.0),
        }
        result = self._evict(sessions, max_sessions=1)
        assert -1 not in result
        assert -2 in result


class TestEvictionOnStartup:
    """Eviction runs after creating unattached placeholders from state file."""

    def _make_ghost(
        self, *, pid: int, cwd: str, last_active: float, flagged: bool = False
    ) -> _SessionEntry:
        entry = _SessionEntry(_make_session(pid=pid, cwd=cwd))
        entry.unattached = True
        entry.last_active = last_active
        entry.flagged = flagged
        return entry

    def _evict(
        self, sessions: dict[int, _SessionEntry], max_sessions: int
    ) -> dict[int, _SessionEntry]:
        total = len(sessions)
        if total <= max_sessions:
            return sessions
        candidates = [
            (pid, entry)
            for pid, entry in sessions.items()
            if entry.unattached and not entry.flagged
        ]
        if not candidates:
            return sessions
        candidates.sort(key=lambda pair: pair[1].last_active)
        evict_count = min(len(candidates), total - max_sessions)
        for pid, _ in candidates[:evict_count]:
            sessions.pop(pid)
        return sessions

    def test_startup_eviction_prunes_old_state_entries(self):
        """Simulates loading 5 ghosts from state with max_sessions=2."""
        sessions: dict[int, _SessionEntry] = {}
        for i in range(5):
            pid = -(i + 1)
            sessions[pid] = self._make_ghost(
                pid=pid,
                cwd=f"/tmp/project-{i}",
                last_active=1000.0 + i * 100,
            )
        result = self._evict(sessions, max_sessions=2)
        assert len(result) == 2
        remaining_cwds = {e.session.cwd for e in result.values()}
        assert "/tmp/project-3" in remaining_cwds
        assert "/tmp/project-4" in remaining_cwds
