# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for the hook HTTP server."""

import json
import threading
import urllib.request

from claude_dashboard.hook_server import HookServer
from claude_dashboard.config import StatusState


class TestHookServer:
    def test_receives_hook_event(self):
        """POST a hook event and verify the callback fires."""
        received: list[tuple[str, str, StatusState]] = []
        event = threading.Event()

        def on_hook(session_id, hook_event, state, cwd=""):
            received.append((session_id, hook_event, state))
            event.set()

        server = HookServer(
            on_hook_event=on_hook,
            on_session_end=lambda sid: None,
            port=0,  # OS-assigned port
        )
        server.start()

        try:
            payload = json.dumps(
                {
                    "session_id": "test-session-123",
                    "hook_event_name": "Stop",
                    "cwd": "/tmp/test",
                }
            ).encode()

            req = urllib.request.Request(
                f"http://127.0.0.1:{server.port}/hook",
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=5) as resp:
                assert resp.status == 200

            event.wait(timeout=2)
            assert len(received) == 1
            assert received[0] == ("test-session-123", "Stop", StatusState.IDLE)
        finally:
            server.stop()

    def test_permission_request_event(self):
        """PermissionRequest hook fires PERMISSION_REQUIRED state."""
        received: list[tuple[str, str, StatusState]] = []
        event = threading.Event()

        def on_hook(session_id, hook_event, state, cwd=""):
            received.append((session_id, hook_event, state))
            event.set()

        server = HookServer(
            on_hook_event=on_hook,
            on_session_end=lambda sid: None,
            port=0,
        )
        server.start()

        try:
            payload = json.dumps(
                {
                    "session_id": "test-session-456",
                    "hook_event_name": "PermissionRequest",
                    "tool_name": "Bash",
                    "tool_input": {"command": "rm -rf /"},
                }
            ).encode()

            req = urllib.request.Request(
                f"http://127.0.0.1:{server.port}/hook",
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=5):
                pass

            event.wait(timeout=2)
            assert received[0][2] == StatusState.PERMISSION_REQUIRED
        finally:
            server.stop()

    def test_session_end_fires_callback(self):
        """SessionEnd hook fires the on_session_end callback."""
        ended: list[str] = []
        event = threading.Event()

        def on_end(session_id):
            ended.append(session_id)
            event.set()

        server = HookServer(
            on_hook_event=lambda *a: None,
            on_session_end=on_end,
            port=0,
        )
        server.start()

        try:
            payload = json.dumps(
                {
                    "session_id": "ending-session",
                    "hook_event_name": "SessionEnd",
                }
            ).encode()

            req = urllib.request.Request(
                f"http://127.0.0.1:{server.port}/hook",
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=5):
                pass

            event.wait(timeout=2)
            assert ended == ["ending-session"]
        finally:
            server.stop()

    def test_empty_body_returns_400(self):
        """POST with invalid body returns 400."""
        server = HookServer(
            on_hook_event=lambda *a: None,
            on_session_end=lambda s: None,
            port=0,
        )
        server.start()

        try:
            req = urllib.request.Request(
                f"http://127.0.0.1:{server.port}/hook",
                data=b"not json",
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            try:
                urllib.request.urlopen(req, timeout=5)
                assert False, "Expected HTTP error"
            except urllib.error.HTTPError as e:
                assert e.code == 400
        finally:
            server.stop()
