# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for OpenShell sandbox session discovery."""

import json
import subprocess
from unittest.mock import MagicMock, patch

from claude_dashboard.platform.base import ContainerInfo, ContainerType
from claude_dashboard.session import discover_sandbox_sessions


def _make_sandbox_json(sandboxes):
    """Build JSON output matching openshell sandbox list --output json."""
    return json.dumps(
        [
            {
                "name": sb["name"],
                "phase": sb.get("phase", "Ready"),
                "created_at": sb.get("created_at", "2026-06-02 12:00:00"),
                "id": sb.get("id", "fake-uuid"),
            }
            for sb in sandboxes
        ]
    )


class TestDiscoverSandboxSessions:
    def test_discovers_ready_sandbox(self, tmp_path):
        sandbox_dir = tmp_path / "my-sandbox"
        sandbox_dir.mkdir()
        json_out = _make_sandbox_json([{"name": "my-sandbox"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert len(sessions) == 1
        assert sessions[0].session_id == "sandbox-my-sandbox"
        assert sessions[0].cwd == str(sandbox_dir)
        assert sessions[0].entrypoint == "sandbox"
        assert sessions[0].pid == 0

    def test_filters_non_ready_phase(self, tmp_path):
        sandbox_dir = tmp_path / "stopping"
        sandbox_dir.mkdir()
        json_out = _make_sandbox_json([{"name": "stopping", "phase": "Stopping"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_skips_sandbox_without_host_dir(self, tmp_path):
        json_out = _make_sandbox_json([{"name": "no-dir"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_openshell_not_installed(self):
        with patch("subprocess.run", side_effect=FileNotFoundError):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_openshell_timeout(self):
        with patch("subprocess.run", side_effect=subprocess.TimeoutExpired("openshell", 5)):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_openshell_nonzero_exit(self):
        mock_result = MagicMock(returncode=1, stdout="")

        with patch("subprocess.run", return_value=mock_result):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_invalid_json(self):
        mock_result = MagicMock(returncode=0, stdout="not valid json{{{")

        with patch("subprocess.run", return_value=mock_result):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_non_list_json(self):
        mock_result = MagicMock(returncode=0, stdout='{"not": "a list"}')

        with patch("subprocess.run", return_value=mock_result):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_parses_created_at_timestamp(self, tmp_path):
        sandbox_dir = tmp_path / "ts-test"
        sandbox_dir.mkdir()
        json_out = _make_sandbox_json([{"name": "ts-test", "created_at": "2026-06-02 12:57:25"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert len(sessions) == 1
        assert sessions[0].started_at > 0

    def test_handles_missing_created_at(self, tmp_path):
        sandbox_dir = tmp_path / "no-ts"
        sandbox_dir.mkdir()
        json_out = json.dumps([{"name": "no-ts", "phase": "Ready"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert len(sessions) == 1
        assert sessions[0].started_at == 0

    def test_multiple_sandboxes_sorted(self, tmp_path):
        (tmp_path / "zebra").mkdir()
        (tmp_path / "alpha").mkdir()
        json_out = _make_sandbox_json([{"name": "zebra"}, {"name": "alpha"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert len(sessions) == 2
        assert "alpha" in sessions[0].cwd
        assert "zebra" in sessions[1].cwd

    def test_skips_empty_name(self, tmp_path):
        json_out = json.dumps([{"name": "", "phase": "Ready"}])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_skips_non_dict_items(self, tmp_path):
        json_out = json.dumps(["not-a-dict", 42, None])
        mock_result = MagicMock(returncode=0, stdout=json_out)

        with (
            patch("claude_dashboard.session.SANDBOXES_DIR", tmp_path),
            patch("subprocess.run", return_value=mock_result),
        ):
            sessions = discover_sandbox_sessions()

        assert sessions == []

    def test_os_error(self):
        with patch("subprocess.run", side_effect=OSError("pipe broken")):
            sessions = discover_sandbox_sessions()

        assert sessions == []


class TestSandboxContainerType:
    def test_sandbox_enum_exists(self):
        assert ContainerType.SANDBOX == "Sandbox"
        assert ContainerType.SANDBOX.value == "Sandbox"


class TestSandboxForeground:
    def test_sandbox_uses_code_cli(self):
        from claude_dashboard.platform.linux import foreground_window_linux

        container = ContainerInfo(container_type=ContainerType.SANDBOX)
        mock_result = MagicMock(returncode=0)

        with patch("subprocess.run", return_value=mock_result) as mock_run:
            result = foreground_window_linux(container, cwd="/tmp/sandbox/project")

        assert result is True
        mock_run.assert_called_once()
        args = mock_run.call_args[0][0]
        assert args == ["code", "/tmp/sandbox/project"]

    def test_sandbox_no_cwd_falls_through(self):
        from claude_dashboard.platform.linux import foreground_window_linux

        container = ContainerInfo(container_type=ContainerType.SANDBOX)

        with patch("claude_dashboard.platform.linux._find_window_id_for_session", return_value=0):
            result = foreground_window_linux(container, cwd="")

        assert result is False
