# Generated By: Claude Code (Claude Opus 4.6)
"""Cost history popup — shows daily spending over the last 14 days."""

import datetime
import json
import logging
import tkinter as tk

from claude_dashboard import config

logger = logging.getLogger(__name__)

_DAYS = 14
_BAR_CHAR = "\u2588"  # █
_BAR_MAX_WIDTH = 20


def _read_daily_costs(*, days: int = _DAYS) -> list[tuple[str, float]]:
    """Read daily cost totals for the last N days.

    Returns list of (date_str, cost) tuples, oldest first.
    Days with no data are included as 0.0.
    """
    today = datetime.date.today()
    results = []
    for i in range(days - 1, -1, -1):
        d = today - datetime.timedelta(days=i)
        date_str = d.isoformat()
        day_dir = config.SESSION_TRACKER_DIR / date_str
        total = 0.0
        if day_dir.is_dir():
            for path in day_dir.glob("*.json"):
                try:
                    data = json.loads(path.read_text(encoding="utf-8"))
                    cost = data.get("cost", {}).get("total_cost_usd", 0) or 0
                    prior = data.get("_prior_cost", 0) or 0
                    total += cost - prior
                except (json.JSONDecodeError, OSError):
                    continue
        results.append((date_str, total))
    return results


def _format_table(daily_costs: list[tuple[str, float]]) -> str:
    """Format daily costs as a text table with proportional bars."""
    if not daily_costs:
        return "No cost data available."

    max_cost = max(cost for _, cost in daily_costs)
    period_total = sum(cost for _, cost in daily_costs)
    today = datetime.date.today()

    lines = []
    for date_str, cost in daily_costs:
        d = datetime.date.fromisoformat(date_str)
        day_abbr = d.strftime("%a")
        # Show month-day, highlight today
        label = d.strftime("%m-%d")
        if d == today:
            label = f"{label} *"
        else:
            label = f"{label}  "

        if max_cost > 0 and cost > 0:
            bar_len = max(1, round(cost / max_cost * _BAR_MAX_WIDTH))
        else:
            bar_len = 0
        bar = _BAR_CHAR * bar_len

        lines.append(f"  {day_abbr} {label}  ${cost:7.2f}  {bar}")

    lines.append("")
    lines.append(f"  {_DAYS}-day total: ${period_total:.2f}")

    return "\n".join(lines)


class CostPopup:
    """Dismissable popup showing cost history."""

    def __init__(self, root: tk.Tk, *, anchor_x: int, anchor_y: int):
        daily_costs = _read_daily_costs()
        table_text = _format_table(daily_costs)

        bg = "#1e1e2e"

        self._popup = tk.Toplevel(root, bg=bg)
        self._popup.withdraw()
        self._popup.configure(bg=bg)
        if config.IS_LINUX:
            self._popup.wm_attributes("-type", "dock")
        else:
            self._popup.overrideredirect(True)
        self._popup.wm_attributes("-topmost", True)
        fg = "#cdd6f4"

        frame = tk.Frame(self._popup, bg=bg, padx=12, pady=8)
        frame.pack(fill=tk.BOTH, expand=True)

        header = tk.Label(
            frame,
            text="Daily Cost (14 days)",
            bg=bg,
            fg="#89b4fa",
            font=("monospace", 10, "bold"),
            anchor=tk.W,
        )
        header.pack(fill=tk.X, pady=(0, 4))

        body = tk.Label(
            frame,
            text=table_text,
            bg=bg,
            fg=fg,
            font=("monospace", 9),
            anchor=tk.W,
            justify=tk.LEFT,
        )
        body.pack(fill=tk.X)

        # Position near the anchor point
        self._popup.update_idletasks()
        w = self._popup.winfo_reqwidth()
        h = self._popup.winfo_reqheight()
        sh = root.winfo_screenheight()

        x = anchor_x - w
        if x < 0:
            x = anchor_x
        y = anchor_y
        if y + h > sh:
            y = anchor_y - h

        self._popup.geometry(f"+{x}+{y}")
        self._popup.deiconify()
        self._popup.lift()
        self._popup.focus_force()

    def dismiss(self):
        try:
            self._popup.destroy()
        except tk.TclError:
            pass
