# Generated By: Claude Code (Claude Opus 4.6)
"""Dashboard window — dynamic row grid showing Claude sessions."""

import logging
import tkinter as tk
import tkinter.font as tkfont
from dataclasses import dataclass
from typing import Any, Callable

import io

from PIL import Image

from claude_dashboard import config
from claude_dashboard.tray import generate_icon_image
from claude_dashboard.config import IS_WINDOWS, GitStatus, StatusState
from claude_dashboard.models import SessionRow
from claude_dashboard.platform.base import ContainerInfo, ContainerType
from claude_dashboard.session import SessionInfo, cwd_relative_to_home
from claude_dashboard.settings import Settings

logger = logging.getLogger(__name__)

# Dashboard UI constants — platform-aware font selection
if IS_WINDOWS:
    _FONT_FAMILY = "Segoe UI"
    _FONT_EMOJI_FAMILY = "Segoe UI Emoji"
else:
    _FONT_FAMILY = "Noto Sans"
    _FONT_EMOJI_FAMILY = "Noto Emoji"


def _build_fonts(size: int) -> tuple[tuple, tuple, tuple]:
    """Build (body, emoji, container) font tuples from a base size."""
    return (
        (_FONT_FAMILY, size),
        (_FONT_EMOJI_FAMILY, size + 3),
        (_FONT_FAMILY, max(size - 2, 6)),
    )


_COLOR_EMPTY_FG = "#666666"
_COLOR_CONTAINER_FG = "#888888"
_ROW_PAD_X = 1
_ROW_PAD_Y = 1

# Layout constants (pixel values for padding, margins, and sizing)
_ICON_PADDING = 8  # subtracted from row_height for icon sizing
_ICON_MIN_SIZE = 16  # minimum icon dimension in pixels
_EMOJI_PADDING = 6  # subtracted from row_height for emoji sizing
_EMOJI_MIN_SIZE = 12  # minimum emoji dimension in pixels
_MARGIN_LEFT = 6  # left margin for first element in a row
_MARGIN_RIGHT = 6  # right margin for last element in a row
_ELEMENT_GAP = 2  # horizontal gap between adjacent elements
_USAGE_LABEL_GAP = 4  # gap between usage labels (5h, 7d)
_HIGHLIGHT_THICKNESS = 1  # title bar border thickness
_CLICK_DELAY_MS = 200  # delay before single-click fires (allows double-click)

# Auto-contrast text colors (W3C contrast ratio + warm two-tone)
_TEXT_LIGHT = "#f5f0e8"  # warm white for dark backgrounds
_TEXT_DARK = "#1a1520"  # cool near-black for light backgrounds


@dataclass
class MainWindowCallbacks:
    """Callbacks from the UI to the controller."""

    on_row_left_click: Callable[[SessionInfo], None] | None = None
    on_row_double_click: Callable[[SessionInfo], None] | None = None
    on_row_middle_click: Callable[[SessionInfo], None] | None = None
    on_position_save: Callable[[int, int], None] | None = None
    on_right_click: Callable[[int, int], None] | None = None
    on_row_right_click: Callable[[SessionInfo, int, int], None] | None = None
    on_settings: Callable[[], None] | None = None
    on_restart: Callable[[], None] | None = None
    on_quit: Callable[[], None] | None = None
    on_build_sessions_menu: Callable[[tk.Menu], None] | None = None
    on_open_folder: Callable[[], None] | None = None
    on_cost_click: Callable[[int, int], None] | None = None
    on_ghost_toggle: Callable[[], None] | None = None
    on_width_save: Callable[[int], None] | None = None


def _load_title_emoji(
    *, emoji_img_size: int, bg_hex: str, label_width: int
) -> tk.PhotoImage | None:
    """Load the chef kiss PNG centered in a canvas matching the emoji label width."""
    try:
        if config.TITLE_EMOJI_IMAGE.is_file():
            size = emoji_img_size
            fg = Image.open(config.TITLE_EMOJI_IMAGE).convert("RGBA")
            fg.thumbnail((size, size), Image.Resampling.LANCZOS)
            bg_rgb = config.hex_to_rgb(hex_color=bg_hex)
            canvas = Image.new("RGBA", (label_width, size), bg_rgb + (255,))
            canvas.paste(
                fg,
                ((label_width - fg.width) // 2, (size - fg.height) // 2),
                fg,
            )
            return _pil_to_photoimage(canvas.convert("RGB"))
    except Exception:
        pass
    return None


def _pil_to_photoimage(pil_image: Any) -> tk.PhotoImage:
    """Convert a PIL Image to a Tkinter PhotoImage via PNG buffer."""
    buf = io.BytesIO()
    pil_image.save(buf, format="PNG")
    return tk.PhotoImage(data=buf.getvalue())


def _contrast_text_for_bg(bg_hex: str) -> str:
    """Pick light or dark text color based on W3C contrast ratio against bg."""
    r, g, b = config.hex_to_rgb(hex_color=bg_hex)

    def _srgb_linear(c: int) -> float:
        s = c / 255.0
        return s / 12.92 if s <= 0.03928 else ((s + 0.055) / 1.055) ** 2.4

    luminance = 0.2126 * _srgb_linear(r) + 0.7152 * _srgb_linear(g) + 0.0722 * _srgb_linear(b)
    ratio_light = 1.05 / (luminance + 0.05)
    ratio_dark = (luminance + 0.05) / 0.05
    return _TEXT_LIGHT if ratio_light > ratio_dark else _TEXT_DARK


class MainWindow:
    """Dashboard window with a vertical stack of session rows."""

    def __init__(
        self,
        root: tk.Tk,
        settings: Settings,
        *,
        callbacks: MainWindowCallbacks | None = None,
    ):
        cb = callbacks or MainWindowCallbacks()
        self._root = root
        self._settings = settings
        self._on_row_left_click = cb.on_row_left_click
        self._on_row_double_click = cb.on_row_double_click
        self._on_row_middle_click = cb.on_row_middle_click
        self._on_position_save = cb.on_position_save
        self._on_right_click = cb.on_right_click
        self._on_row_right_click = cb.on_row_right_click
        self._on_settings = cb.on_settings
        self._on_restart = cb.on_restart
        self._on_quit = cb.on_quit
        self._on_build_sessions_menu = cb.on_build_sessions_menu
        self._on_open_folder = cb.on_open_folder
        self._on_cost_click = cb.on_cost_click
        self._on_ghost_toggle = cb.on_ghost_toggle
        self._on_width_save = cb.on_width_save
        self._cost_popup: Any = None
        self._font_body, self._font_emoji, self._font_container = _build_fonts(settings.font_size)
        self._rows: dict[int, dict[str, Any]] = {}
        self._row_order: list[int] = []
        self._drag_start_x = 0
        self._drag_start_y = 0
        self._dragged = False  # True if mouse moved significantly since button-down
        self._resize_start_x_root = 0
        self._resize_start_width = 0
        self._double_clicked_pid: int | None = None  # PID of row being double-clicked
        self._pending_click_id: str | None = None  # Pending after() id for delayed single-click
        self._pending_click_pid: int | None = None  # PID associated with pending click
        self._force_resize = False
        self._shaded = False
        self._last_highest_state_color: str = ""
        self._icon_cache: dict[tuple, tk.PhotoImage] = {}
        self._emoji_image_cache: dict[tuple, tk.PhotoImage] = {}
        self._icon_size = _ICON_MIN_SIZE  # updated by _update_icon_size()
        self._emoji_img_size = _EMOJI_MIN_SIZE  # updated by _update_icon_size()
        # Tracked position.  winfo_x/winfo_y can return stale or
        # DPI-mismatched values (Wayland compositors, Windows DPI scaling).
        # We track position ourselves and update on every geometry() call.
        self._tracked_x: int | None = None
        self._tracked_y: int | None = None
        self._grow_up_bottom_y: int | None = None

        # Create the window shell — apply_settings handles all configuration
        self._window = tk.Toplevel(root)
        if config.IS_LINUX:
            # Wayland compositors (Mutter/GNOME 46+) don't render
            # overrideredirect X windows.  'dock' type removes decorations
            # and keeps the window visible on all workspaces.
            self._window.wm_attributes("-type", "dock")
        else:
            self._window.overrideredirect(True)

        self._frame = tk.Frame(self._window)
        self._frame.pack(fill=tk.BOTH, expand=True)

        # Compute icon sizes from font metrics before building the UI
        self._update_icon_size()

        # Title bar — at bottom when grow_up (anchor point), at top otherwise
        self._title_bar = self._create_title_bar()

        # Title bar right-click context menu
        self._title_menu = tk.Menu(self._root, tearoff=0)

        self._empty_label = tk.Label(
            self._frame,
            text="No visible Claude sessions",
            fg=_COLOR_EMPTY_FG,
            font=self._font_body,
        )
        self._empty_label.pack(pady=10)

        # Bindings
        self._window.bind("<Button-3>", self._on_right_click_event)

        # Apply all settings (position, size, colors, topmost)
        self.apply_settings(settings, restore_position=True)

    # ------------------------------------------------------------------
    # Geometry helpers — track position on every geometry() call
    # ------------------------------------------------------------------

    def _set_geometry(self, geom: str):
        """Set window geometry and update tracked x/y from the geometry string."""
        self._window.geometry(geom)
        # Parse +x+y from geometry string (formats: WxH+X+Y or +X+Y)
        parts = geom.split("+")
        if len(parts) >= 3:
            try:
                self._tracked_x = int(parts[-2])
                self._tracked_y = int(parts[-1])
            except ValueError:
                pass

    # ------------------------------------------------------------------
    # Icon sizing — derived from rendered font metrics so images scale
    # with both font_size and platform DPI.
    # ------------------------------------------------------------------

    def _update_icon_size(self):
        """Recompute icon sizes from the current body font's rendered height."""
        font_obj = tkfont.Font(font=self._font_body)
        line_height = font_obj.metrics("linespace")
        self._icon_size = max(line_height, _ICON_MIN_SIZE)
        self._emoji_img_size = max(line_height, _EMOJI_MIN_SIZE)

    # ------------------------------------------------------------------
    # Title bar
    # ------------------------------------------------------------------

    def _create_title_bar(self) -> tk.Frame:
        """Create the faux title bar row at the top of the dashboard."""
        self._title_bg = config.DEFAULT_COLOR_UNATTACHED
        self._title_fg = _contrast_text_for_bg(self._title_bg)
        bg = self._title_bg
        fg = self._title_fg

        frame = tk.Frame(
            self._frame,
            bg=bg,
            height=self._settings.row_height,
            cursor="hand2",
            highlightbackground="#555555",
            highlightthickness=_HIGHLIGHT_THICKNESS,
        )
        if self._settings.grow_up:
            frame.pack(side=tk.BOTTOM, fill=tk.X, padx=_ROW_PAD_X, pady=_ROW_PAD_Y)
        else:
            frame.pack(fill=tk.X, padx=_ROW_PAD_X, pady=_ROW_PAD_Y)
        frame.pack_propagate(False)

        # Left side: eye icon (hardcoded ready green), emoji, title text
        icon_size = self._icon_size
        icon_rgb = config.hex_to_rgb(hex_color=config.DEFAULT_COLOR_READY)
        self._title_icon_image = _pil_to_photoimage(
            generate_icon_image(color=icon_rgb).resize((icon_size, icon_size))
        )
        self._title_icon = tk.Label(
            frame,
            image=self._title_icon_image,
            bg=bg,
            anchor=tk.CENTER,
        )
        self._title_icon.pack(side=tk.LEFT, padx=(_MARGIN_LEFT, 0))

        # Measure the emoji label width so the image label matches it exactly
        probe = tk.Label(frame, text="XX", font=self._font_emoji, width=2)
        frame.update_idletasks()
        emoji_label_width = probe.winfo_reqwidth()
        probe.destroy()

        self._emoji_label_width = emoji_label_width
        self._title_emoji_image = _load_title_emoji(
            emoji_img_size=self._emoji_img_size,
            bg_hex=self._title_bg,
            label_width=emoji_label_width,
        )
        if self._title_emoji_image:
            self._title_emoji_label = tk.Label(
                frame,
                image=self._title_emoji_image,
                bg=bg,
                borderwidth=0,
                padx=0,
                pady=0,
            )
        else:
            self._title_emoji_label = tk.Label(
                frame,
                text=config.TITLE_EMOJI,
                bg=bg,
                fg=fg,
                font=self._font_emoji,
                width=2,
                anchor=tk.CENTER,
            )
        self._title_emoji_label.pack(side=tk.LEFT, padx=(0, _ELEMENT_GAP))

        self._title_text_label = tk.Label(
            frame,
            text=config.TITLE_TEXT,
            bg=bg,
            fg=fg,
            font=self._font_body,
            anchor=tk.W,
        )
        self._title_text_label.pack(side=tk.LEFT, padx=(_ELEMENT_GAP, 0))

        # Right side (pack order: daily cost first, then 7d, then 5h — rightmost first)
        self._title_cost_label = tk.Label(
            frame,
            text="",
            bg=bg,
            fg=fg,
            font=self._font_body,
            anchor=tk.E,
        )
        self._title_cost_label.pack(side=tk.RIGHT, padx=(0, _MARGIN_RIGHT))

        self._title_7d_label = tk.Label(
            frame,
            text="",
            bg=bg,
            fg=fg,
            font=self._font_body,
            anchor=tk.E,
        )
        self._title_7d_label.pack(side=tk.RIGHT, padx=(0, _USAGE_LABEL_GAP))

        self._title_5h_label = tk.Label(
            frame,
            text="",
            bg=bg,
            fg=fg,
            font=self._font_body,
            anchor=tk.E,
        )
        self._title_5h_label.pack(side=tk.RIGHT, padx=(0, _USAGE_LABEL_GAP))

        # Bind drag (window move) on non-cost title bar widgets
        move_widgets = [
            frame,
            self._title_icon,
            self._title_emoji_label,
            self._title_text_label,
        ]
        for w in move_widgets:
            w.bind("<Button-1>", self._on_drag_start)
            w.bind("<B1-Motion>", self._on_drag_motion)
            w.bind("<Button-3>", self._on_title_bar_right_click)

        # Title text/icon/frame: left-click toggles shade, middle-click toggles ghosts
        shade_widgets = [frame, self._title_icon, self._title_emoji_label, self._title_text_label]
        for w in shade_widgets:
            w.bind("<ButtonRelease-1>", self._on_shade_toggle)
            w.bind("<Button-2>", self._on_ghost_toggle_click)

        # Cost/usage labels: drag to resize width, click for cost popup
        cost_widgets = [self._title_cost_label, self._title_7d_label, self._title_5h_label]
        for w in cost_widgets:
            w.configure(cursor="sb_h_double_arrow")
            w.bind("<Button-1>", self._on_resize_start)
            w.bind("<B1-Motion>", self._on_resize_motion)
            w.bind("<ButtonRelease-1>", self._on_resize_end)
            w.bind("<Button-3>", self._on_title_bar_right_click)
            w.bind("<Leave>", self._on_cost_label_leave)

        return frame

    def _on_shade_toggle(self, event: Any):
        """Left-click on title text — toggle window shade (collapse/expand rows)."""
        if self._dragged:
            return
        self._shaded = not self._shaded
        self._apply_shade_state()

    def _apply_shade_state(self):
        """Apply shade/unshade: update title bar, pack/unpack rows, recalculate geometry."""
        self._apply_title_bar_style()
        if self._shaded:
            for row_data in self._rows.values():
                row_data["frame"].pack_forget()
            self._empty_label.pack_forget()
        else:
            for pid in self._row_order:
                if pid in self._rows:
                    self._rows[pid]["frame"].pack(fill=tk.X, padx=_ROW_PAD_X, pady=_ROW_PAD_Y)
            if not self._rows:
                self._empty_label.pack(pady=10)
        self._apply_geometry(row_count=len(self._rows))

    def _apply_title_bar_style(self):
        """Apply title bar bg/fg/icon based on current shade state and last known priority."""
        color = self._last_highest_state_color
        # When shaded, suppress "ready" — only show states requiring user action
        if color and color.lower() == self._settings.color_ready.lower():
            color = ""
        if self._shaded and color:
            self._title_bg = color
        else:
            self._title_bg = config.DEFAULT_COLOR_UNATTACHED
        self._title_fg = _contrast_text_for_bg(self._title_bg)
        bg = self._title_bg
        fg = self._title_fg

        for w in [
            self._title_bar,
            self._title_icon,
            self._title_emoji_label,
            self._title_text_label,
            self._title_cost_label,
            self._title_7d_label,
            self._title_5h_label,
        ]:
            try:
                w["background"] = bg
            except tk.TclError:
                pass

        self._title_text_label.configure(fg=fg)
        self._title_cost_label.configure(fg=fg)
        self._title_5h_label.configure(fg=fg)
        self._title_7d_label.configure(fg=fg)

        # Eye icon: hidden when shaded, always green when expanded
        icon_size = self._icon_size
        if self._shaded:
            blank = Image.new("RGBA", (icon_size, icon_size), (0, 0, 0, 0))
            self._title_icon_image = _pil_to_photoimage(blank)
        else:
            icon_rgb = config.hex_to_rgb(hex_color=config.DEFAULT_COLOR_READY)
            self._title_icon_image = _pil_to_photoimage(
                generate_icon_image(color=icon_rgb).resize((icon_size, icon_size))
            )
        self._title_icon.configure(image=self._title_icon_image)

        # Update emoji image bg if using PNG
        if self._title_emoji_image:
            new_emoji_image = _load_title_emoji(
                emoji_img_size=self._emoji_img_size,
                bg_hex=bg,
                label_width=self._emoji_label_width,
            )
            if new_emoji_image:
                self._title_emoji_image = new_emoji_image
                self._title_emoji_label.configure(image=self._title_emoji_image)

    def _apply_geometry(self, *, row_count: int):
        """Single geometry calculation used by shade, unshade, and update_sessions.

        Computes window height from *row_count*, reads x/y from tracked
        position (never stale winfo), and sets the geometry.
        """
        self._window.update_idletasks()
        title_bar_height = self._settings.row_height + _ROW_PAD_Y * 2
        if self._shaded:
            new_height = title_bar_height
        elif row_count > 0:
            new_height = title_bar_height + row_count * (self._settings.row_height + _ROW_PAD_Y * 2)
        else:
            new_height = title_bar_height + self._settings.row_height + _ROW_PAD_Y * 2

        x = self._tracked_x if self._tracked_x is not None else self._window.winfo_x()
        if self._settings.grow_up and self._grow_up_bottom_y is not None:
            y = self._grow_up_bottom_y - new_height
        else:
            old_height = self._window.winfo_height()
            y = self._tracked_y if self._tracked_y is not None else self._window.winfo_y()
            if self._settings.grow_up and old_height > 0:
                y = y + old_height - new_height

        geom = f"{self._settings.row_width}x{new_height}+{x}+{y}"
        if logger.isEnabledFor(logging.DEBUG):
            logger.debug(
                "apply_geometry: shaded=%s rows=%d tracked=(%s,%s) bottom=%s"
                " new_h=%d y=%d geom=%s",
                self._shaded,
                row_count,
                self._tracked_x,
                self._tracked_y,
                self._grow_up_bottom_y,
                new_height,
                y,
                geom,
            )
        self._set_geometry(geom)
        if self._settings.grow_up:
            self._window.update_idletasks()
            self._grow_up_bottom_y = y + new_height
            # Detect compositor drift (Wayland may reposition dock windows)
            actual_x = self._window.winfo_x()
            actual_y = self._window.winfo_y()
            if actual_x != x or actual_y != y:
                logger.warning(
                    "apply_geometry: compositor drift detected:"
                    " requested=(%d,%d) actual=(%d,%d)",
                    x,
                    y,
                    actual_x,
                    actual_y,
                )

    def _on_ghost_toggle_click(self, event: Any):
        """Middle-click on title bar — toggle ghost session visibility."""
        if self._on_ghost_toggle:
            self._on_ghost_toggle()
        if self._shaded:
            self._shaded = False
            self._apply_shade_state()

    def _on_cost_label_leave(self, event: Any):
        """Mouse left the cost label area — dismiss any open cost popup."""
        if self._cost_popup is not None:
            self._cost_popup.dismiss()
            self._cost_popup = None

    def _on_title_bar_right_click(self, event: Any):
        """Show Sessions submenu + Settings / Restart / Quit on title bar right-click."""
        self._title_menu.delete(0, tk.END)

        # Sessions submenu with visibility checkboxes
        sessions_submenu = tk.Menu(self._title_menu, tearoff=0)
        if self._on_build_sessions_menu:
            self._on_build_sessions_menu(sessions_submenu)
        self._title_menu.add_cascade(label="Sessions", menu=sessions_submenu)

        self._title_menu.add_separator()
        self._title_menu.add_command(
            label="Open...",
            command=self._on_open_folder if self._on_open_folder else lambda: None,
        )
        self._title_menu.add_separator()
        self._title_menu.add_command(
            label="Settings",
            command=self._on_settings if self._on_settings else lambda: None,
        )
        self._title_menu.add_command(
            label="Restart",
            command=self._on_restart if self._on_restart else lambda: None,
        )
        self._title_menu.add_command(
            label="Quit",
            command=self._on_quit if self._on_quit else lambda: None,
        )
        self._title_menu.tk_popup(event.x_root, event.y_root)
        return "break"

    def update_title_bar(
        self,
        *,
        daily_cost: float,
        limits: dict,
        hidden_live: int = 0,
        hidden_ghost: int = 0,
        highest_state_color: str = "",
    ):
        """Update the title bar with current cost, limit data, and state icon."""
        self._last_highest_state_color = highest_state_color
        self._apply_title_bar_style()
        fg = self._title_fg

        suffix = ""
        if hidden_live > 0:
            suffix += f" (+{hidden_live})"
        if hidden_ghost > 0:
            suffix += f" [+{hidden_ghost}]"
        self._title_text_label.configure(text=f"{config.TITLE_TEXT}{suffix}")

        # Right-side info
        cost_text = f"${daily_cost:.2f}" if daily_cost > 0 else ""
        self._title_cost_label.configure(text=cost_text, fg=fg)

        five_hour = limits.get("five_hour", {})
        seven_day = limits.get("seven_day", {})

        five_util = five_hour.get("utilization") if isinstance(five_hour, dict) else None
        seven_util = seven_day.get("utilization") if isinstance(seven_day, dict) else None

        self._title_5h_label.configure(
            text=f"5h: {five_util:.0f}%" if five_util is not None else "",
            fg=fg,
        )
        self._title_7d_label.configure(
            text=f"7d: {seven_util:.0f}%" if seven_util is not None else "",
            fg=fg,
        )

        # Update title bar height
        try:
            self._title_bar.configure(height=self._settings.row_height)
        except tk.TclError:
            pass

    # ------------------------------------------------------------------
    # Settings — single path for all configuration
    # ------------------------------------------------------------------

    def apply_settings(self, settings: Settings, *, restore_position: bool = False):
        """Apply settings to the window. Does NOT change position unless restore_position=True."""
        self._settings = settings
        self._font_body, self._font_emoji, self._font_container = _build_fonts(settings.font_size)
        self._update_icon_size()
        self._force_resize = True
        self._icon_cache.clear()
        self._emoji_image_cache.clear()

        # Update title bar emoji (image or font)
        new_emoji_image = _load_title_emoji(
            emoji_img_size=self._emoji_img_size,
            bg_hex=self._title_bg,
            label_width=self._emoji_label_width,
        )
        if new_emoji_image:
            self._title_emoji_image = new_emoji_image
            self._title_emoji_label.configure(image=self._title_emoji_image)
        else:
            self._title_emoji_label.configure(font=self._font_emoji)
        self._title_text_label.configure(font=self._font_body)
        self._title_cost_label.configure(font=self._font_body)
        self._title_7d_label.configure(font=self._font_body)
        self._title_5h_label.configure(font=self._font_body)

        # Window attributes
        self._window.wm_attributes("-topmost", bool(settings.always_on_top))
        self._window.configure(bg=settings.window_bg)
        self._frame.configure(bg=settings.window_bg)
        self._empty_label.configure(bg=settings.window_bg, font=self._font_body)

        # Position — only on initial startup, not on settings changes
        if restore_position:
            x = settings.window_x
            y = settings.window_y
            if x is not None and y is not None:
                # Sanity check: discard positions entirely off-screen
                # (e.g., from a disconnected monitor). Don't clamp to
                # edges — that shifts the window on every restart.
                screen_w = self._root.winfo_screenwidth()
                screen_h = self._root.winfo_screenheight()
                if x < -screen_w or x > 2 * screen_w or y < -screen_h or y > 2 * screen_h:
                    x, y = 0, 0
                if settings.grow_up:
                    # y is the saved bottom edge — will be adjusted in
                    # update_sessions once we know the actual height
                    self._grow_up_bottom_y = y
                    logger.debug(
                        "grow_up: apply_settings tracked_bottom=%d x=%d y=%d",
                        y,
                        x,
                        y,
                    )
                self._set_geometry(f"{settings.row_width}x1+{x}+{y}")
            else:
                self._window.geometry(f"{settings.row_width}x1")

    # ------------------------------------------------------------------
    # Window visibility
    # ------------------------------------------------------------------

    def show(self):
        self._window.deiconify()

    def hide(self):
        self._save_position()
        self._window.withdraw()

    @property
    def toplevel(self) -> tk.Toplevel:
        return self._window

    def get_position(self) -> tuple[int | None, int | None]:
        """Return the window position to save.

        When grow_up is enabled, saves the bottom edge y-coordinate
        so the bottom stays anchored across restarts with different
        session counts.

        Returns (None, None) if the window reports nonsensical values
        (e.g. Wayland returning 0,0 for overrideredirect windows) to
        avoid corrupting the saved position.
        """
        try:
            x = self._tracked_x if self._tracked_x is not None else self._window.winfo_x()
            y = self._tracked_y if self._tracked_y is not None else self._window.winfo_y()
            h = self._window.winfo_height()
            # Reject bogus geometry: a 1px-tall window at origin means the
            # compositor isn't reporting real values (common on Wayland).
            if x == 0 and y == 0 and h <= 1:
                return None, None
            if self._settings.grow_up:
                # Prefer tracked bottom edge over winfo (Wayland may be stale)
                if self._grow_up_bottom_y is not None:
                    y = self._grow_up_bottom_y
                else:
                    y = y + h
            return x, y
        except tk.TclError:
            return None, None

    # ------------------------------------------------------------------
    # Drag (borderless window)
    # ------------------------------------------------------------------

    _DRAG_THRESHOLD = 5  # pixels of movement before it counts as a drag

    def _on_drag_start(self, event: Any):
        self._drag_start_x = event.x
        self._drag_start_y = event.y
        self._dragged = False
        if self._settings.grow_up:
            self._drag_start_height = self._window.winfo_height()

    def _on_drag_motion(self, event: Any):
        dx = abs(event.x - self._drag_start_x)
        dy = abs(event.y - self._drag_start_y)
        if dx > self._DRAG_THRESHOLD or dy > self._DRAG_THRESHOLD:
            self._dragged = True
        if self._dragged:
            x = self._window.winfo_x() + event.x - self._drag_start_x
            y = self._window.winfo_y() + event.y - self._drag_start_y
            self._set_geometry(f"+{x}+{y}")
            if self._settings.grow_up:
                self._grow_up_bottom_y = y + self._drag_start_height
                # Guard: fires on every drag pixel
                if logger.isEnabledFor(logging.DEBUG):
                    logger.debug(
                        "grow_up: drag tracked_bottom=%d y=%d h=%d",
                        self._grow_up_bottom_y,
                        y,
                        self._drag_start_height,
                    )

    # ------------------------------------------------------------------
    # Horizontal resize via cost labels
    # ------------------------------------------------------------------

    _MIN_WIDTH = 150

    def _on_resize_start(self, event: Any):
        self._resize_start_x_root = event.x_root
        self._resize_start_width = self._settings.row_width
        self._dragged = False
        return "break"

    def _on_resize_motion(self, event: Any):
        dx = event.x_root - self._resize_start_x_root
        if abs(dx) > self._DRAG_THRESHOLD:
            self._dragged = True
        if self._dragged:
            new_width = max(self._MIN_WIDTH, self._resize_start_width + dx)
            self._settings.row_width = new_width
            x = self._tracked_x if self._tracked_x is not None else self._window.winfo_x()
            y = self._tracked_y if self._tracked_y is not None else self._window.winfo_y()
            h = self._window.winfo_height()
            self._set_geometry(f"{new_width}x{h}+{x}+{y}")
        return "break"

    def _on_resize_end(self, event: Any):
        if self._dragged:
            if self._on_width_save:
                self._on_width_save(self._settings.row_width)
        else:
            if self._on_cost_click:
                self._on_cost_click(event.x_root, event.y_root)
        return "break"

    # ------------------------------------------------------------------
    # Right-click context menu
    # ------------------------------------------------------------------

    def _on_right_click_event(self, event: Any):
        if self._on_right_click:
            self._on_right_click(event.x_root, event.y_root)
        return "break"

    # ------------------------------------------------------------------
    # Position persistence
    # ------------------------------------------------------------------

    def _save_position(self):
        if self._on_position_save:
            x, y = self.get_position()
            if x is not None and y is not None:
                self._on_position_save(x, y)

    # ------------------------------------------------------------------
    # Session rows
    # ------------------------------------------------------------------

    def update_sessions(self, sessions: list[SessionRow]):
        # When shaded, track rows silently but don't touch geometry or visibility
        if self._shaded:
            current_pids = {row.session.pid for row in sessions}
            for pid in set(self._rows.keys()) - current_pids:
                self._remove_row(pid)
            for row in sessions:
                if row.session.pid in self._rows:
                    self._update_row(row)
                else:
                    self._add_row(row)
                    self._rows[row.session.pid]["frame"].pack_forget()
            self._row_order = [row.session.pid for row in sessions]
            return

        current_pids = {row.session.pid for row in sessions}

        # Detect changes that affect geometry
        stale_pids = set(self._rows.keys()) - current_pids
        new_pids = {r.session.pid for r in sessions} - set(self._rows.keys())
        desired_order = [row.session.pid for row in sessions]
        geometry_changed = bool(stale_pids or new_pids) or desired_order != self._row_order

        # Pre-set geometry BEFORE packing to prevent Wayland compositor
        # from repositioning the dock window during intermediate auto-resize.
        # Row packing triggers geometry negotiation; on secondary monitors
        # the compositor may snap the window to the primary monitor if it
        # sees a large transient resize before the final geometry is applied.
        if geometry_changed or self._force_resize:
            self._force_resize = False
            self._apply_geometry(row_count=len(sessions))

        # Remove stale rows
        for pid in stale_pids:
            self._remove_row(pid)

        # Add or update rows
        for row in sessions:
            if row.session.pid in self._rows:
                self._update_row(row)
            else:
                self._add_row(row)

        # Re-order rows only if the order changed
        if desired_order != self._row_order:
            for sr in sessions:
                row_data = self._rows.get(sr.session.pid)
                if row_data:
                    row_data["frame"].pack_forget()
                    row_data["frame"].pack(fill=tk.X, padx=_ROW_PAD_X, pady=_ROW_PAD_Y)
            self._row_order = desired_order

        # Empty state label
        if sessions:
            self._empty_label.pack_forget()
        else:
            self._empty_label.pack(pady=10)

    def _color_for_state(self, state: StatusState) -> str:
        return {
            StatusState.WORKING: self._settings.color_working,
            StatusState.READY: self._settings.color_ready,
            StatusState.IDLE: self._settings.color_idle,
            StatusState.AWAITING_INPUT: self._settings.color_awaiting_input,
            StatusState.PERMISSION_REQUIRED: self._settings.color_permission_required,
        }.get(state, self._settings.color_idle)

    def _container_label(self, container: ContainerInfo | None) -> str:
        if not container or container.container_type == ContainerType.UNKNOWN:
            return ""
        return {
            ContainerType.VSCODE: "VS Code",
            ContainerType.TERMINAL: "Term",
            ContainerType.GITBASH: "Git Bash",
            ContainerType.SCREEN: "screen",
        }.get(container.container_type, container.container_type.value)

    def _cwd_display(self, cwd: str, *, agent_count: int = 0) -> str:
        display = cwd_relative_to_home(cwd=cwd).replace("git-worktrees/", ".../")
        if agent_count > 0:
            display += f" (+{agent_count})"
        return display

    @staticmethod
    def _branch_display(branch: str) -> str:
        return f"[{branch}]" if branch else ""

    @staticmethod
    def _branch_color(*, merged: bool, fg: str) -> str:
        if merged:
            return config.DEFAULT_COLOR_BRANCH_MERGED
        return fg

    def _emoji_image(self, state: StatusState | None, *, bg_hex: str) -> tk.PhotoImage:
        """Return a cached emoji image for the given state, composited on bg."""
        png_path = config.EMOJI_IMAGES[state]
        cache_key = (state, bg_hex, self._emoji_img_size, self._emoji_label_width)
        cached = self._emoji_image_cache.get(cache_key)
        if cached is not None:
            return cached
        size = self._emoji_img_size
        label_width = self._emoji_label_width
        fg = Image.open(png_path).convert("RGBA")
        fg.thumbnail((size, size), Image.Resampling.LANCZOS)
        bg_rgb = config.hex_to_rgb(hex_color=bg_hex)
        canvas = Image.new("RGBA", (label_width, size), bg_rgb + (255,))
        canvas.paste(
            fg,
            ((label_width - fg.width) // 2, (size - fg.height) // 2),
            fg,
        )
        img = _pil_to_photoimage(canvas.convert("RGB"))
        self._emoji_image_cache[cache_key] = img
        return img

    def _flag_icon(self, row: SessionRow) -> tk.PhotoImage:
        """Generate an eye icon for git status + manual flag, or transparent if clean."""
        icon_size = self._icon_size
        eye_color = self._git_status_color(row)
        pupil_color_hex = self._settings.color_flag_manual if row.flagged else None

        cache_key = (eye_color, pupil_color_hex, icon_size)
        cached = self._icon_cache.get(cache_key)
        if cached is not None:
            return cached

        if eye_color is None and pupil_color_hex is None:
            # No git status, no flag — transparent placeholder
            blank = Image.new("RGBA", (icon_size, icon_size), (0, 0, 0, 0))
            result = _pil_to_photoimage(blank)
        else:
            # Eye outer = git status, pupil = manual flag
            # If only flagged (no git status), use neutral gray eye with flag-colored pupil
            eye_rgb = config.hex_to_rgb(hex_color=eye_color) if eye_color else (90, 90, 90)

            if pupil_color_hex is not None:
                img = generate_icon_image(
                    color=eye_rgb, pupil_color=config.hex_to_rgb(hex_color=pupil_color_hex)
                )
            else:
                img = generate_icon_image(color=eye_rgb)
            result = _pil_to_photoimage(img.resize((icon_size, icon_size)))

        self._icon_cache[cache_key] = result
        return result

    def _git_status_color(self, row: SessionRow) -> str | None:
        """Return color for git working tree status (excludes manual flag)."""
        if row.git_status == GitStatus.UNSTAGED_CHANGES:
            return self._settings.color_flag_unstaged
        if row.git_status == GitStatus.STAGED_UNCOMMITTED:
            return self._settings.color_flag_staged
        if row.git_status == GitStatus.COMMITTED_NOT_PUSHED:
            return self._settings.color_flag_unpushed
        if row.git_status == GitStatus.PUSHED_NOT_MERGED:
            return self._settings.color_flag_unmerged
        return None

    def _add_row(self, row: SessionRow):
        session = row.session
        state = row.state
        container = row.container

        if row.unattached:
            bg = self._settings.color_unattached
            fg = _COLOR_CONTAINER_FG  # dim text for ghosts
            emoji_state: StatusState | None = None  # unattached
            container_text = ""
        else:
            bg = self._color_for_state(state)
            fg = _contrast_text_for_bg(bg)
            emoji_state = state
            container_text = self._container_label(container)

        row_frame = tk.Frame(self._frame, bg=bg, height=self._settings.row_height, cursor="hand2")
        row_frame.pack(fill=tk.X, padx=_ROW_PAD_X, pady=_ROW_PAD_Y)
        row_frame.pack_propagate(False)

        # Pack LEFT: flag eye icon → emoji (visual indicators grouped together)
        flag_image = self._flag_icon(row)
        flag_label = tk.Label(
            row_frame,
            image=flag_image,
            bg=bg,
            anchor=tk.CENTER,
        )
        flag_label.pack(side=tk.LEFT, padx=(_MARGIN_LEFT, 0))

        emoji_image = self._emoji_image(emoji_state, bg_hex=bg)
        status_label = tk.Label(
            row_frame,
            image=emoji_image,
            bg=bg,
            borderwidth=0,
            padx=0,
            pady=0,
        )
        status_label.pack(side=tk.LEFT, padx=(0, _ELEMENT_GAP))

        # Pack RIGHT: container label
        container_var = tk.StringVar(value=container_text)
        container_label = tk.Label(
            row_frame,
            textvariable=container_var,
            bg=bg,
            fg=_COLOR_CONTAINER_FG,
            font=self._font_container,
            anchor=tk.E,
        )
        container_label.pack(side=tk.RIGHT, padx=(0, _MARGIN_RIGHT))

        cwd_var = tk.StringVar(value=self._cwd_display(session.cwd, agent_count=row.agent_count))
        cwd_label = tk.Label(
            row_frame,
            textvariable=cwd_var,
            bg=bg,
            fg=fg,
            font=self._font_body,
            anchor=tk.W,
        )
        cwd_label.pack(side=tk.LEFT, padx=(_ELEMENT_GAP, 0))

        branch_var = tk.StringVar(value=self._branch_display(row.branch))
        branch_fg = self._branch_color(merged=row.merged, fg=fg)
        branch_label = tk.Label(
            row_frame,
            textvariable=branch_var,
            bg=bg,
            fg=branch_fg,
            font=self._font_body,
            anchor=tk.W,
        )
        branch_label.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(_ELEMENT_GAP, 0))

        # Click and right-click bindings on all widgets
        widgets = [row_frame, status_label, cwd_label, branch_label, container_label, flag_label]

        def make_click(s: SessionInfo = session):
            def handler(event: Any):
                if self._double_clicked_pid == s.pid:
                    self._double_clicked_pid = None
                    return
                if self._on_row_left_click:
                    # Delay single-click so double-click can suppress it.
                    # On Linux, <ButtonRelease-1> fires before <Double-1>,
                    # so without a delay the single-click runs first.
                    def deferred_click(session: SessionInfo = s):
                        self._pending_click_id = None
                        self._pending_click_pid = None
                        if self._double_clicked_pid != session.pid and self._on_row_left_click:
                            self._on_row_left_click(session)
                        self._double_clicked_pid = None

                    self._pending_click_id = self._window.after(_CLICK_DELAY_MS, deferred_click)
                    self._pending_click_pid = s.pid

            return handler

        def make_double_click(s: SessionInfo = session):
            def handler(event: Any):
                self._double_clicked_pid = s.pid
                if self._pending_click_id is not None:
                    self._window.after_cancel(self._pending_click_id)
                    self._pending_click_id = None
                    self._pending_click_pid = None
                if self._on_row_double_click:
                    self._on_row_double_click(s)
                return "break"

            return handler

        def make_middle_click(s: SessionInfo = session):
            def handler(event: Any):
                if self._on_row_middle_click:
                    self._on_row_middle_click(s)

            return handler

        def make_right_click(s: SessionInfo = session):
            def handler(event: Any):
                if self._on_row_right_click:
                    self._on_row_right_click(s, event.x_root, event.y_root)
                return "break"

            return handler

        click = make_click()
        dbl_click = make_double_click()
        mid_click = make_middle_click()
        right_click = make_right_click()
        for w in widgets:
            w.bind("<ButtonRelease-1>", click)
            w.bind("<Double-1>", dbl_click)
            w.bind("<Button-2>", mid_click)
            w.bind("<Button-3>", right_click)

        self._rows[session.pid] = {
            "frame": row_frame,
            "status_image": emoji_image,
            "cwd_var": cwd_var,
            "branch_var": branch_var,
            "container_var": container_var,
            "status_label": status_label,
            "cwd_label": cwd_label,
            "branch_label": branch_label,
            "container_label": container_label,
            "flag_label": flag_label,
            "flag_image": flag_image,
        }

    def _update_row(self, row_data: SessionRow):
        row = self._rows[row_data.session.pid]

        if row_data.unattached:
            bg = self._settings.color_unattached
            fg = _COLOR_CONTAINER_FG
            emoji_state: StatusState | None = None
            container_text = ""
        else:
            bg = self._color_for_state(row_data.state)
            fg = _contrast_text_for_bg(bg)
            emoji_state = row_data.state
            container_text = self._container_label(row_data.container)

        emoji_image = self._emoji_image(emoji_state, bg_hex=bg)
        row["status_image"] = emoji_image  # prevent GC
        row["status_label"].configure(image=emoji_image)
        row["cwd_var"].set(
            self._cwd_display(row_data.session.cwd, agent_count=row_data.agent_count)
        )
        row["branch_var"].set(self._branch_display(row_data.branch))
        row["container_var"].set(container_text)
        row["cwd_label"].configure(fg=fg, font=self._font_body)
        row["branch_label"].configure(
            fg=self._branch_color(merged=row_data.merged, fg=fg), font=self._font_body
        )
        row["container_label"].configure(font=self._font_container)
        flag_image = self._flag_icon(row_data)
        row["flag_image"] = flag_image  # prevent GC
        row["flag_label"].configure(image=flag_image, bg=bg)

        # Update row height if settings changed
        try:
            row["frame"].configure(height=self._settings.row_height)
        except tk.TclError:
            pass

        for key in (
            "frame",
            "status_label",
            "cwd_label",
            "branch_label",
            "container_label",
            "flag_label",
        ):
            try:
                row[key].configure(bg=bg)
            except tk.TclError:
                pass

    def _remove_row(self, pid: int):
        if self._pending_click_pid == pid and self._pending_click_id is not None:
            self._window.after_cancel(self._pending_click_id)
            self._pending_click_id = None
            self._pending_click_pid = None
        row = self._rows.pop(pid, None)
        if row and row["frame"]:
            row["frame"].destroy()
