# Generated By: Claude Code (Claude Opus 4.6)
"""One-off diagnostic: check dbus window list for VS Code matching logic."""

import json
import subprocess
import sys


def main():
    result = subprocess.run(
        [
            "gdbus",
            "call",
            "--session",
            "--dest",
            "org.gnome.Shell",
            "--object-path",
            "/org/gnome/Shell/Extensions/Windows",
            "--method",
            "org.gnome.Shell.Extensions.Windows.List",
        ],
        capture_output=True,
        text=True,
        timeout=3,
    )
    if result.returncode != 0:
        print(f"dbus call failed: {result.stderr.strip()}")
        sys.exit(1)

    raw = result.stdout.strip()
    if raw.startswith("('") and raw.endswith("',)"):
        json_str = raw[2:-3]
    elif raw.startswith("('") and raw.endswith("')"):
        json_str = raw[2:-2]
    else:
        print(f"unexpected format: {raw[:100]}")
        sys.exit(1)

    windows = json.loads(json_str)

    print(f"Total windows: {len(windows)}\n")

    print("=== VS Code windows ===")
    vscode_count = 0
    for w in windows:
        wm_class = (w.get("wm_class") or "").lower()
        if "code" in wm_class or "cursor" in wm_class:
            vscode_count += 1
            title = w.get("title")
            print(f"  title: {title!r}")
            print(f"  wm_class: {w.get('wm_class')!r}")
            print(f"  pid: {w.get('pid')}")
            print()
    if not vscode_count:
        print("  (none found)\n")

    print("=== Windows with None title or wm_class ===")
    none_count = 0
    for w in windows:
        t = w.get("title")
        c = w.get("wm_class")
        if t is None or c is None:
            none_count += 1
            print(f"  title={t!r} wm_class={c!r} pid={w.get('pid')}")
    if not none_count:
        print("  (none found)")

    # Test sandbox matching
    sandbox_names = ["myapp-1176", "myapp-ui-main", "myapp-pr-1208", "myapp-issue-77243"]
    print(f"\n=== Sandbox match test ===")
    vscode_titles = set()
    for w in windows:
        wm_class = (w.get("wm_class") or "").lower()
        if "code" in wm_class or "cursor" in wm_class:
            vscode_titles.add((w.get("title") or "").lower())

    for name in sandbox_names:
        matched = any(name.lower() in title for title in vscode_titles)
        print(f"  {name}: {'MATCH' if matched else 'no match'}")


if __name__ == "__main__":
    main()
