# Generated By: Claude Code (Claude Opus 4.6)
"""
Compare prompt-log and transcript files for a Claude Code session.

Usage:
    python compare_logs.py <prompt_log_path> <transcript_path>

Outputs a structured comparison showing:
- Event types in each file
- Schema differences (fields present in each)
- Whether prompt-log content is a subset of transcript content
- What each file provides that the other does not
"""

import json
import sys
from pathlib import Path


def load_jsonl(path: str) -> list[dict]:
    entries = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    return entries


def extract_transcript_user_messages(entries: list[dict]) -> list[dict]:
    """Extract non-meta user messages from transcript."""
    results = []
    for obj in entries:
        if obj.get("type") == "user" and not obj.get("isMeta"):
            msg = obj.get("message", {})
            content = msg.get("content", "")
            if isinstance(content, str):
                results.append({
                    "timestamp": obj.get("timestamp"),
                    "content": content,
                })
    return results


def extract_transcript_assistant_messages(entries: list[dict]) -> list[dict]:
    """Extract assistant text responses from transcript."""
    results = []
    for obj in entries:
        if obj.get("type") == "assistant":
            msg = obj.get("message", {})
            parts = msg.get("content", [])
            text = ""
            for p in parts:
                if isinstance(p, dict) and p.get("type") == "text":
                    text += p.get("text", "")
            if text.strip():
                results.append({
                    "timestamp": obj.get("timestamp"),
                    "content": text,
                    "model": msg.get("model"),
                    "usage": msg.get("usage"),
                    "stop_reason": msg.get("stop_reason"),
                })
    return results


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <prompt_log_path> <transcript_path>")
        sys.exit(1)

    plog_path, transcript_path = sys.argv[1], sys.argv[2]

    plog = load_jsonl(plog_path)
    transcript = load_jsonl(transcript_path)

    # --- File sizes ---
    print("=" * 70)
    print("FILE SIZES")
    print("=" * 70)
    print(f"  Prompt-log:  {len(plog)} entries  ({Path(plog_path).stat().st_size:,} bytes)")
    print(f"  Transcript:  {len(transcript)} entries  ({Path(transcript_path).stat().st_size:,} bytes)")
    print()

    # --- Event types ---
    print("=" * 70)
    print("EVENT TYPES")
    print("=" * 70)
    plog_types = sorted(set(e.get("event_type", "") for e in plog))
    transcript_types = sorted(set(e.get("type", "") for e in transcript))
    print(f"  Prompt-log event_type values: {plog_types}")
    print(f"  Transcript type values:       {transcript_types}")
    print()

    # --- Schema comparison ---
    print("=" * 70)
    print("SCHEMA (fields per entry)")
    print("=" * 70)
    plog_fields = set()
    for e in plog:
        plog_fields.update(e.keys())
    print(f"  Prompt-log fields: {sorted(plog_fields)}")

    transcript_fields_by_type: dict[str, set] = {}
    for e in transcript:
        t = e.get("type", "unknown")
        if t not in transcript_fields_by_type:
            transcript_fields_by_type[t] = set()
        transcript_fields_by_type[t].update(e.keys())
    for t in sorted(transcript_fields_by_type):
        print(f"  Transcript '{t}' fields: {sorted(transcript_fields_by_type[t])}")
    print()

    # --- Content overlap ---
    print("=" * 70)
    print("CONTENT OVERLAP: Is prompt-log a subset of transcript?")
    print("=" * 70)

    t_user = extract_transcript_user_messages(transcript)
    t_asst = extract_transcript_assistant_messages(transcript)

    # Build lookup of transcript content by preview
    t_user_contents = {m["content"][:100] for m in t_user}
    t_asst_contents = {m["content"][:100] for m in t_asst}

    prompts_found = 0
    prompts_missing = 0
    responses_found = 0
    responses_missing = 0

    for entry in plog:
        preview = entry.get("content", "")[:100]
        if entry["event_type"] == "prompt":
            if preview in t_user_contents:
                prompts_found += 1
            else:
                prompts_missing += 1
                print(f"  PROMPT not in transcript: {preview[:60]}...")
        elif entry["event_type"] == "response":
            if not preview.strip():
                # empty response, skip matching
                responses_found += 1
                continue
            if preview in t_asst_contents:
                responses_found += 1
            else:
                responses_missing += 1
                print(f"  RESPONSE not in transcript: {preview[:60]}...")

    total_prompts = prompts_found + prompts_missing
    total_responses = responses_found + responses_missing
    print(f"\n  Prompts:   {prompts_found}/{total_prompts} found in transcript")
    print(f"  Responses: {responses_found}/{total_responses} found in transcript")
    print()

    # --- What transcript has that prompt-log lacks ---
    print("=" * 70)
    print("TRANSCRIPT-ONLY DATA (not in prompt-log)")
    print("=" * 70)
    transcript_extras = [
        "Tool use details (tool calls, tool results, parameters)",
        "System messages and context injections",
        "Progress events (hook_progress, agent_progress)",
        "File history snapshots",
        "Queue operations",
        f"Model info, usage/token counts, stop_reason (from {len(t_asst)} assistant msgs)",
        "UUID chain (parentUuid -> uuid) for message threading",
        "isMeta messages (skill instructions, system prompts)",
        "Version info, entrypoint, slug",
    ]
    for item in transcript_extras:
        print(f"  - {item}")
    print()

    # --- What prompt-log has that transcript lacks ---
    print("=" * 70)
    print("PROMPT-LOG-ONLY DATA (not in transcript)")
    print("=" * 70)
    plog_extras = []

    # Check for fields unique to prompt-log
    # Prompt-log has: timestamp, event_type, session_id, working_dir, git_branch, content
    # Transcript user has: timestamp, type, message, uuid, parentUuid, sessionId, cwd, version, gitBranch, ...
    # The prompt-log 'content' for responses is the FINAL rendered text. The transcript has
    # incremental assistant messages (multiple per turn). Let's check.

    # Count how many assistant messages per user turn in transcript
    turn_count = 0
    for i, e in enumerate(transcript):
        if e.get("type") == "user" and not e.get("isMeta"):
            # Count assistant messages until next user message
            asst_count = 0
            for j in range(i + 1, len(transcript)):
                if transcript[j].get("type") == "user" and not transcript[j].get("isMeta"):
                    break
                if transcript[j].get("type") == "assistant":
                    asst_count += 1
            if asst_count > 1:
                turn_count += 1

    if turn_count > 0:
        plog_extras.append(
            f"Consolidated final response text ({turn_count} turns had multiple "
            f"assistant messages in transcript but single response in prompt-log)"
        )

    plog_extras.append("Simpler schema (flat JSON, 6 fields vs nested objects)")
    plog_extras.append("Explicit event_type field ('prompt'/'response') vs inferring from type+isMeta")

    for item in plog_extras:
        print(f"  - {item}")
    print()

    # --- Verdict ---
    print("=" * 70)
    print("VERDICT")
    print("=" * 70)
    if prompts_missing == 0 and responses_missing == 0:
        print("  The prompt-log content IS a subset of the transcript.")
        print("  Every prompt and response in the prompt-log also appears in the transcript.")
    else:
        print("  The prompt-log contains content NOT found in the transcript.")
    print()
    print("  The prompt-log's value proposition:")
    print("    1. Simpler to parse (flat JSON, 6 fields)")
    print("    2. Pre-consolidated responses (one entry per turn, not N assistant chunks)")
    print("    3. Explicit prompt/response typing (no need to filter isMeta, tool results, etc.)")
    print("    4. Tiny file size compared to transcript")
    print()
    print("  The transcript's advantages:")
    print("    1. Full tool use history (every Read, Bash, Edit call and result)")
    print("    2. Token usage and model metadata per message")
    print("    3. Message threading via UUID chain")
    print("    4. Progress events, hooks, agent dispatches")
    print("    5. State machine data for permission detection (stop_reason, tool_use, is_error)")


if __name__ == "__main__":
    main()
