# Generated By: Claude Code (Claude Opus 4.6)
"""
Claude Dashboard — Linux Session Detection & Window Matching

Diagnostic script to discover running Claude Code sessions on Linux and
map them to their containing application windows. Tests multiple approaches
for window discovery on both Wayland and X11.

Usage:
    python scripts/detect_sessions_linux.py [--json] [--verbose]

Requires: psutil

Findings are used to inform claude_dashboard/platform/linux.py.
"""

import argparse
import json
import os
import platform
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

CLAUDE_HOME = Path.home() / ".claude"
SESSIONS_DIR = CLAUDE_HOME / "sessions"


@dataclass
class WindowInfo:
    """A discovered window on the desktop."""

    window_id: int = 0
    pid: int = 0
    title: str = ""
    wm_class: str = ""


@dataclass
class ContainerInfo:
    """The application containing the Claude session."""

    process_name: str = "Unknown"
    process_pid: int = 0
    container_type: str = "Unknown"
    window_id: int = 0
    window_title: str = ""


@dataclass
class SessionInfo:
    """A discovered Claude Code session."""

    pid: int = 0
    session_id: str = ""
    cwd: str = ""
    started_at: int = 0
    pid_alive: bool = False
    container: Optional[ContainerInfo] = None
    process_chain: list[str] = field(default_factory=list)


# ---- Environment Detection ----


def detect_display_server() -> str:
    """Detect whether we're on Wayland, X11, or unknown."""
    session_type = os.environ.get("XDG_SESSION_TYPE", "")
    if session_type == "wayland":
        return "wayland"
    if session_type == "x11":
        return "x11"
    if os.environ.get("WAYLAND_DISPLAY"):
        return "wayland"
    if os.environ.get("DISPLAY"):
        return "x11"
    return "unknown"


def detect_desktop() -> str:
    """Detect the desktop environment."""
    return os.environ.get("XDG_CURRENT_DESKTOP", "unknown")


def check_tool(name: str) -> bool:
    """Check if a CLI tool is available."""
    try:
        subprocess.run(
            ["which", name], capture_output=True, check=True, timeout=3
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


# ---- Session Discovery ----


def discover_sessions() -> list[SessionInfo]:
    """Read ~/.claude/sessions/*.json to find all registered sessions."""
    sessions = []
    if not SESSIONS_DIR.exists():
        return sessions

    for session_file in SESSIONS_DIR.glob("*.json"):
        try:
            data = json.loads(session_file.read_text(encoding="utf-8"))
            session = SessionInfo(
                pid=data.get("pid", 0),
                session_id=data.get("sessionId", ""),
                cwd=data.get("cwd", ""),
                started_at=data.get("startedAt", 0),
            )
            sessions.append(session)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"Warning: could not read {session_file}: {exc}", file=sys.stderr)

    return sessions


def validate_pid(pid: int) -> bool:
    """Check if a process with the given PID is alive and is Claude."""
    try:
        import psutil

        if not psutil.pid_exists(pid):
            return False
        proc = psutil.Process(pid)
        return "claude" in proc.name().lower()
    except Exception:
        return False


def walk_process_chain(pid: int) -> list[str]:
    """Walk the parent process chain from PID to root."""
    import psutil

    chain = []
    try:
        current = psutil.Process(pid)
        while current:
            chain.append(f"{current.name()} (PID {current.pid})")
            current = current.parent()
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass
    return chain


# ---- Container Detection ----

_TERMINAL_NAMES = {
    "gnome-terminal-server",
    "konsole",
    "xfce4-terminal",
    "alacritty",
    "kitty",
    "wezterm-gui",
    "terminator",
    "tilix",
    "xterm",
    "urxvt",
    "st",
    "foot",
    "ghostty",
}


def detect_container(pid: int) -> ContainerInfo:
    """Walk the parent process chain to identify the containing application."""
    import psutil

    container = ContainerInfo()
    try:
        claude_proc = psutil.Process(pid)
        current = claude_proc.parent()

        while current:
            name = current.name().lower()

            if "code" in name and name != "code":
                # VS Code on Linux is typically "code" binary
                pass
            if name == "code" or name.startswith("code-"):
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = "VSCode"
                break

            if name in _TERMINAL_NAMES:
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = "Terminal"
                break

            if name == "screen":
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = "Screen"
                try:
                    current = current.parent()
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    break
                continue

            if name == "tmux: server" or name.startswith("tmux"):
                container.process_name = current.name()
                container.process_pid = current.pid
                container.container_type = "Terminal"
                break

            try:
                current = current.parent()
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                break

        # Fallback: check TERM_PROGRAM env var
        if container.container_type == "Unknown":
            try:
                env = claude_proc.parent().environ()
                term_prog = env.get("TERM_PROGRAM", "").lower()
                del env  # drop full environment from memory
                if term_prog == "vscode":
                    container.container_type = "VSCode"
                elif term_prog:
                    container.container_type = "Terminal"
                    container.process_name = term_prog
            except (psutil.AccessDenied, psutil.NoSuchProcess, AttributeError):
                pass

    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass

    return container


# ---- Window Matching: Multiple Approaches ----


def list_windows_xdotool() -> list[WindowInfo]:
    """List windows using xdotool (X11 / XWayland)."""
    windows = []
    try:
        result = subprocess.run(
            ["xdotool", "search", "--name", ""],
            capture_output=True,
            text=True,
            timeout=5,
        )
        for line in result.stdout.strip().splitlines():
            wid = int(line.strip())
            info = WindowInfo(window_id=wid)
            # Get PID
            try:
                r = subprocess.run(
                    ["xdotool", "getwindowpid", str(wid)],
                    capture_output=True,
                    text=True,
                    timeout=3,
                )
                if r.returncode == 0 and r.stdout.strip():
                    info.pid = int(r.stdout.strip())
            except (subprocess.CalledProcessError, ValueError):
                pass
            # Get title
            try:
                r = subprocess.run(
                    ["xdotool", "getwindowname", str(wid)],
                    capture_output=True,
                    text=True,
                    timeout=3,
                )
                if r.returncode == 0:
                    info.title = r.stdout.strip()
            except subprocess.CalledProcessError:
                pass
            windows.append(info)
    except FileNotFoundError:
        print("  xdotool not installed", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("  xdotool timed out", file=sys.stderr)
    return windows


def list_windows_wmctrl() -> list[WindowInfo]:
    """List windows using wmctrl (X11 / XWayland)."""
    windows = []
    try:
        result = subprocess.run(
            ["wmctrl", "-l", "-p"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        for line in result.stdout.strip().splitlines():
            parts = line.split(None, 4)
            if len(parts) >= 5:
                wid = int(parts[0], 16)
                pid = int(parts[2])
                title = parts[4] if len(parts) > 4 else ""
                windows.append(WindowInfo(window_id=wid, pid=pid, title=title))
    except FileNotFoundError:
        print("  wmctrl not installed", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("  wmctrl timed out", file=sys.stderr)
    return windows


def list_windows_gnome_dbus() -> list[WindowInfo]:
    """List windows using GNOME Shell D-Bus eval (requires unsafe-mode).

    NOTE: Blocked on GNOME 45+ by default. Kept for reference only.
    Use list_windows_window_calls() instead.
    """
    windows = []
    js_code = (
        "global.get_window_actors().map(a => {"
        " let w = a.get_meta_window();"
        " return JSON.stringify({pid: w.get_pid(), title: w.get_title(), id: w.get_id()});"
        "}).join('\\n')"
    )
    try:
        result = subprocess.run(
            [
                "gdbus",
                "call",
                "--session",
                "--dest",
                "org.gnome.Shell",
                "--object-path",
                "/org/gnome/Shell",
                "--method",
                "org.gnome.Shell.Eval",
                js_code,
            ],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            raw = result.stdout.strip()
            if "'," in raw or "')" in raw:
                start = raw.index("'") + 1
                end = raw.rindex("'")
                data_str = raw[start:end]
                for line in data_str.split("\\n"):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                        windows.append(
                            WindowInfo(
                                window_id=obj.get("id", 0),
                                pid=obj.get("pid", 0),
                                title=obj.get("title", ""),
                            )
                        )
                    except json.JSONDecodeError:
                        pass
        else:
            stderr_msg = result.stderr.strip()[:200] if result.stderr else ""
            print(f"  gdbus eval failed: rc={result.returncode} {stderr_msg}", file=sys.stderr)
    except FileNotFoundError:
        print("  gdbus not found", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("  gdbus timed out", file=sys.stderr)
    return windows


def list_windows_window_calls() -> list[WindowInfo]:
    """List windows using the window-calls GNOME Shell extension via D-Bus.

    This is the preferred method on GNOME/Wayland. Requires the
    window-calls extension: https://extensions.gnome.org/extension/4724/window-calls/

    D-Bus path: /org/gnome/Shell/Extensions/Windows
    Methods: List (enumerate), Activate (foreground by ID)
    """
    windows = []
    try:
        result = subprocess.run(
            [
                "gdbus",
                "call",
                "--session",
                "--dest",
                "org.gnome.Shell",
                "--object-path",
                "/org/gnome/Shell/Extensions/Windows",
                "--method",
                "org.gnome.Shell.Extensions.Windows.List",
            ],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            stderr_msg = result.stderr.strip()[:200] if result.stderr else ""
            print(f"  window-calls List failed: {stderr_msg}", file=sys.stderr)
            return windows

        raw = result.stdout.strip()
        # gdbus wraps output as ('json_string',)
        if raw.startswith("('") and raw.endswith("',)"):
            json_str = raw[2:-3]
        elif raw.startswith("('") and raw.endswith("')"):
            json_str = raw[2:-2]
        else:
            print(f"  unexpected gdbus output format: {raw[:100]}", file=sys.stderr)
            return windows

        for obj in json.loads(json_str):
            windows.append(
                WindowInfo(
                    window_id=obj.get("id", 0),
                    pid=obj.get("pid", 0),
                    title=obj.get("title", ""),
                    wm_class=obj.get("wm_class", ""),
                )
            )
    except FileNotFoundError:
        print("  gdbus not found", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("  window-calls List timed out", file=sys.stderr)
    except (json.JSONDecodeError, ValueError) as exc:
        print(f"  failed to parse window-calls output: {exc}", file=sys.stderr)
    return windows


def list_windows_xprop() -> list[WindowInfo]:
    """List windows using xprop + xwininfo (X11/XWayland fallback).

    Uses the root window's _NET_CLIENT_LIST to enumerate windows,
    then queries each for _NET_WM_PID and WM_NAME.
    """
    windows = []
    try:
        # Get client list from root window
        result = subprocess.run(
            ["xprop", "-root", "_NET_CLIENT_LIST"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            print("  xprop: _NET_CLIENT_LIST not available", file=sys.stderr)
            return windows

        # Parse window IDs from output like:
        # _NET_CLIENT_LIST(WINDOW): window id # 0x1234, 0x5678
        line = result.stdout.strip()
        if "#" not in line:
            return windows

        wid_str = line.split("#", 1)[1]
        wids = []
        for part in wid_str.split(","):
            part = part.strip()
            if part:
                try:
                    wids.append(int(part, 16))
                except ValueError:
                    pass

        for wid in wids:
            info = WindowInfo(window_id=wid)
            # Get PID
            try:
                r = subprocess.run(
                    ["xprop", "-id", str(wid), "_NET_WM_PID"],
                    capture_output=True,
                    text=True,
                    timeout=3,
                )
                if "=" in r.stdout:
                    info.pid = int(r.stdout.split("=")[1].strip())
            except (subprocess.CalledProcessError, ValueError, IndexError):
                pass
            # Get title
            try:
                r = subprocess.run(
                    ["xprop", "-id", str(wid), "WM_NAME"],
                    capture_output=True,
                    text=True,
                    timeout=3,
                )
                if "=" in r.stdout:
                    # WM_NAME(UTF8_STRING) = "title here"
                    title_part = r.stdout.split("=", 1)[1].strip()
                    info.title = title_part.strip('"')
            except (subprocess.CalledProcessError, ValueError, IndexError):
                pass
            windows.append(info)
    except FileNotFoundError:
        print("  xprop not found", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("  xprop timed out", file=sys.stderr)
    return windows


def match_window_to_container(
    container: ContainerInfo, windows: list[WindowInfo], cwd: str
) -> ContainerInfo:
    """Match a container process to a window from the enumerated list."""
    if container.process_pid == 0:
        return container

    import psutil

    # Collect all PIDs in the container's process tree
    target_pids = {container.process_pid}
    try:
        proc = psutil.Process(container.process_pid)
        for child in proc.children(recursive=True):
            target_pids.add(child.pid)
        # Also walk up to find the top-level process
        parent = proc.parent()
        if parent and parent.name().lower() == container.process_name.lower():
            target_pids.add(parent.pid)
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass

    # Find windows owned by any PID in the tree
    candidates = [w for w in windows if w.pid in target_pids]

    if not candidates:
        # Broader search: any window whose PID is in the tree
        return container

    # For VS Code, prefer window title matching the CWD folder name
    folder_name = Path(cwd).name.lower()
    for w in candidates:
        if folder_name in w.title.lower():
            container.window_id = w.window_id
            container.window_title = w.title
            return container

    # Fallback: first visible window
    if candidates:
        container.window_id = candidates[0].window_id
        container.window_title = candidates[0].title

    return container


# ---- Foreground ----


def foreground_window_xdotool(window_id: int) -> bool:
    """Foreground using xdotool (X11/XWayland)."""
    try:
        subprocess.run(
            ["xdotool", "windowactivate", str(window_id)],
            check=True,
            capture_output=True,
            timeout=3,
        )
        return True
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        print(f"  xdotool foreground failed: {exc}", file=sys.stderr)
        return False


def foreground_window_gnome_dbus(window_id: int) -> bool:
    """Foreground using GNOME Shell D-Bus (Wayland-native).

    Uses the activate_window method on the Meta.Window object.
    """
    js_code = (
        f"let start = global.get_current_time();"
        f"global.get_window_actors().forEach(a => {{"
        f"  let w = a.get_meta_window();"
        f"  if (w.get_id() === {window_id}) w.activate(start);"
        f"}});"
    )
    try:
        result = subprocess.run(
            [
                "gdbus",
                "call",
                "--session",
                "--dest",
                "org.gnome.Shell",
                "--object-path",
                "/org/gnome/Shell",
                "--method",
                "org.gnome.Shell.Eval",
                js_code,
            ],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        print(f"  gdbus foreground failed: {exc}", file=sys.stderr)
        return False


def foreground_window_xprop(window_id: int) -> bool:
    """Foreground using xdotool with hex window ID from xprop."""
    return foreground_window_xdotool(window_id)


# ---- Additional Diagnostics ----


def probe_dbus_interfaces() -> dict[str, str]:
    """Probe GNOME/freedesktop D-Bus interfaces for window management capabilities.

    Returns a dict of interface -> status describing what's available.
    """
    results = {}

    # 1. GNOME Shell Eval (needs unsafe mode on GNOME 45+)
    try:
        r = subprocess.run(
            [
                "gdbus", "call", "--session",
                "--dest", "org.gnome.Shell",
                "--object-path", "/org/gnome/Shell",
                "--method", "org.gnome.Shell.Eval",
                "1+1",
            ],
            capture_output=True, text=True, timeout=5,
        )
        if r.returncode == 0:
            success = r.stdout.strip().startswith("(true")
            results["gnome.Shell.Eval"] = "WORKS" if success else "BLOCKED (unsafe mode disabled)"
        else:
            results["gnome.Shell.Eval"] = f"FAILED rc={r.returncode}"
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        results["gnome.Shell.Eval"] = f"ERROR: {exc}"

    # 2. GNOME Shell FocusApp
    try:
        r = subprocess.run(
            [
                "gdbus", "call", "--session",
                "--dest", "org.gnome.Shell",
                "--object-path", "/org/gnome/Shell",
                "--method", "org.gnome.Shell.FocusApp",
                "org.gnome.Nautilus.desktop",
            ],
            capture_output=True, text=True, timeout=5,
        )
        if "AccessDenied" in (r.stderr or ""):
            results["gnome.Shell.FocusApp"] = "BLOCKED (AccessDenied)"
        elif r.returncode == 0:
            results["gnome.Shell.FocusApp"] = "WORKS"
        else:
            results["gnome.Shell.FocusApp"] = f"FAILED rc={r.returncode}"
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        results["gnome.Shell.FocusApp"] = f"ERROR: {exc}"

    # 3. XDG Desktop Portal — check available interfaces
    try:
        r = subprocess.run(
            [
                "gdbus", "introspect", "--session",
                "--dest", "org.freedesktop.portal.Desktop",
                "--object-path", "/org/freedesktop/portal/desktop",
            ],
            capture_output=True, text=True, timeout=5,
        )
        interfaces = []
        for line in r.stdout.splitlines():
            line = line.strip()
            if line.startswith("interface ") and "{" in line:
                iface = line.split()[1]
                if "freedesktop" in iface or "gnome" in iface:
                    interfaces.append(iface)
        results["xdg.portal.interfaces"] = ", ".join(interfaces) if interfaces else "none"
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        results["xdg.portal"] = f"ERROR: {exc}"

    # 4. GNOME Shell introspection — list available methods
    try:
        r = subprocess.run(
            [
                "gdbus", "introspect", "--session",
                "--dest", "org.gnome.Shell",
                "--object-path", "/org/gnome/Shell",
            ],
            capture_output=True, text=True, timeout=5,
        )
        methods = []
        for line in r.stdout.splitlines():
            line = line.strip()
            if line.startswith("Eval(") or line.startswith("Focus") or "Activate" in line:
                methods.append(line.split("(")[0])
        results["gnome.Shell.methods"] = ", ".join(methods) if methods else "see introspect"
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        results["gnome.Shell.introspect"] = f"ERROR: {exc}"

    # 5. Check if GNOME Shell extensions can help
    try:
        r = subprocess.run(
            ["gnome-extensions", "list", "--enabled"],
            capture_output=True, text=True, timeout=5,
        )
        if r.returncode == 0:
            extensions = [e.strip() for e in r.stdout.strip().splitlines() if e.strip()]
            results["gnome.extensions.enabled"] = ", ".join(extensions) if extensions else "none"
        else:
            results["gnome.extensions"] = "gnome-extensions command failed"
    except FileNotFoundError:
        results["gnome.extensions"] = "gnome-extensions not found"
    except subprocess.TimeoutExpired:
        results["gnome.extensions"] = "timed out"

    return results


def analyze_vscode_processes() -> dict[int, dict]:
    """Analyze VS Code process tree to map workspace windows.

    VS Code runs multiple processes:
    - Main process (parent is systemd/init)
    - Renderer processes (--type=renderer) — one per window
    - GPU, utility, crashpad helpers

    The renderer cmdline contains --vscode-window-config with a path
    that includes the workspace folder. The PID of the renderer owns
    the actual window.
    """
    import psutil

    results = {}

    # Find all VS Code processes
    code_procs = []
    for proc in psutil.process_iter(["pid", "name", "ppid"]):
        try:
            if proc.info["name"] and proc.info["name"].lower() in ("code", "code-oss"):
                code_procs.append(proc)
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass

    if not code_procs:
        return results

    for proc in code_procs:
        try:
            cmdline = proc.cmdline()
            cmdline_str = " ".join(cmdline)
            info = {
                "pid": proc.pid,
                "ppid": proc.ppid(),
                "name": proc.name(),
                "type": "unknown",
                "cmdline_summary": cmdline_str[:200],
            }

            # Classify process type from --type= flag
            for arg in cmdline:
                if arg.startswith("--type="):
                    info["type"] = arg.split("=")[1]
                    break
            else:
                # No --type flag = main process or window host
                if any("--folder-uri" in a or "--file-uri" in a for a in cmdline):
                    info["type"] = "window-host"
                else:
                    info["type"] = "main"

            # Extract workspace info from various cmdline patterns
            for i, arg in enumerate(cmdline):
                if arg == "--folder-uri" and i + 1 < len(cmdline):
                    info["folder_uri"] = cmdline[i + 1]
                if arg.startswith("--folder-uri="):
                    info["folder_uri"] = arg.split("=", 1)[1]
                if "--vscode-window-config" in arg:
                    info["window_config"] = arg[:200]

            # Check environment for workspace hints
            try:
                env = proc.environ()
                if "VSCODE_PID" in env:
                    info["vscode_pid"] = env["VSCODE_PID"]
                if "VSCODE_CWD" in env:
                    info["vscode_cwd"] = env["VSCODE_CWD"]
                del env
            except (psutil.AccessDenied, psutil.NoSuchProcess):
                pass

            results[proc.pid] = info
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass

    return results


def find_vscode_window_for_cwd(cwd: str) -> dict:
    """Find the specific VS Code window process that has a given CWD open.

    Returns info about the matching process, or empty dict if not found.
    """
    vscode_procs = analyze_vscode_processes()
    folder_name = Path(cwd).name

    # Strategy 1: match by --folder-uri in renderer/window-host cmdline
    for pid, info in vscode_procs.items():
        folder_uri = info.get("folder_uri", "")
        if folder_uri and (cwd in folder_uri or folder_name in folder_uri):
            info["match_method"] = "folder_uri"
            return info

    # Strategy 2: match by VSCODE_CWD environment
    for pid, info in vscode_procs.items():
        vscode_cwd = info.get("vscode_cwd", "")
        if vscode_cwd and cwd == vscode_cwd:
            info["match_method"] = "vscode_cwd"
            return info

    # Strategy 3: match by window config path containing folder name
    for pid, info in vscode_procs.items():
        config = info.get("window_config", "")
        if config and folder_name in config:
            info["match_method"] = "window_config"
            return info

    return {}


def probe_activation_methods(
    container: ContainerInfo, cwd: str
) -> dict[str, str]:
    """Test various methods to activate/foreground a specific container window.

    Only tests non-destructive probes. Returns status for each method.
    """
    results = {}

    if container.process_pid == 0:
        results["skip"] = "no container PID"
        return results

    # 1. VS Code CLI: `code /path` activates the window with that folder open
    if container.container_type == "VSCode":
        try:
            # First check if code CLI is available
            r = subprocess.run(
                ["which", "code"],
                capture_output=True, text=True, timeout=3,
            )
            if r.returncode == 0:
                results["code CLI"] = f"available at {r.stdout.strip()}"
                results["code /path (theory)"] = (
                    f"`code {cwd}` should activate the window with this folder. "
                    f"Uses --reuse-window semantics."
                )
            else:
                results["code CLI"] = "not in PATH"
        except (FileNotFoundError, subprocess.TimeoutExpired):
            results["code CLI"] = "check failed"

    # 2. gtk-launch: activates the application generically (not window-specific)
    app_id = ""
    if container.container_type == "VSCode":
        app_id = "code.desktop"
    elif container.container_type == "Terminal":
        app_id = "org.gnome.Terminal.desktop"

    if app_id:
        results[f"gtk-launch {app_id}"] = "activates app generically (NOT window-specific)"

    # 3. xdotool (if installed)
    if container.window_id:
        try:
            r = subprocess.run(
                ["xdotool", "windowactivate", str(container.window_id)],
                capture_output=True, text=True, timeout=3,
            )
            results["xdotool windowactivate"] = (
                "WORKS" if r.returncode == 0 else f"FAILED rc={r.returncode}"
            )
        except FileNotFoundError:
            results["xdotool"] = "not installed"
        except subprocess.TimeoutExpired:
            results["xdotool"] = "timed out"

    # 4. wmctrl -ia (if available)
    if container.window_id:
        try:
            r = subprocess.run(
                ["wmctrl", "-ia", str(container.window_id)],
                capture_output=True, text=True, timeout=3,
            )
            results["wmctrl -ia"] = "WORKS" if r.returncode == 0 else f"FAILED rc={r.returncode}"
        except FileNotFoundError:
            results["wmctrl"] = "not installed"
        except subprocess.TimeoutExpired:
            results["wmctrl"] = "timed out"

    # 5. xdg-activation (Wayland protocol)
    results["xdg-activation"] = "requires app cooperation, no standalone CLI"

    return results


# ---- Main ----


def main():
    parser = argparse.ArgumentParser(
        description="Linux session detection and window matching diagnostic"
    )
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--verbose", action="store_true", help="Show extra details")
    args = parser.parse_args()

    print("=== Environment ===")
    display_server = detect_display_server()
    desktop = detect_desktop()
    print(f"  Display server: {display_server}")
    print(f"  Desktop: {desktop}")
    print(f"  DISPLAY: {os.environ.get('DISPLAY', '(not set)')}")
    print(f"  WAYLAND_DISPLAY: {os.environ.get('WAYLAND_DISPLAY', '(not set)')}")
    print()

    tools = ["xdotool", "wmctrl", "xprop", "xwininfo", "gdbus", "gtk-launch", "gnome-extensions"]
    print("=== Available Tools ===")
    for tool in tools:
        available = check_tool(tool)
        print(f"  {tool}: {'YES' if available else 'no'}")
    print()

    print("=== D-Bus Interface Probes ===")
    dbus_probes = probe_dbus_interfaces()
    for iface, status in dbus_probes.items():
        print(f"  {iface}: {status}")
    print()

    print("=== Window Enumeration Methods ===")

    print("\n--- Method 1: xprop (_NET_CLIENT_LIST) ---")
    xprop_windows = list_windows_xprop()
    print(f"  Found {len(xprop_windows)} windows")
    for w in xprop_windows[:10]:
        print(f"    id=0x{w.window_id:x} pid={w.pid} title={w.title!r}")

    print("\n--- Method 2: xdotool ---")
    xdotool_windows = list_windows_xdotool()
    print(f"  Found {len(xdotool_windows)} windows")
    for w in xdotool_windows[:10]:
        print(f"    id=0x{w.window_id:x} pid={w.pid} title={w.title!r}")

    print("\n--- Method 3: wmctrl ---")
    wmctrl_windows = list_windows_wmctrl()
    print(f"  Found {len(wmctrl_windows)} windows")
    for w in wmctrl_windows[:10]:
        print(f"    id=0x{w.window_id:x} pid={w.pid} title={w.title!r}")

    print("\n--- Method 4: GNOME Shell D-Bus (Eval, requires unsafe-mode) ---")
    dbus_windows = list_windows_gnome_dbus()
    print(f"  Found {len(dbus_windows)} windows")
    for w in dbus_windows[:10]:
        print(f"    id={w.window_id} pid={w.pid} title={w.title!r}")

    print("\n--- Method 5: window-calls GNOME extension (PREFERRED) ---")
    wc_windows = list_windows_window_calls()
    print(f"  Found {len(wc_windows)} windows")
    for w in wc_windows[:10]:
        print(f"    id={w.window_id} pid={w.pid} class={w.wm_class!r} title={w.title!r}")

    # Pick the best window list — prefer window-calls extension
    best_windows = wc_windows or xprop_windows or dbus_windows or xdotool_windows or wmctrl_windows
    best_method = (
        "window-calls"
        if wc_windows
        else "xprop"
        if xprop_windows
        else "gdbus-eval"
        if dbus_windows
        else "xdotool"
        if xdotool_windows
        else "wmctrl"
        if wmctrl_windows
        else "none"
    )
    print(f"\n  Best method: {best_method} ({len(best_windows)} windows)")

    print("\n=== Claude Sessions ===")
    sessions = discover_sessions()

    if not sessions:
        print("  No sessions found in ~/.claude/sessions/")
        return

    for session in sessions:
        session.pid_alive = validate_pid(session.pid)
        if session.pid_alive:
            session.process_chain = walk_process_chain(session.pid)
            session.container = detect_container(session.pid)
            session.container = match_window_to_container(
                session.container, best_windows, session.cwd
            )

    if args.json:
        output = [asdict(s) for s in sessions]
        print(json.dumps(output, indent=2))
    else:
        for session in sessions:
            alive = "ALIVE" if session.pid_alive else "DEAD"
            print(f"\n  Session: {session.session_id[:16]}...")
            print(f"    PID:       {session.pid} ({alive})")
            print(f"    CWD:       {session.cwd}")
            if session.container:
                c = session.container
                print(f"    Container: {c.container_type} ({c.process_name})")
                if c.window_id:
                    wid_hex = f"0x{c.window_id:x}" if c.window_id > 0xFF else str(c.window_id)
                    print(f"    Window:    {wid_hex} {c.window_title!r}")
            if args.verbose and session.process_chain:
                print(f"    Chain:     {' -> '.join(session.process_chain)}")

    # VS Code process analysis
    print("\n=== VS Code Process Analysis ===")
    vscode_procs = analyze_vscode_processes()
    if vscode_procs:
        for pid, info in sorted(vscode_procs.items()):
            ptype = info.get("type", "?")
            print(f"\n  PID {pid} [{ptype}]")
            if info.get("folder_uri"):
                print(f"    folder_uri: {info['folder_uri']}")
            if info.get("vscode_cwd"):
                print(f"    vscode_cwd: {info['vscode_cwd']}")
            if info.get("window_config"):
                print(f"    window_config: {info['window_config']}")
            if args.verbose:
                print(f"    cmdline: {info.get('cmdline_summary', '')}")
    else:
        print("  No VS Code processes found")

    # Window matching for each VS Code session
    print("\n=== VS Code Window Matching ===")
    for session in sessions:
        if session.pid_alive and session.container and session.container.container_type == "VSCode":
            match = find_vscode_window_for_cwd(session.cwd)
            if match:
                print(f"\n  CWD: {session.cwd}")
                print(f"    Matched PID: {match.get('pid')}")
                print(f"    Match method: {match.get('match_method')}")
                if match.get("folder_uri"):
                    print(f"    folder_uri: {match['folder_uri']}")
            else:
                print(f"\n  CWD: {session.cwd}")
                print(f"    NO MATCH FOUND")

    # Test activation methods on each unique container type
    print("\n=== Activation Method Probes ===")
    tested_types = set()
    for session in sessions:
        if not session.pid_alive or not session.container:
            continue
        ctype = session.container.container_type
        if ctype in tested_types:
            continue
        tested_types.add(ctype)
        print(f"\n  Testing activation for {ctype} "
              f"({session.container.process_name}, PID {session.container.process_pid}):")
        probes = probe_activation_methods(session.container, session.cwd)
        for method, status in probes.items():
            print(f"    {method}: {status}")
    if not tested_types:
        print("  No live sessions with containers to test")


if __name__ == "__main__":
    main()
