# Generated By: Claude Code (Claude Opus 4.6)
"""Generate high-resolution icon PNGs from the tray icon drawing code.

Usage:
    python scripts/generate_icon.py [--size 512] [--color '#047857'] [--output assets/icon.png]
"""

import argparse
import sys
from pathlib import Path

# Add project root to path so we can import claude_dashboard
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from PIL import Image, ImageDraw


def generate_icon(
    *,
    size: int = 512,
    color: tuple[int, int, int] = (128, 128, 128),
) -> Image.Image:
    """Generate the icon at an arbitrary size.

    Uses the same design as tray.py's generate_icon_image but scaled
    proportionally to the requested size. Base design is 64x64.
    """
    scale = size / 64
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    cx, cy = size // 2, size // 2
    margin = round(3 * scale)

    # Outer eye (filled circle)
    draw.ellipse([margin, margin, size - margin, size - margin], fill=color)

    # Iris/pupil (dark circle, offset right and slightly up)
    pupil_r = round(10 * scale)
    pupil_cx = cx + round(6 * scale)
    pupil_cy = cy - round(2 * scale)
    draw.ellipse(
        [pupil_cx - pupil_r, pupil_cy - pupil_r,
         pupil_cx + pupil_r, pupil_cy + pupil_r],
        fill=(20, 20, 20),
    )

    return image


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def main():
    parser = argparse.ArgumentParser(description="Generate high-res icon PNG")
    parser.add_argument("--size", type=int, default=512, help="Icon size in pixels (default: 512)")
    parser.add_argument("--color", default="#808080", help="Fill color as hex (default: #808080)")
    parser.add_argument("--output", default="assets/icon.png", help="Output path (default: assets/icon.png)")
    args = parser.parse_args()

    color = hex_to_rgb(args.color)
    image = generate_icon(size=args.size, color=color)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    image.save(str(output))
    print(f"Saved {output} ({args.size}x{args.size}, color={args.color})")


if __name__ == "__main__":
    main()
