#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Relay hook events to the dashboard HTTP server.

Used as a Claude Code command hook. Reads JSON from stdin,
POSTs it to the dashboard's HTTP server on localhost:17384.
Non-blocking — if the server is down, exits silently.

Also logs raw payloads to a JSONL file for debugging/research.
Use --marker TEXT to inject a labeled boundary line into the log.
"""

import argparse
import json
import logging
import logging.handlers
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

EXIT_SUCCESS = 0
EXIT_ERROR = 1

_PAYLOAD_LOG_DIR = Path.home() / ".claude" / "claude-dashboard" / "logs"
_PAYLOAD_LOG_FILE = _PAYLOAD_LOG_DIR / "hook-payloads.jsonl"

logger = logging.getLogger(__name__)


def _configure_logging(*, debug: bool, quiet: bool, log_file: str | None) -> None:
    """Set up logging. In debug mode, also log raw payloads to a JSONL file."""
    if quiet:
        level = logging.WARNING
    elif debug:
        level = logging.DEBUG
    else:
        level = logging.WARNING
    log_fmt = "%(asctime)s %(levelname)s %(name)s: %(message)s"
    if log_file:
        log_path = str(Path(log_file).expanduser().resolve())
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        handler: logging.Handler = logging.handlers.RotatingFileHandler(
            log_path, maxBytes=2 * 1024 * 1024, backupCount=1, encoding="utf-8"
        )
        handler.setFormatter(logging.Formatter(log_fmt))
        logging.basicConfig(level=level, handlers=[handler])
    else:
        logging.basicConfig(level=level, format=log_fmt, stream=sys.stderr)
    if debug:
        logger.setLevel(logging.DEBUG)
        try:
            _PAYLOAD_LOG_DIR.mkdir(parents=True, exist_ok=True)
            payload_handler = logging.handlers.RotatingFileHandler(
                _PAYLOAD_LOG_FILE,
                maxBytes=2 * 1024 * 1024,
                backupCount=1,
                encoding="utf-8",
            )
            payload_handler.setLevel(logging.DEBUG)
            payload_handler.setFormatter(logging.Formatter("%(message)s"))
            logger.addHandler(payload_handler)
        except OSError:
            pass


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Relay Claude Code hook events to the dashboard HTTP server."
    )
    parser.add_argument("--debug", action="store_true", help="enable debug logging")
    parser.add_argument(
        "--quiet", "-q", action="store_true", help="suppress non-essential output"
    )
    parser.add_argument(
        "--log-file", type=str, default=None, help="write log output to file"
    )
    parser.add_argument(
        "--marker",
        nargs="*",
        default=None,
        help="inject a labeled boundary line into the payload log and exit",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    debug = bool(args.debug or args.marker is not None)
    _configure_logging(debug=debug, quiet=args.quiet, log_file=args.log_file)

    if args.marker is not None:
        marker_text = " ".join(args.marker)
        logger.debug(json.dumps({"_marker": marker_text, "_ts": _now_iso()}))
        return EXIT_SUCCESS

    try:
        data = sys.stdin.read()
        if not data:
            return EXIT_SUCCESS

        if debug:
            try:
                payload = json.loads(data)
                payload["_ts"] = _now_iso()
                logger.debug(json.dumps(payload))
            except (json.JSONDecodeError, TypeError):
                logger.debug(json.dumps({"_raw": data, "_ts": _now_iso()}))

        req = urllib.request.Request(
            "http://127.0.0.1:17384/hook",
            data=data.encode(),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=2)
    except Exception:
        if debug:
            logger.debug("relay failed", exc_info=True)
    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
