# Generated By: Claude Code (Claude Opus 4.6)
"""Diagnostic script to test Loki queries for last user prompt.

Usage:
    python scripts/test_loki_query.py [loki_url] [session_id]

Defaults: loki_url=http://localhost:3100, session_id=auto-detect from first active session
"""

import json
import sys
import urllib.parse
import urllib.request


def query_loki(loki_url: str, query: str, limit: int = 5) -> dict:
    """Query Loki and return raw response."""
    params = urllib.parse.urlencode({
        "query": query,
        "direction": "backward",
        "limit": str(limit),
    })
    url = f"{loki_url}/loki/api/v1/query?{params}"
    print(f"\n--- GET {url}")
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=5) as resp:
            raw = resp.read()
            data = json.loads(raw)
            print(f"    status: {data.get('status')}")
            results = data.get("data", {}).get("result", [])
            print(f"    resultType: {data.get('data', {}).get('resultType')}")
            print(f"    streams: {len(results)}")
            return data
    except Exception as exc:
        print(f"    FAILED: {exc}")
        return {}


def main():
    loki_url = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:3100"
    session_id = sys.argv[2] if len(sys.argv) > 2 else None

    # 1. Basic connectivity
    print("=== Step 1: Loki connectivity ===")
    query_loki(loki_url, '{service_name="claude-code"}', limit=1)

    # 2. Check what event_name values exist
    print("\n=== Step 2: Recent event_names ===")
    data = query_loki(loki_url, '{service_name="claude-code"}', limit=10)
    if data.get("status") == "success":
        for stream in data["data"]["result"]:
            labels = stream.get("stream", {})
            print(f"    stream labels: {json.dumps(labels, indent=6)}")
            for ts, line in stream.get("values", [])[:2]:
                # Try to parse and show relevant fields
                try:
                    parsed = json.loads(line)
                    keys = list(parsed.keys())[:10]
                    print(f"    log line keys: {keys}")
                    for k in ["event_name", "body", "message", "session_id"]:
                        if k in parsed:
                            val = str(parsed[k])[:100]
                            print(f"      {k}: {val}")
                except json.JSONDecodeError:
                    print(f"    raw line: {line[:200]}")

    # 3. Try user_prompt filter as structured metadata
    print("\n=== Step 3: user_prompt via label filter ===")
    query_loki(loki_url, '{service_name="claude-code"} | event_name = "user_prompt"', limit=3)

    # 4. Try user_prompt as stream selector (if it's a label, not structured metadata)
    print("\n=== Step 4: user_prompt as stream selector ===")
    query_loki(
        loki_url,
        '{service_name="claude-code", event_name="user_prompt"}',
        limit=3,
    )

    # 5. Try line filter for user_prompt
    print("\n=== Step 5: user_prompt as line filter ===")
    query_loki(loki_url, '{service_name="claude-code"} |= "user_prompt"', limit=3)

    # 6. If session_id provided, try session-specific query
    if session_id:
        print(f"\n=== Step 6: session_id={session_id} ===")

        print("\n--- 6a: session_id as label filter")
        query_loki(
            loki_url,
            f'{{service_name="claude-code"}} | event_name = "user_prompt" | session_id = "{session_id}"',
            limit=3,
        )

        print("\n--- 6b: session_id as stream selector")
        query_loki(
            loki_url,
            f'{{service_name="claude-code", session_id="{session_id}"}} | event_name = "user_prompt"',
            limit=3,
        )

        print("\n--- 6c: session_id as line filter")
        query_loki(
            loki_url,
            f'{{service_name="claude-code"}} |= "{session_id}" |= "user_prompt"',
            limit=3,
        )

    # 7. Show first log line raw for structure analysis
    print("\n=== Step 7: Raw first log line ===")
    data = query_loki(loki_url, '{service_name="claude-code"}', limit=1)
    if data.get("status") == "success":
        for stream in data["data"]["result"]:
            for ts, line in stream.get("values", []):
                print(f"    raw ({len(line)} chars):")
                print(f"    {line[:500]}")


if __name__ == "__main__":
    main()
