# Generated By: Claude Code (Claude Opus 4.6)
LOG_FILE := ~/.claude/claude-dashboard/dashboard.log

.PHONY: run run-reset-position test-tkinter

test-tkinter: $(PYTHON)  ## Verify tkinter is available (system package, not pip)
	@$(PYTHON) -c "import tkinter" 2>/dev/null || { \
		echo ""; \
		echo "ERROR: tkinter is not available to $(PYTHON)"; \
		echo ""; \
		echo "tkinter ships with the OS Python, not from pip, so it cannot be"; \
		echo "declared in pyproject.toml. Install it for your system Python:"; \
		echo ""; \
		echo "  Fedora / RHEL    sudo dnf install python3-tkinter"; \
		echo "  Debian / Ubuntu  sudo apt install python3-tk"; \
		echo "  Arch             sudo pacman -S tk"; \
		echo "  macOS (Homebrew) brew install python-tk"; \
		echo ""; \
		echo "The existing venv picks it up automatically once installed."; \
		echo ""; \
		exit 1; \
	}

run: install-dev test-tkinter ## Start the app (use DEBUG=1 for debug logging)
	@echo "Logging to $(LOG_FILE)"
	$(PYTHON) -m claude_dashboard $(if $(DEBUG),--debug) --log-file $(LOG_FILE)

run-reset-position: install-dev test-tkinter ## Start the app centered on screen (recover an off-screen window)
	@echo "Logging to $(LOG_FILE)"
	$(PYTHON) -m claude_dashboard $(if $(DEBUG),--debug) --log-file $(LOG_FILE) --reset-position
