#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 5 (1M context))
"""Verify OTEL label joins against a live stack, without launching the UI.

Answers three questions the unit tests cannot, because they use fixtures:
  1. Do current state metrics still carry the labels the dashboard joins on?
  2. Does a sandbox row (keyed ``sandbox-<openshell name>``) actually receive
     its state from Prometheus?
  3. Are host-local sessions correctly excluded from the remote block?

Usage (LOCAL_HOSTNAME defaults to the value the dashboard host would see):
    python -m scripts.explore.verify_otel_match --local-hostname phantom \
        --prometheus http://prometheus.example:9090
"""

import argparse
from unittest.mock import patch

from claude_dashboard import config
from claude_dashboard.otel_state import poll_session_states
from claude_dashboard.session import SessionInfo
from claude_dashboard.settings import Settings


def _bare_controller(*, prometheus_url: str, loki_url: str):
    """Build a controller with only the state the OTEL path touches (no Tk)."""
    from claude_dashboard.controller import AppController

    controller = object.__new__(AppController)
    controller._sessions = {}
    controller._session_id_to_pid = {}
    controller._next_synthetic_pid = -1
    controller._settings = Settings(prometheus_url=prometheus_url, loki_url=loki_url)
    controller._saved_state = {}
    controller._refresh_ui = lambda: None
    return controller


def _register_sandbox(controller, *, openshell_name: str, cwd: str) -> int:
    """Register a sandbox row the way _add_sandbox_session keys it."""
    from claude_dashboard.controller import _SessionEntry

    controller._next_synthetic_pid -= 1
    pid = controller._next_synthetic_pid
    session_id = f"sandbox-{openshell_name}"
    entry = _SessionEntry(SessionInfo(pid=pid, session_id=session_id, cwd=cwd, started_at=0))
    entry.sandbox = True
    entry.sandbox_phase = "Ready"
    controller._sessions[pid] = entry
    controller._session_id_to_pid[session_id] = pid
    return pid


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prometheus", default=config.DEFAULT_PROMETHEUS_URL)
    parser.add_argument("--loki", default=config.DEFAULT_LOKI_URL)
    parser.add_argument(
        "--no-register",
        action="store_true",
        help="skip sandbox row registration — simulates a dashboard on another machine",
    )
    parser.add_argument(
        "--local-hostname",
        default=config.LOCAL_HOSTNAME,
        help="host_name label of the machine the dashboard runs on",
    )
    args = parser.parse_args()

    states = poll_session_states(prometheus_url=args.prometheus)
    print(f"state metrics: {len(states)} session(s)\n")

    sandbox_names = []
    for session_id, state in states.items():
        kind = "sandbox" if state.sandbox_openshell_name else "host"
        if state.headless:
            kind += " (headless)"
        print(f"  {state.state.value:20} {kind:20} {state.location}")
        print(f"      session_id={session_id}")
        print(
            f"      host_name={state.host_name!r} "
            f"sandbox_openshell_name={state.sandbox_openshell_name!r}"
        )
        if state.sandbox_openshell_name:
            sandbox_names.append((state.sandbox_openshell_name, state.location))

    if not sandbox_names:
        print("\nno sandbox sessions in current metrics — nothing to join")
        return 0

    controller = _bare_controller(prometheus_url=args.prometheus, loki_url=args.loki)
    pids = (
        {}
        if args.no_register
        else {
            name: _register_sandbox(controller, openshell_name=name, cwd=location)
            for name, location in sandbox_names
        }
    )

    with patch("claude_dashboard.config.LOCAL_HOSTNAME", args.local_hostname):
        controller._update_states_from_otel()

    print(f"\njoin result (LOCAL_HOSTNAME={args.local_hostname!r}):")
    failures = 0
    for name, pid in pids.items():
        entry = controller._sessions[pid]
        matched = entry.state.value
        ok = matched != "idle"
        failures += 0 if ok else 1
        print(f"  {'OK  ' if ok else 'FAIL'} sandbox-{name} -> state={matched}")

    remote = [e for e in controller._sessions.values() if e.remote_host]
    print(f"\nremote rows created: {len(remote)}")
    for entry in remote:
        print(f"  host={entry.remote_host} cwd={entry.session.cwd} state={entry.state.value}")

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
